canonical/multipass

.travis.yml
CMakeLists.txt
bors.toml
snap/snapcraft.yaml
src/CMakeLists.txt
tests/CMakeLists.txt
tests/travis-Coverage.patch
tests/travis-Debug.patch

This will build PRs into master and prepares us to use [bors.tech](http://bors.tech) as our merge bot.

travis: add travis and coverage setup

---

src/daemon/daemon.cpp
src/daemon/daemon.h
src/daemon/daemon_rpc.cpp
src/daemon/daemon_rpc.h
src/rpc/multipass.proto
tests/test_daemon.cpp

Remove unusued exec rpc and related code

[daemon] remove exec dead code

---

.gitmodules

Point libssh submodule to patched fork.

---

3rd-party/CMakeLists.txt

[third-party] Update versions

---

src/sshfs_mount/sshfs_mount.cpp

When getting file stats, explicitly check if a file is a symlink when setting the file type.
Also follow symlinks when necessary to stat the underlying file.
Fixes #81

sshfsmount: Explicitly check if a file is symlink

---

.gitmodules
3rd-party/CMakeLists.txt
include/multipass/exceptions/sshfs_missing_error.h
src/client/CMakeLists.txt
src/client/argparser.cpp
src/daemon/CMakeLists.txt
src/daemon/daemon.cpp
src/daemon/daemon.h
src/daemon/daemon_main.cpp
src/daemon/daemon_rpc.cpp
src/daemon/default_vm_image_vault.cpp
src/platform/backends/qemu/CMakeLists.txt
src/platform/backends/qemu/qemu_virtual_machine_factory.cpp
src/utils/CMakeLists.txt
src/utils/utils.cpp
tests/test_utils.cpp

fmtlib enables Python style string formatting. See http://fmtlib.net

Add and use fmtlib

---

include/multipass/utils.h
src/platform/backends/qemu/qemu_virtual_machine_factory.cpp
src/utils/utils.cpp

network: If the virtual bridge exists, get the subnet of it

---

3rd-party/libssh/CMakeLists.txt
src/sshfs_mount/CMakeLists.txt
tests/CMakeLists.txt

Update to libssh version that supports chacha20-poly1305 for better performance.

Update libssh version to one that supports chacha20-poly1305

---

src/platform/backends/qemu/qemu_virtual_machine_factory.cpp

qemu: Explicitly set iptables rules for the DNS/DHCP ports

---

src/daemon/daemon.cpp

[daemon] Merge vendor and user ssh keys

---

src/utils/utils.cpp
tests/test_utils.cpp

utils: Don't allow '/home' as a source path

---

include/multipass/utils.h
src/client/formatter/json_formatter.cpp
src/client/formatter/table_formatter.cpp
src/daemon/daemon.cpp
src/rpc/multipass.proto
src/utils/utils.cpp
tests/test_output_formatter.cpp

Add missing fields to info and list json outputs.

Add missing fields to json output

---

include/multipass/sshfs_mount/sftp_server.h
src/sshfs_mount/sftp_server.cpp
src/sshfs_mount/sshfs_mount.cpp
tests/test_sftpserver.cpp

sftpserver: Validate mounted directory to prevent jailbreaking

---

src/client/formatter/table_formatter.cpp
src/daemon/daemon.cpp

[info][list]: Don't throw exceptions when image data cannot be retrieved

---

src/daemon/daemon.cpp

[daemon] fix disk size determination on bionic

---

completions/bash/multipass

bash_completions: Implement tab completion for copy-files

---

src/daemon/default_vm_image_vault.cpp

image_vault: Remove instance directory only if cd succeeds

---

include/multipass/url_downloader.h
include/multipass/vm_image.h
src/daemon/default_vm_image_vault.cpp
src/network/url_downloader.cpp
tests/stub_vm_image_vault.h
tests/test_image_vault.cpp
tests/test_qemu_backend.cpp

image_vault: Cache http download images passed in via `--image`

---

src/daemon/daemon_config.cpp
src/daemon/daemon_main.cpp
src/logging/log.cpp

Trap and forward Qt logs to multipass logging.
Install logger as early as possible.
Fixes #205

[daemon] Forward Qt logs to multipass logging

---

include/multipass/ssh/openssh_key_provider.h
include/multipass/ssh/ssh_key_provider.h
src/ssh/openssh_key_provider.cpp
src/ssh/ssh_client_key_provider.cpp
src/ssh/ssh_client_key_provider.h
tests/stub_ssh_key_provider.h
tests/test_ssh_key_provider.cpp

Remove unused private_key_path api

[ssh] Cleanup SSHKeyProvider

---

include/multipass/vm_image_host.h
src/daemon/daemon.cpp
src/daemon/daemon_config.cpp
src/daemon/ubuntu_image_host.cpp
src/daemon/ubuntu_image_host.h
tests/test_ubuntu_image_host.cpp

Also, add 'core' alias info to the custom multipass manifest.

image_host: Add support for a custom 'multipass' manifest

---

src/cert/ssl_cert_provider.cpp

Fix potential memory leaks and potential dangling pointer issues.

[cert] Fix issues with internal classes

---

include/multipass/metrics_provider.h
src/metrics/metrics_provider.cpp
tests/test_metrics_provider.cpp

Use a separate thread for the actual sending of the metrics.

metrics_provider: Retry network errors

---

include/multipass/cli/command.h
src/client/cmd/copy_files.cpp
src/client/cmd/delete.cpp
src/client/cmd/exec.cpp
src/client/cmd/find.cpp
src/client/cmd/info.cpp
src/client/cmd/launch.cpp
src/client/cmd/list.cpp
src/client/cmd/mount.cpp
src/client/cmd/purge.cpp
src/client/cmd/recover.cpp
src/client/cmd/shell.cpp
src/client/cmd/start.cpp
src/client/cmd/stop.cpp
src/client/cmd/umount.cpp

client: Return '3' when it cannot connect to the daemon

---

src/platform/backends/qemu/dnsmasq_server.cpp
src/platform/backends/qemu/qemu_virtual_machine_factory.cpp

backends/qemu: Put network specific files in the new 'network' dir

---

snap/snapcraft.yaml

snap: Add ebtables package for staging for libvirt networking

---

src/platform/backends/backend_utils/backend_utils.cpp
src/platform/backends/libvirt/libvirt_virtual_machine_factory.cpp
src/platform/backends/qemu/qemu_virtual_machine_factory.cpp

backends: Use single bridge name for backend bridges

---

include/multipass/logging/cstring.h
include/multipass/ssh/ssh_session.h
include/multipass/ssh/throw_on_error.h
src/ssh/CMakeLists.txt
src/ssh/openssh_key_provider.cpp
src/ssh/scp_client.cpp
src/ssh/ssh_client.cpp
src/ssh/ssh_process.cpp
src/ssh/ssh_session.cpp
src/sshfs_mount/sftp_server.cpp

Add more detail to ssh related error messages.
Fix incorrect uses of ssh_get_error.

ssh: Improve error messages

---

include/multipass/days.h
include/multipass/url_downloader.h
include/multipass/vm_image_vault.h
src/daemon/daemon.cpp
src/daemon/daemon_config.cpp
src/daemon/daemon_config.h
src/daemon/default_vm_image_vault.h
src/network/url_downloader.cpp
tests/test_image_vault.cpp
tests/test_ubuntu_image_host.cpp

Remove hardcoded timer values.
Passthrough std::chrono values to QTimer when applicable. Make timeout/timer values configurable.

Configurable timers

---

snap/snapcraft.yaml
src/platform/backends/qemu/dnsmasq_server.cpp
src/platform/backends/qemu/dnsmasq_server.h
src/platform/backends/qemu/qemu_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine_factory.cpp
src/platform/backends/qemu/qemu_virtual_machine_factory.h
tests/CMakeLists.txt
tests/mock_dhcp_release.cpp
tests/mock_dnsmasq_server.cpp
tests/test_dnsmasq_server.cpp
tests/test_qemu_backend.cpp
tests/test_with_mocked_bin_path.cpp
tests/test_with_mocked_bin_path.h

qemu: ensure dnsmasq releases unused ip addresses

---

src/daemon/custom_image_host.cpp
src/daemon/default_vm_image_vault.cpp
src/daemon/default_vm_image_vault.h
src/daemon/ubuntu_image_host.cpp
tests/test_custom_image_host.cpp
tests/test_image_vault.cpp
tests/test_ubuntu_image_host.cpp

This fixes #401 and fixes #402.

Fix broken aliases

---

snap/snapcraft.yaml

snap: Add ebtables path for the libvirt part

---

src/platform/backends/libvirt/CMakeLists.txt
tests/CMakeLists.txt
tests/c_mock_defines.cmake
tests/mock_libvirt.cpp
tests/mock_libvirt.h
tests/test_libvirt_backend.cpp

tests: Add mocks and tests for libvirt backend driver

---

include/multipass/ssh/ssh_session.h
src/ssh/ssh_session.cpp

ssh_session: Increase session timeout to 20s to account for busy VM's

---

src/platform/backends/libvirt/libvirt_virtual_machine.cpp

This will make the function names more consistent with other helper functions of this type.

backend/libvirt: Rename helper functions

---

include/multipass/cli/formatter.h
src/client/cmd/mount.cpp
src/client/formatter/json_formatter.cpp
src/client/formatter/table_formatter.cpp
src/client/formatter/yaml_formatter.cpp
src/daemon/daemon.cpp
src/rpc/multipass.proto
tests/test_output_formatter.cpp

Info prints uid gid map

---

completions/bash/multipass
include/multipass/virtual_machine.h
include/multipass/vm_status_monitor.h
snap/hooks/configure
src/client/client.cpp
src/client/cmd/CMakeLists.txt
src/client/cmd/suspend.cpp
src/client/cmd/suspend.h
src/client/formatter/format_utils.cpp
src/daemon/daemon.cpp
src/daemon/daemon.h
src/daemon/daemon_rpc.cpp
src/daemon/daemon_rpc.h
src/platform/backends/libvirt/libvirt_virtual_machine.cpp
src/platform/backends/libvirt/libvirt_virtual_machine.h
src/platform/backends/qemu/qemu_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.h
src/rpc/multipass.proto
tests/c_mock_defines.cmake
tests/mock_libvirt.cpp
tests/mock_libvirt.h
tests/mock_qemu_system.cpp
tests/mock_status_monitor.h
tests/stub_status_monitor.h
tests/stub_virtual_machine.h
tests/test_cli_client.cpp
tests/test_daemon.cpp
tests/test_format_utils.cpp
tests/test_libvirt_backend.cpp
tests/test_qemu_backend.cpp

Add vm suspend option

---

tests/CMakeLists.txt
tests/mock_qemu_system.cpp
tests/test_qemu_backend.cpp

tests/qemu: Make mock qemu a little more intelligent

---

src/platform/backends/qemu/qemu_virtual_machine_factory.cpp

One less utility to have to ship and confine

Write to /proc/sys instead of using sysctl tool

---

include/multipass/exceptions/exitless_sshprocess_exception.h
src/daemon/daemon.cpp
src/ssh/ssh_process.cpp

Some more logging resolution around mounting, which may be useful to diagnose bugs that are hard to reproduce (e.g. #502)

Add some logging around mounting in daemon.

---

include/multipass/cli/command.h

client: Handle UNAVAILABLE grpc error separately

---

src/daemon/daemon.cpp
src/daemon/daemon.h

Fixes #534 
This can only be merged after #535 !

Fix recovering all on deleted

---

src/daemon/CMakeLists.txt
src/daemon/common_image_host.cpp
src/daemon/common_image_host.h
src/daemon/custom_image_host.cpp
src/daemon/custom_image_host.h
src/daemon/daemon_config.cpp
src/daemon/ubuntu_image_host.cpp
src/daemon/ubuntu_image_host.h
tests/test_custom_image_host.cpp

custom_image_host: Update custom images information when requested

---

src/daemon/ubuntu_image_host.cpp

Fix dangling timer event after image host destruction.

---

include/multipass/exceptions/download_exception.h
src/daemon/common_image_host.cpp
src/daemon/common_image_host.h
src/daemon/custom_image_host.cpp
src/daemon/custom_image_host.h
src/daemon/ubuntu_image_host.cpp
src/daemon/ubuntu_image_host.h
src/network/url_downloader.cpp
tests/CMakeLists.txt
tests/image_host_remote_count.cpp
tests/image_host_remote_count.h
tests/mischievous_url_downloader.cpp
tests/mischievous_url_downloader.h
tests/test_custom_image_host.cpp
tests/test_image_vault.cpp
tests/test_ubuntu_image_host.cpp

Fixes #555 
This PR supersedes #586

Robust host comm

---

.travis.yml

This way we can chain PRs behind one another.

[travis] run on all pull requests

---

src/network/url_downloader.cpp

downloader: Reset timer when readReady is emitted for general downloads

---

src/daemon/daemon.cpp

daemon/suspend: Stop mounts before suspending instance

---

.gitignore

For those of us who build on host

Have git ignore snapcraft build artifacts

---

src/daemon/daemon.cpp
src/daemon/daemon.h
src/platform/backends/qemu/qemu_virtual_machine.cpp
src/utils/utils.cpp

Also allow for concurrent starts on the same instance.

 daemon: Make multiple instance starts completely asynchronous 

---

src/client/cmd/common_cli.cpp

cli: Fix namespacing issues breaking Windows builds

---

completions/bash/multipass
include/multipass/query.h
include/multipass/vm_image_host.h
src/client/cmd/find.cpp
src/daemon/custom_image_host.cpp
src/daemon/custom_image_host.h
src/daemon/daemon.cpp
src/daemon/ubuntu_image_host.cpp
src/daemon/ubuntu_image_host.h
src/rpc/multipass.proto
tests/stub_image_host.h
tests/test_cli_client.cpp
tests/test_custom_image_host.cpp
tests/test_data/releases/multiple_versions_manifest.json
tests/test_image_vault.cpp
tests/test_ubuntu_image_host.cpp

742: launch/find: Allow using and searching for unsupported cloud images r=Saviq a=townsend2010

Release 0.6.1

---

tests/test_output_formatter.cpp

Conditionally disable tests relying on POSIX regex

---

src/client/argparser.cpp
src/client/cmd/help.cpp

Correct error msgs

---

include/multipass/exceptions/create_image_exception.h
src/daemon/daemon.cpp
src/daemon/daemon.h

Catch errors when trying to launch an unsupported cloud image.

daemon: Fix a couple of launching issues due to recent async work

---

src/daemon/daemon.cpp

Handle empty memory specs in old instance DBs

---

include/multipass/exceptions/create_image_exception.h
src/daemon/daemon.cpp

Compiler tweaks

---

include/multipass/virtual_machine.h
src/daemon/daemon.cpp
src/daemon/daemon.h

Use shared pointer when sharing object between threads

---

completions/bash/multipass

Fixes #700, fixes #714, fixes #716

Fix various autocomplete bugs

---

src/platform/backends/qemu/qemu_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.h

Remove unused private attribute

---

tests/test_scp_client.cpp

tests: Use proper temp file for scp pull testing

---

src/daemon/daemon.cpp

Work around for a situation that somehow invalid state was saved to disk.
Fix #773

Detect invalid saved state and correct.

---

src/daemon/daemon.cpp

daemon: Lower logging level of unknown hash exception

---

include/multipass/virtual_machine.h
include/multipass/virtual_machine_description.h
src/daemon/daemon.cpp
src/platform/backends/libvirt/libvirt_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.cpp
tests/stub_virtual_machine.h
tests/test_libvirt_backend.cpp
tests/test_qemu_backend.cpp

I do not see it being used in any VM

Remove unused passing around of key_provider

---

README.md

Minor update to README for MacOS installation

Add Homebrew directions for MacOS

---

src/daemon/daemon.cpp
src/platform/backends/libvirt/libvirt_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.cpp
tests/test_libvirt_backend.cpp
tests/test_qemu_backend.cpp

daemon: Better handle 'unknown' state for certain operations

---

src/daemon/daemon.cpp

find: ensure supported alias before creating image info entry

---

include/multipass/constants.h
include/multipass/exceptions/settings_exceptions.h
include/multipass/platform.h
include/multipass/settings.h
snap-wrappers/bin/launch-multipass
snap-wrappers/bin/launch-multipass-gui
snap-wrappers/bin/launch-multipassd
snap-wrappers/bin/launcher-common.sh
snap/snapcraft.yaml
src/client/cli/cmd/set.cpp
src/daemon/daemon_main.cpp
src/platform/platform_linux.cpp
src/utils/settings.cpp
tests/CMakeLists.txt
tests/fake_handle.h
tests/test_cli_client.cpp
tests/test_libvirt_backend.cpp
tests/test_platform_linux.cpp

Fixes #776.
New attempt, using a central file for daemon settings and requiring admin privileges to set.

Settings daemon driver - take 2

---

snap/snapcraft.yaml

Only build for amd64, armhf and arm64 for now.

[snap] clean up architectures

---

snap/snapcraft.yaml

[snap] fix snap paths

---

src/daemon/default_vm_image_vault.cpp
tests/test_image_vault.cpp

Fix http download crash

---

include/multipass/utils.h
src/platform/CMakeLists.txt
src/platform/platform_linux.cpp
src/utils/settings.cpp
src/utils/utils.cpp
tests/mock_process_factory.cpp
tests/test_cli_client.cpp

To make certain compilers happy.

Portability fixes

---

src/client/cli/cmd/set.cpp

[settings] Fix crash on forgotten sudo

---

src/daemon/CMakeLists.txt
src/daemon/daemon_main.cpp
src/daemon/daemon_monitor_settings.cpp
src/daemon/daemon_monitor_settings.h

To make it available on other platforms (other "daemon mains").

[daemon] Extract settings-file monitoring

---

src/client/cli/cmd/set.cpp

[cli] Improve `set` argument format error

---

src/client/cli/cmd/set.cpp

[cli] Fix wrong error on unsupported driver

---

src/client/cli/cmd/set.cpp

[cli] Accept driver setting when daemon not around

---

src/platform/backends/shared/linux/backend_utils.cpp

backend_utils: Create new process object when changing the qemu-img args

---

.gitmodules

[libssh] workaround chunksize (Fixes #772)

---

src/network/url_downloader.cpp

url_downloader: Use cache if unable to retrieve Last-Modified header

---

include/multipass/sshfs_mount/sftp_server.h
src/ssh/ssh_process.cpp
src/sshfs_mount/sftp_server.cpp
src/sshfs_mount/sshfs_mount.cpp
tests/sftp_server_test_fixture.h
tests/test_sftpserver.cpp
tests/test_sshfsmount.cpp

 sshfs_mount: Recover mounts when sshfs exits for unexpected reasons 

---

src/daemon/daemon.cpp
src/daemon/daemon_config.cpp

daemon: Use 'ubuntu' user instead of 'multipass' user

---

tests/CMakeLists.txt

Also, change the 'BACKEND_TESTS' var name to 'PLATFORM_TESTS' to better identify
what it's for.

tests: Only build snap utils tests on Linux

---

src/platform/backends/qemu/CMakeLists.txt
src/platform/backends/shared/linux/backend_utils.cpp

Also, set absolute path for check_kvm_support.

check_kvm_support: Copy to build's bin when building

---

src/client/cli/cmd/set.cpp
src/utils/utils.cpp
tests/test_cli_client.cpp

Replace driver key literals with constant

---

src/platform/backends/qemu/dnsmasq_process_spec.cpp
src/platform/backends/qemu/dnsmasq_process_spec.h
src/platform/backends/qemu/dnsmasq_server.cpp
src/platform/backends/qemu/dnsmasq_server.h
src/platform/backends/qemu/qemu_virtual_machine_factory.cpp
tests/CMakeLists.txt
tests/mock_dnsmasq_server.cpp
tests/test_dnsmasq_server.cpp

 dnsmasq_server: Better handle when dnsmasq does not run or dies

---

tests/mock_dnsmasq_server.cpp

Fix unused-returns in dnsmasq mock

---

tests/mock_dnsmasq_server.cpp

There is no need to fork *before* returning the detected error condition.
Fixes #998

tests: Simplify the mock dnsmasq server

---

snap/snapcraft.yaml

A build system update only relevant for snaps.

Release 0.8.1

---

src/client/gui/gui_cmd.cpp
src/client/gui/gui_cmd.h

gui: Commonize functions used for petenv and normal instances

---

src/client/gui/gui_cmd.cpp

gui: Detect petenv name change when new petenv doesn't exist

---

.gitmodules
3rd-party/CMakeLists.txt
CMakeLists.txt
data/CMakeLists.txt
data/multipass.gui.autostart.desktop
include/multipass/cli/client_common.h
include/multipass/constants.h
include/multipass/exceptions/autostart_setup_exception.h
include/multipass/exceptions/settings_exceptions.h
include/multipass/platform.h
include/multipass/settings.h
snap-wrappers/bin/client-common.sh
snap-wrappers/bin/launch-multipass
snap-wrappers/bin/launch-multipass-gui
snap/snapcraft.yaml
src/client/cli/client.cpp
src/client/cli/main.cpp
src/client/common/client_common.cpp
src/client/gui/CMakeLists.txt
src/client/gui/client_gui.cpp
src/client/gui/main.cpp
src/platform/platform_linux.cpp
src/utils/settings.cpp
tests/CMakeLists.txt
tests/test_cli_client.cpp
tests/test_platform_linux.cpp

Fixes #967 and addresses (lays the ground for) #944 and #968.

Config gui autostart

---

src/platform/backends/qemu/CMakeLists.txt
src/platform/backends/qemu/iptables_config.cpp
src/platform/backends/qemu/iptables_config.h
src/platform/backends/qemu/qemu_virtual_machine_factory.cpp
src/platform/backends/qemu/qemu_virtual_machine_factory.h
tests/CMakeLists.txt
tests/test_dnsmasq_server.cpp
tests/test_iptables_config.cpp
tests/test_qemu_backend.cpp

Puts the iptables rules handling into its own class and now has some tests.
Fixes #1049, Fixes #1051

Cleanup iptables rules properly

---

src/client/common/client_common.cpp
src/platform/platform_linux.cpp
tests/test_platform_linux.cpp

Fixes #1066 and adds new tests

Fix autostart link crash

---

src/platform/backends/qemu/iptables_config.cpp

iptables: Append the reject rules to the end of the table

---

README.md

[doc] Document how to enable auto-complete

---

include/multipass/exceptions/aborted_download_exception.h
include/multipass/url_downloader.h
src/daemon/default_vm_image_vault.cpp
src/daemon/default_vm_image_vault.h
src/network/url_downloader.cpp
tests/test_image_vault.cpp

image_vault: Allow background image updater downloads to be aborted

---

src/daemon/delayed_shutdown_timer.cpp
tests/test_delayed_shutdown.cpp

delayed_shutdown: Catch thrown exception if ssh exec fails

---

src/platform/update/default_update_prompt.cpp
src/platform/update/new_release_monitor.cpp
tests/test_new_release_monitor.cpp

Proposals for #1210 upon review.

Multipass run json review proposals

---

src/platform/update/CMakeLists.txt
src/platform/update/default_update_prompt.cpp
src/platform/update/default_update_prompt.h
src/platform/update/new_release_monitor.cpp
src/platform/update/new_release_monitor.h
tests/test_new_release_monitor.cpp

---
This will work once https://github.com/canonical-web-and-design/multipass.run/pull/62 lands.

[update] use multipass.run rather than github direct

---

include/multipass/settings.h
src/client/gui/gui_cmd.cpp
src/client/gui/gui_cmd.h
src/utils/settings.cpp

---
Merry Christmas!
Since this is kind of off the cuff, let's see if this looks ok and if we want it.

gui: Add a checkable "autostart on login" option in the About menu

---

include/multipass/constants.h
src/client/cli/cmd/launch.cpp
src/client/cli/cmd/launch.h
src/client/cli/cmd/shell.cpp
src/client/cli/cmd/start.cpp
tests/test_cli_client.cpp

WIP: [primary] Auto-mount home in primary on launch

---

README.md
src/daemon/daemon.cpp

Update remaining github org references

---

src/daemon/daemon.cpp

fix typo: retreive -> retrieve

---

src/platform/backends/qemu/qemu_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.h
tests/qemu/test_qemu_backend.cpp

Bugfix release for Linux (qemu) fixing VM deletion crash (#1266)

Release 1.0.2

---

CMakeLists.txt
src/CMakeLists.txt

#1290 got closed after its base was merged and gh doesn't let me change the base or reopen.

Fix include coverage - based on master

---

src/platform/console/unix_console.cpp

Fixes #1180, Fixes #1217, Fixes #667

Fix exec file redirect and update libssh submodule

---

include/multipass/cli/format_utils.h
include/multipass/format.h

Also, fix a couple of places due to changes in fmt.

fmt: Update submodule to version 6.1.2

---

include/multipass/settings.h
src/utils/settings.cpp

To make settings thread safe. Fixes #1221.

[settings] Lock checked get and set

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

---
The result of this is:
https://github.com/Saviq/multipass/issues/new/choose

Introduce bug template

---

tests/linux/test_apparmored_process.cpp
tests/stub_process_factory.cpp
tests/test_custom_image_host.cpp
tests/test_ubuntu_image_host.cpp

---
Only test code affected after all.
~~Requires #1331 to be merged. Change base to master and delete ghost branch ATP.~~

Sanitize optional derefs

---

src/utils/settings.cpp

Split into separate PR on review request.

[settings] Accept const ref in get helper

---

src/daemon/custom_image_host.cpp
src/daemon/daemon_config.cpp

switched to https for image downloads

---

.travis.yml

---
[Here's a previous build](https://travis-ci.org/github/canonical/multipass/builds/676103727) that had a formatting issue.

[travis] run clang-format on pull requests

---

src/client/cli/cmd/launch.cpp
tests/test_cli_client.cpp

Added check for cloud-init file existence

---

.travis.yml
snap-wrappers/bin/client-common.sh
snap-wrappers/bin/launch-multipassd
snap/local/plugs.json
snap/snapcraft.yaml
src/client/cli/cmd/launch.cpp
src/platform/backends/shared/linux/process_factory.cpp

Requires on #1073 for mounts to function

Convert to strict snap

---

include/multipass/platform.h
src/platform/platform_unix.cpp
src/sshfs_mount/sshfs_server.cpp

[detail] Use multi-thread-capable signal masking

---

include/multipass/ip_address.h

missing include in ip_address.h:24.1

---

src/client/cli/cmd/common_cli.cpp
tests/test_cli_client.cpp

[subcmd] Forward verbosity to subcmds

---

include/multipass/utils.h
src/utils/utils.cpp

Hopefully easier to sift through this way.

[cosmetic] Reorder util functions into small lumps

---

src/platform/backends/libvirt/libvirt_virtual_machine_factory.cpp
src/platform/backends/libvirt/libvirt_virtual_machine_factory.h
src/platform/backends/lxd/lxd_virtual_machine_factory.cpp
src/platform/backends/lxd/lxd_virtual_machine_factory.h
src/platform/backends/qemu/qemu_virtual_machine_factory.cpp
src/platform/backends/qemu/qemu_virtual_machine_factory.h
src/platform/backends/shared/base_virtual_machine_factory.h
tests/CMakeLists.txt
tests/test_base_virtual_machine_factory.cpp

This allows for the various virtual machine factories to use a base class implementation
for defaults to cut down on code reuse.

[virtual_machine_factory] Introduce new base class common implementation

---

src/platform/backends/lxd/lxd_vm_image_vault.cpp

[lxd] Disregard download percent for metadata download portion

---

.travis.yml

https://snapcraft.io/docs/deprecation-notices/dn11

[travis] use `snapcraft upload`, rather than `push`

---

README.md

Also update some areas to include newer information.
---
See the readme here: https://github.com/canonical/multipass/blob/update-readme-to-include-project-status/README.md

[readme] Add new project status section

---

src/sshfs_mount/sshfs_mount.cpp
tests/test_sshfsmount.cpp

[sshfs_mount] Add no compression and cache_timeout options

---

src/daemon/daemon.cpp

CLion was complaining about these.

[detail] Fix a couple of shadowing vars

---

src/client/cli/cmd/launch.cpp
src/daemon/daemon.cpp
src/rpc/multipass.proto

~~https://github.com/canonical/multipass/compare/control-network-interfaces...network-param-handling~~

Move `--network` param parsing to client

---

3rd-party/submodule_info.md

Build mac package with updated hyperkit.

Update hyperkit (note: no longer no-op)

---

src/platform/backends/qemu/dnsmasq_process_spec.cpp
src/platform/backends/qemu/dnsmasq_process_spec.h
src/platform/backends/qemu/dnsmasq_server.cpp
src/platform/backends/qemu/dnsmasq_server.h
tests/mock_process_factory.cpp
tests/mock_process_factory.h
tests/qemu/mock_dnsmasq.cpp
tests/qemu/test_dnsmasq_process_spec.cpp
tests/qemu/test_dnsmasq_server.cpp
tests/stub_process_factory.cpp

Fixes #1741 (and possibly #1475).

Undaemonize dnsmasq

---

src/platform/backends/lxd/lxd_virtual_machine.cpp
tests/lxd/test_lxd_backend.cpp

[lxd] Only return starting state if LXD VM is actually running

---

include/multipass/exceptions/local_socket_connection_exception.h
src/network/network_access_manager.cpp
src/platform/backends/lxd/lxd_virtual_machine.cpp
src/platform/backends/lxd/lxd_virtual_machine_factory.cpp
src/platform/backends/lxd/lxd_vm_image_vault.cpp
tests/linux/test_local_network_access_manager.cpp
tests/lxd/test_lxd_backend.cpp
tests/lxd/test_lxd_image_vault.cpp

Throw new LocalSocketConnectionException type and handle accordingly.

[lxd] Detect connection failures with the LXD socket

---

src/client/cli/cmd/mount.cpp
src/client/cli/cmd/set.cpp
src/network/local_socket_reply.cpp
src/sshfs_mount/sshfs_server.cpp

Make source able to compile on Qt>=5.15.0

---

src/daemon/daemon.cpp

https://github.com/canonical/multipass/pull/1745/files#r505458074

Simplify mac-repetition check in daemon ctor

---

src/platform/backends/lxd/lxd_virtual_machine.cpp
src/platform/backends/lxd/lxd_virtual_machine.h
tests/lxd/test_lxd_backend.cpp

[lxd] Wait on state operations to complete

---

src/daemon/daemon.cpp
src/daemon/daemon.h

A few proposed fixes and simplifications for the public bridging PR.

Control network proposed tweaks

---

include/multipass/platform.h
src/platform/platform_linux.cpp

Proposed updates for the "control" branch, public side.

Control platform update

---

3rd-party/premock/premock.hpp
include/multipass/utils.h
src/daemon/CMakeLists.txt
src/daemon/daemon.cpp
src/utils/utils.cpp
tests/CMakeLists.txt
tests/mock_utils_functions.cpp
tests/mock_utils_functions.h
tests/test_daemon.cpp
tests/test_utils.cpp

This fixes the reliance on the amount of disk space available during tests which can be non-deterministic.

[tests] Add disk size check util and mock

---

src/daemon/daemon.cpp
tests/stub_terminal.h
tests/test_daemon.cpp

Release mac addresses

---

src/client/cli/cmd/CMakeLists.txt
src/client/cli/cmd/networks.h

Couple details

---

include/multipass/process/basic_process.h
include/multipass/process/process.h
src/process/basic_process.cpp
tests/mock_process_factory.h
tests/stub_process_factory.cpp
tests/test_basic_process.cpp

Public side with changes around `Process` for logging purposes, mainly to accommodate incoming changes to PowerShell logging.

Improve ps logging

---

src/platform/backends/lxd/lxd_request.cpp
src/platform/backends/lxd/lxd_request.h
src/platform/backends/lxd/lxd_virtual_machine.cpp
src/platform/backends/lxd/lxd_vm_image_vault.cpp
tests/lxd/test_lxd_backend.cpp

This will bubble up LXD errors and present them to the client and log them.

[lxd] Handle LXD errors better

---

src/platform/backends/lxd/lxd_virtual_machine.cpp
tests/lxd/test_lxd_backend.cpp

This implements `launch --network` with the LXD backend.

Bridging lxd

---

include/multipass/utils.h
include/multipass/virtual_machine.h
src/daemon/daemon.cpp
src/platform/backends/libvirt/libvirt_virtual_machine.cpp
src/platform/backends/libvirt/libvirt_virtual_machine.h
src/platform/backends/lxd/lxd_virtual_machine.cpp
src/platform/backends/lxd/lxd_virtual_machine.h
src/platform/backends/qemu/qemu_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.h
src/platform/backends/shared/CMakeLists.txt
src/platform/backends/shared/base_virtual_machine.cpp
src/platform/backends/shared/base_virtual_machine.h
src/ssh/ssh_session.cpp
src/utils/utils.cpp
tests/mock_virtual_machine.h
tests/stub_virtual_machine.h

In order to fix https://github.com/canonical/multipass/issues/1951, we need to make each backend to handle the request for IP listing.

Move get_all_ipv4() from daemon to VirtualMachine

---

include/multipass/logging/log.h
include/multipass/logging/logger.h
include/multipass/logging/standard_logger.h
src/logging/log.cpp
src/logging/multiplexing_logger.cpp
src/logging/standard_logger.cpp
src/platform/backends/shared/sshfs_server_process_spec.cpp
src/platform/logger/journald_logger.cpp
src/platform/logger/journald_logger.h
src/sshfs_mount/sshfs_server.cpp
tests/mock_logger.cpp
tests/mock_logger.h
tests/test_sshfs_server_process_spec.cpp
tests/test_sshfsmounts.cpp

Logging to the system logger in the sshfs_server process has been broken.

[logging] Fix sshfs_server logging

---

3rd-party/CMakeLists.txt
3rd-party/libssh/CMakeLists.txt
3rd-party/submodule_info.md
src/cert/CMakeLists.txt
src/client/cli/formatter/CMakeLists.txt
src/logging/CMakeLists.txt
src/utils/CMakeLists.txt

---
Better ideas about how to handle libssh welcome :)
Also, grpc is a mess, so not included - @townsend2010 will have a look.

[3rd-party] refresh submodules

---

3rd-party/submodule_info.md

[libssh] Update to include our patch to fix crash on Windows

---

src/ssh/sftp_client.cpp
tests/test_sftp_client.cpp

[sftp] Fix streaming of null-containing data

---

src/daemon/custom_image_host.cpp
src/daemon/daemon_config.cpp

[daemon] switch over to HTTPS for cdimage.u.c

---

src/network/local_socket_reply.cpp
src/network/local_socket_reply.h
src/platform/backends/lxd/lxd_request.cpp
tests/linux/test_local_network_access_manager.cpp

[local_socket_reply] Handle multiple chunked transfers

---

.github/workflows/linux.yml

`base: core20` renamed this key.

[gha] fix label injection

---

src/network/local_socket_reply.cpp
src/network/local_socket_reply.h
tests/linux/test_local_network_access_manager.cpp

This didn't fix the problem in the end, and introduced another.
Kept this commit, though: 43748d8fd3a28e71c641888899aa59a4057bca87

[lxd] revert chunked reads

---

src/network/local_socket_reply.cpp
src/network/local_socket_reply.h
tests/linux/local_socket_server_test_fixture.h
tests/linux/test_local_network_access_manager.cpp

We've only been reading once, when sometimes the socket could be buffered.

[lxd] read all data from the socket

---

3rd-party/CMakeLists.txt
include/multipass/file_ops.h
include/multipass/platform.h
include/multipass/singleton.h
include/multipass/standard_paths.h
include/multipass/utils.h
src/utils/file_ops.cpp
src/utils/standard_paths.cpp
src/utils/utils.cpp
tests/linux/test_platform_linux.cpp
tests/mock_singleton_helpers.h
tests/test_daemon.cpp

This is possible with C++17 and avoids undefined behavior.

Require noexcept in sg

---

include/multipass/snap_utils.h
snap/snapcraft.yaml
src/platform/backends/lxd/lxd_virtual_machine_factory.cpp
src/platform/platform_linux.cpp
src/utils/snap_utils.cpp
tests/file_operations.cpp
tests/file_operations.h
tests/linux/test_platform_linux.cpp
tests/linux/test_snap_utils.cpp
tests/lxd/mock_lxd_server_responses.h
tests/lxd/test_lxd_backend.cpp

List ethernet devices in `multipass networks` when using the LXD backend. Part of the bridge creation story.

List ethernets

---

src/platform/backends/shared/linux/CMakeLists.txt
src/platform/backends/shared/linux/backend_utils.cpp
src/platform/backends/shared/linux/backend_utils.h
src/platform/backends/shared/linux/dbus_wrappers.h
tests/linux/test_backend_utils.cpp

This contains the procedure to create bridges on Linux. It is not plugged in yet, but can be exercised [like this](https://github.com/canonical/multipass/pull/2022#issuecomment-820648151).

Bridge creation

---

src/utils/utils.cpp

[utils] Pass timeout when getting ssh_hostname() in wait_until_ssh_up()

---

src/daemon/daemon.cpp
tests/test_daemon.cpp

[daemon] Make sure there is a path before checking if it exists

---

src/network/url_downloader.cpp
tests/mock_network.h
tests/test_url_downloader.cpp

Also, some refactoring of getting HTTP headers and waiting for the reply.
Fixes #2104

[url_downloader] Add timeout when retrieving HTTP headers

---

include/multipass/timer.h
src/utils/timer.cpp
tests/test_timer.cpp

[timer] Remove timer state getter

---

src/client/gui/gui_cmd.cpp

[gui] Update copyright in "About" widget

---

src/daemon/daemon.cpp

[daemon] Fix file and http based launching regression

---

src/platform/backends/qemu/qemu_virtual_machine.cpp
tests/qemu/test_qemu_backend.cpp

[backend/qemu] Fix qemu suspend regression

---

src/platform/backends/lxd/lxd_virtual_machine.cpp
src/platform/backends/lxd/lxd_virtual_machine.h
src/platform/backends/lxd/lxd_virtual_machine_factory.cpp
src/platform/backends/lxd/lxd_virtual_machine_factory.h
tests/lxd/test_lxd_backend.cpp

This will use the default storage pool if it exists. Otherwise, it will use a multipass storage pool and create it if it doesn't exist.

[LXD] Handle storage pools better

---

src/platform/backends/qemu/firewall_config.cpp
src/platform/backends/qemu/qemu_virtual_machine_factory.cpp
tests/qemu/test_firewall_config.cpp

[firewall] Fix detection of nftables support in kernel

---

src/daemon/daemon.cpp

[daemon] Fix memory reported in older ubuntu vms

---

src/daemon/daemon.cpp

Just a couple of small improvements I stumbled upon while browsing code.

Minor validate launch tweaks

---

include/multipass/timer.h
src/utils/timer.cpp
tests/test_timer.cpp

- Use millisecond resolution
- Adapt and improve tests

[timer] Fix failing Timer test in CI

---

src/client/cli/cmd/launch.cpp
tests/test_cli_client.cpp

Fixes https://github.com/canonical/multipass/issues/2224.

Parse memory, disk parameters in the client.

---

src/platform/backends/lxd/lxd_virtual_machine.h

This appears to be a leftover.

[lxd] Drop unimplemented method

---

src/client/cli/cmd/set.cpp

Just a cosmetic tweak that didn't make sense to lump in another PR.

[cosmetic] Fix comment format

---

include/multipass/id_map.h
include/multipass/id_mappings.h
include/multipass/id_relationship_list.h
include/multipass/sshfs_mount/sftp_server.h
include/multipass/sshfs_mount/sshfs_mount.h
include/multipass/sshfs_mount/sshfs_mounts.h
include/multipass/sshfs_server_config.h
src/client/cli/cmd/mount.cpp
src/client/cli/formatter/json_formatter.cpp
src/client/cli/formatter/table_formatter.cpp
src/client/cli/formatter/yaml_formatter.cpp
src/daemon/daemon.cpp
src/daemon/daemon.h
src/platform/backends/shared/sshfs_server_process_spec.cpp
src/rpc/multipass.proto
src/sshfs_mount/sftp_server.cpp
src/sshfs_mount/sshfs_mount.cpp
src/sshfs_mount/sshfs_mounts.cpp
src/sshfs_mount/sshfs_server.cpp
tests/test_cli_client.cpp
tests/test_daemon.cpp
tests/test_output_formatter.cpp
tests/test_sftpserver.cpp
tests/test_sshfsmount.cpp
tests/test_sshfsmounts.cpp

Fixes https://github.com/canonical/multipass/issues/1718.

Fix `chown` in the host if uid/gid is reverse mapped

---

src/client/cli/cmd/animated_spinner.cpp
src/client/cli/cmd/exec.cpp
tests/test_cli_client.cpp

Start the VM if needed on `exec`

---

snap/snapcraft.yaml

[snap] extend `stop-timeout` to 5 minutes

---

src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp
src/platform/backends/qemu/qemu_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.h

[qemu] Fix starting from resume regression

---

src/daemon/default_vm_image_vault.cpp

[detail] Fix unused-variable warning

---

src/sshfs_mount/sftp_server.cpp
tests/test_sftpserver.cpp

[sftpserver] Removing reverse mapping handling when creating symlink

---

include/multipass/constants.h
src/cert/client_cert_store.cpp
src/client/cli/client.cpp
src/client/cli/cmd/CMakeLists.txt
src/client/cli/cmd/authenticate.cpp
src/client/cli/cmd/authenticate.h
src/daemon/daemon_rpc.cpp
tests/test_cli_client.cpp
tests/test_client_cert_store.cpp
tests/unix/test_daemon_rpc.cpp

Also has an "auth" alias to shorten the typing

[client/cli] Rename register command to authenticate

---

src/simplestreams/simple_streams_manifest.cpp
tests/test_simple_streams_manifest.cpp

[lxd] skip -kvm images in streams

---

src/client/cli/cmd/launch.cpp
src/client/cli/cmd/launch.h
tests/test_cli_client.cpp

Port auto-mount code in launch to settings handlers

---

src/client/cli/cmd/launch.cpp

[cli] Don't attempt automount with disabled petenv

---

.github/workflows/integration.yml

To reduce diff between classic and release integration tests.
Also allow running longer due to potential queueing.

[ci] abstract _install and a couple tweaks

---

src/platform/backends/lxd/lxd_vm_image_vault.cpp
tests/lxd/test_lxd_image_vault.cpp

[image_vault/lxd] Fix downloading image with type change

---

src/daemon/instance_settings_handler.cpp
tests/test_instance_settings_handler.cpp

[settings] Allow lowering cpu and memory instance settings

---

.github/workflows/linux.yml

Ref. samuelmeuli/action-snapcraft#36

[ci] fix Snapcraft token handling

---

completions/bash/multipass

Added bash completions for the `launch --mount` option.

[cli][launch] add bash completions for mount option

---

src/daemon/daemon.cpp
src/daemon/daemon.h
src/platform/backends/libvirt/libvirt_virtual_machine.cpp
src/platform/backends/lxd/lxd_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.cpp
tests/CMakeLists.txt
tests/daemon_test_fixture.h
tests/lxd/test_lxd_backend.cpp
tests/qemu/test_qemu_backend.cpp
tests/test_daemon.cpp
tests/test_daemon_start.cpp

[daemon] Handle instance state logic for determining when to start

---

src/daemon/daemon.cpp
src/daemon/daemon.h
tests/test_daemon_start.cpp

[daemon] Move starting instances back to main thread

---

src/client/cli/cmd/exec.cpp
tests/test_cli_client.cpp

Fix execution of `sudo` through `exec` command

---

snap/snapcraft.yaml
src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp
src/platform/backends/qemu/qemu_vm_process_spec.cpp
tests/qemu/linux/test_qemu_platform_detail.cpp
tests/qemu/test_qemu_vm_process_spec.cpp

Make QEMU boot using UEFI on Linux
fix #1477

Linux qemu uefi

---

src/platform/backends/shared/base_virtual_machine.cpp
tests/test_base_virtual_machine.cpp

Fix IP listing in jammy instances

---

tests/test_url_downloader.cpp

There is a race that has been showing up on the Windows build.

[tests] Fix URLDownloader tests

---

src/daemon/custom_image_host.cpp
src/simplestreams/simple_streams_manifest.cpp
tests/test_custom_image_host.cpp

using the UEFI images for the releases that have them and adding support for core 20 and core 22 images
Fixes #2588

Add core 20/22 images and use UEFI images

---

src/daemon/daemon.cpp
src/platform/backends/qemu/qemu_mount_handler.cpp
tests/test_daemon_mount.cpp
tests/test_daemon_umount.cpp

[mounts] Fix mount handling when suspending

---

src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp
tests/qemu/linux/test_qemu_platform_detail.cpp

[qemu] Account for BIOS only Xenial instances

---

tests/daemon_test_fixture.cpp
tests/daemon_test_fixture.h

This should help some with the compile time and memory footprint needed to compile the unit tests.

[tests] Use explicit template instantiation for templated fixture functions

---

include/multipass/exceptions/invalid_memory_size_exception.h
src/client/cli/cmd/launch.cpp
src/utils/memory_size.cpp
tests/test_memory_size.cpp

Adds the ability to input decimal amounts for memory specification.
Fixes #2677

Accept decimal memory values

---

include/multipass/utils.h
src/daemon/daemon.cpp
src/platform/backends/qemu/qemu_mount_handler.cpp
src/platform/backends/qemu/qemu_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.h
src/platform/backends/qemu/qemu_vm_process_spec.cpp
src/utils/utils.cpp
tests/qemu/test_qemu_backend.cpp
tests/qemu/test_qemu_vm_process_spec.cpp

Handle Qemu native mount when resuming from suspended state

---

README.md

I've been stuck with this issue numerous times now. It needs to be stated clearly as an FYI.
Signed-off-by: Beau <beau.williams@icloud.com>

fix: add note for Mac OS users affected by #2387

---

include/multipass/timer.h
src/utils/timer.cpp
tests/test_timer.cpp

[timer] Handle spurious wake ups

---

tests/daemon_test_fixture.cpp

[tests] Wait on Daemon slot thread when it quits

---

tests/test_memory_size.cpp

Avoids unsupported number representations, e.g. with a comma separating integers and decimal parts.

[tests] Fix MemorySize tests depending on locale

---

.github/workflows/linux.yml
snap/snapcraft.yaml

[snap] update base to core22

---

include/multipass/cli/client_common.h
include/multipass/cli/client_platform.h
src/client/cli/cmd/common_callbacks.h
src/client/cli/cmd/mount.cpp
src/client/cli/cmd/restart.cpp
src/client/cli/cmd/start.cpp
src/client/cli/cmd/stop.cpp
src/client/cli/cmd/suspend.cpp
src/platform/client/client_platform.cpp
tests/CMakeLists.txt
tests/mock_client_platform.h
tests/test_common_callbacks.cpp

Fixes #2888 and #2889, extracts the repeated `streaming_callback`s in question, and adds tests.

Fix spinner callbacks

---

include/multipass/client_cert_store.h
include/multipass/platform.h
include/multipass/utils.h
src/cert/client_cert_store.cpp
src/client/common/client_common.cpp
src/daemon/daemon_config.cpp
src/daemon/default_vm_image_vault.cpp
src/platform/backends/libvirt/libvirt_virtual_machine_factory.cpp
src/platform/backends/lxd/lxd_virtual_machine_factory.cpp
src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp
src/platform/platform_unix.cpp
src/ssh/openssh_key_provider.cpp
src/utils/utils.cpp
tests/mock_utils.h
tests/test_client_cert_store.cpp
tests/test_client_common.cpp
tests/test_daemon.cpp
tests/test_image_vault.cpp
tests/test_ssh_key_provider.cpp
tests/test_ssl_cert_provider.cpp
tests/test_utils.cpp

Windows handles permissions differently than other OS's so we need to add the ability to have a platform specific veersion.
Private side PR [here](https://github.com/canonical/multipass-private/pull/494)

Add platform permission func

---

include/multipass/mount_handler.h
src/platform/backends/qemu/qemu_virtual_machine.h
tests/CMakeLists.txt
tests/mock_mount_handler.h
tests/mock_virtual_machine.h
tests/qemu/CMakeLists.txt
tests/qemu/test_qemu_mount_handler.cpp
tests/qemu/test_qemu_vm_process_spec.cpp
tests/stub_mount_handler.h
tests/stub_virtual_machine.h
tests/test_daemon_mount.cpp
tests/test_daemon_start.cpp
tests/test_daemon_umount.cpp
tests/test_sshfs_mount_handler.cpp

Follow-up to #2835 to add unit tests for the new mount handlers implementations.

Mount handler tests

---

src/client/cli/cmd/remote_settings_handler.cpp
src/daemon/CMakeLists.txt
src/daemon/daemon.cpp
src/rpc/multipass.proto
tests/test_daemon.cpp
tests/test_daemon_find.cpp
tests/test_daemon_launch.cpp
tests/test_daemon_start.cpp

Complete implementation for Hyperkit migration. Fixes #2326.
I am closing the intermediate PRs now, but leaving the branches around, in case anyone prefers to review review in steps.

Hyperkit migration

---

src/client/cli/cmd/launch.cpp

Fix warning message

---

.github/workflows/integration.yml

This between setting passphrase and authenticating to allow daemon to restart.

[ci/macos] Add 20 second sleep

---

snap/local/patches/define-ubuntu-machine-types.patch
snap/snapcraft.yaml

Fixes #2923
---
Private counterpart at https://github.com/canonical/multipass-private/pull/509

[third_party] Update to use Qemu 7.2.0 plus Multipass specific changes

---

3rd-party/submodule_info.md

[3rd-party/libssh] Update to version 0.10.4 plus patches

---

src/rpc/multipass.proto

Just noticed this tiny thing. I am not sure if there is an impact, but may as well fix it.

[rpc] Fix index in KeysRequest

---

src/daemon/daemon.cpp

fixed the false time error when user specifies the new instance name

---

src/rpc/multipass.proto

https://github.com/canonical/multipass/projects/16#card-88442218

[rpc] add num snaphots

---

README.md

Needed a break and found this easy change.
---
Fixes #2695 and #1851

[readme] Remove aspirations of building for anything but Linux

---

src/daemon/daemon.cpp
tests/daemon_test_fixture.cpp
tests/test_daemon.cpp

[daemon] include deleted instances in `info --all` reply

---

3rd-party/submodule_info.md

[3rd-party] Update POCO to version 1.12.4

---

src/client/cli/client.cpp
src/client/cli/cmd/CMakeLists.txt
src/client/cli/cmd/restore.cpp
src/client/cli/cmd/restore.h
src/daemon/daemon.cpp
src/daemon/daemon.h
src/daemon/daemon_rpc.cpp
src/daemon/daemon_rpc.h
src/rpc/multipass.proto
tests/mock_client_rpc.h
tests/test_cli_client.cpp

Based off on #2972, just adding some more tests

[tests] Snapshot cli tests

---

include/multipass/exceptions/snapshot_name_taken.h
include/multipass/memory_size.h
include/multipass/snapshot.h
include/multipass/virtual_machine.h
src/daemon/daemon.cpp
src/platform/backends/shared/CMakeLists.txt
src/platform/backends/shared/base_snapshot.cpp
src/platform/backends/shared/base_snapshot.h
src/platform/backends/shared/base_virtual_machine.cpp
src/platform/backends/shared/base_virtual_machine.h
src/utils/memory_size.cpp
tests/mock_virtual_machine.h
tests/stub_snapshot.h
tests/stub_virtual_machine.h

Adding generic (not backend-specific) snapshot infrastructure.

Hollow snapshots

---

include/multipass/cli/client_common.h
include/multipass/cli/client_platform.h
include/multipass/platform.h
include/multipass/utils.h
src/cert/ssl_cert_provider.cpp
src/client/cli/cmd/common_callbacks.h
src/platform/client/client_platform.cpp
src/platform/platform_unix.cpp
src/rpc/multipass.proto
src/utils/utils.cpp
tests/mock_client_platform.h
tests/test_client_common.cpp
tests/test_common_callbacks.cpp
tests/test_utils.cpp

Refactor some common code that is needed on the private side.
---
public side of [pr510](https://github.com/canonical/multipass-private/pull/510)

Store smb creds

---

src/platform/backends/qemu/qemu_virtual_machine.cpp

[backend/qemu] Increase shutdown/suspend timeout to 5 minutes

---

src/daemon/custom_image_host.cpp
tests/test_custom_image_host.cpp

[image_host/custom] Point snapcraft:devel to lunar buildd daily

---

include/multipass/file_ops.h
include/multipass/virtual_machine.h
src/daemon/daemon.cpp
src/platform/backends/shared/base_snapshot.cpp
src/platform/backends/shared/base_snapshot.h
src/platform/backends/shared/base_virtual_machine.cpp
src/platform/backends/shared/base_virtual_machine.h
src/utils/file_ops.cpp
tests/mock_virtual_machine.h
tests/stub_virtual_machine.h

Implement loading of snapshots that were previously persisted by Multipass.

Implement generic snapshot loading from disk

---

3rd-party/CMakeLists.txt
src/client/cli/cmd/alias.cpp
src/client/cli/cmd/exec.cpp
src/client/cli/cmd/info.cpp
src/client/cli/formatter/csv_formatter.cpp
src/client/cli/formatter/json_formatter.cpp
src/client/cli/formatter/table_formatter.cpp
src/client/cli/formatter/yaml_formatter.cpp
src/daemon/daemon.cpp
src/rpc/multipass.proto
tests/test_cli_client.cpp
tests/test_daemon.cpp
tests/test_output_formatter.cpp

Something to build the different `multipass info` queries off of.

[building and passing tests] Snapshots info RPC

---

src/daemon/daemon.cpp
src/daemon/daemon.h
src/rpc/multipass.proto
tests/stub_virtual_machine.h
tests/test_daemon.cpp

Refactor how we select instances given instance name args, as well as how we react when there is a problem with those args.

[daemon] Refactor instance selection

---

src/utils/utils.cpp
tests/test_cli_client.cpp
tests/test_utils.cpp

Improve argument quoting

---

include/multipass/top_catch_all.h

- [doc] Delete wrong comment in top-catch helper
- [doc] Clarify exception behavior in top-catch-all

[doc] Fix docs regarding exceptions in top_catch_all

---

src/platform/backends/shared/base_virtual_machine.cpp
src/platform/backends/shared/base_virtual_machine.h

Needs #3096 to be merged first.

[snapshots] Refactor snapshot rollbacks in BaseVM

---

include/multipass/snapshot.h
include/multipass/virtual_machine.h
src/daemon/daemon.cpp
src/platform/backends/qemu/qemu_snapshot.cpp
src/platform/backends/qemu/qemu_snapshot.h
src/platform/backends/shared/base_snapshot.h
src/platform/backends/shared/base_virtual_machine.cpp
src/platform/backends/shared/base_virtual_machine.h
tests/mock_virtual_machine.h
tests/stub_snapshot.h
tests/stub_virtual_machine.h

Needs #3085 to be merged first.

[snapshots] Implement generic part of snapshot restoring

---

src/daemon/daemon.cpp

[daemon] Fix mapping of instance/snapshot args

---

src/client/cli/cmd/launch.cpp

Fix relative paths in `launch`

---

src/client/desktop_gui/lib/ffi.dart
src/client/desktop_gui/macos/Runner.xcodeproj/project.pbxproj
src/client/desktop_gui/pubspec.lock
src/client/desktop_gui/pubspec.yaml

This PR add the necessary glue to be able to call C functions through FFI

[gui] call c code using dart ffi

---

include/multipass/snapshot.h
include/multipass/virtual_machine.h
src/daemon/daemon.cpp
src/daemon/daemon.h
src/platform/backends/shared/base_snapshot.cpp
src/platform/backends/shared/base_snapshot.h
src/platform/backends/shared/base_virtual_machine.cpp
src/platform/backends/shared/base_virtual_machine.h
tests/mock_virtual_machine.h
tests/stub_snapshot.h
tests/stub_virtual_machine.h

Rebased with changes from #3136 to make testing easier

[snapshots] populate snapshot details

---

include/multipass/utils.h
src/cert/client_cert_store.cpp
src/ssh/openssh_key_provider.cpp
tests/test_client_cert_store.cpp
tests/test_daemon.cpp
tests/test_ssh_key_provider.cpp

Public side of [multipass-private/pull/547](https://github.com/canonical/multipass-private/pull/547)

Set admin as file owner

---

include/multipass/virtual_machine.h
src/daemon/daemon.cpp
src/daemon/daemon.h
src/daemon/instance_settings_handler.cpp
src/platform/backends/lxd/lxd_virtual_machine.cpp
src/platform/backends/lxd/lxd_virtual_machine.h
src/platform/backends/shared/base_virtual_machine.h
tests/lxd/test_lxd_backend.cpp
tests/mock_virtual_machine.h
tests/stub_virtual_machine.h
tests/test_base_virtual_machine.cpp
tests/test_daemon.cpp
tests/test_daemon_start.cpp
tests/test_instance_settings_handler.cpp

This PR adds the necessary bits to implement adding network interfaces on LXD backend.

Add network interfaces on LXD backend

---

completions/bash/multipass

Replace obsolete regex filtering with proper filtering of the title line in CSV output.

[bash] Slight cleanup of completions

---

.github/workflows/snaps.yml

https://bugs.launchpad.net/lazr.restfulclient/+bug/2041407

ci: fix python version

---

include/multipass/vm_specs.h

[vmspecs] Remove unneeded namespace qualification

Just a tiny tweak

---

3rd-party/libssh/CMakeLists.txt
3rd-party/submodule_info.md

[3rd-party] Update libssh to 0.10.5

---

src/daemon/daemon.cpp
src/daemon/snapshot_settings_handler.cpp
src/daemon/snapshot_settings_handler.h

Stick with the approach of making properties of deleted instances readable but not writable.

Tweak handling of snapshots of deleted instances

---

src/sshfs_mount/sftp_server.cpp

[sftp] set files without a mapping as nobody:nogroup

---

src/platform/backends/qemu/qemu_virtual_machine.cpp
src/platform/backends/qemu/qemu_virtual_machine.h
src/ssh/openssh_key_provider.cpp

[qemu] sync clock with host after resuming from suspension

---

include/multipass/virtual_machine_factory.h
src/daemon/daemon.cpp
src/platform/backends/lxd/lxd_virtual_machine_factory.h
src/platform/backends/shared/base_virtual_machine_factory.h
tests/CMakeLists.txt
tests/daemon_test_fixture.cpp
tests/lxd/test_lxd_backend.cpp
tests/mock_virtual_machine_factory.h
tests/stub_virtual_machine_factory.h
tests/test_base_virtual_machine_factory.cpp
tests/test_daemon_suspend.cpp

[lxd] check for suspend support before attempting operation

---

include/multipass/vm_mount.h
src/platform/backends/shared/base_snapshot.cpp
tests/CMakeLists.txt
tests/daemon_test_fixture.cpp
tests/daemon_test_fixture.h
tests/mock_daemon.h
tests/mock_snapshot.h
tests/qemu/CMakeLists.txt
tests/qemu/test_qemu_backend.cpp
tests/qemu/test_qemu_snapshot.cpp
tests/test_base_snapshot.cpp
tests/test_base_virtual_machine.cpp
tests/test_common_callbacks.cpp
tests/test_daemon.cpp
tests/test_daemon_snapshot.cpp
tests/test_daemon_snapshot_restore.cpp
tests/test_json_utils.cpp
tests/test_mount_handler.cpp
tests/test_qemu_snapshot.cpp
tests/test_utils.cpp
tests/test_vm_mount.cpp

New PR to see if it clears some codecov confusion.

[Snapshots] Unit tests (take 2)

---

src/platform/backends/qemu/qemu_virtual_machine.cpp

[qemu] catch possible errors when syncing hw clock

---

include/multipass/cloud_init_iso.h
include/multipass/file_ops.h
src/iso/cloud_Init_Iso_read_me.md
src/iso/cloud_init_iso.cpp
src/utils/file_ops.cpp
tests/linux/test_platform_linux.cpp
tests/mock_file_ops.h
tests/test_cloud_init_iso.cpp

Added `CloudInitIso::read_from` function which is the missing piece of the CloudInitIso class. 
Please start with cloud_Init_Iso_read_me.md file to get a grasp of the preliminaries.

Added read cloud-init-config.iso file function

---

renovate.json

[github] Add Renovate configuration

---

src/platform/backends/shared/base_virtual_machine.cpp

[vm] Fetch extra IPs also on Delayed Shutdown

---

src/daemon/cli.cpp

[cli] Make the --verbosity option case insensitive

---

src/platform/backends/lxd/lxd_virtual_machine.cpp

[lxd] Fix instances not reported as starting

---

src/daemon/runtime_instance_info_helper.cpp

[daemon] fix the multipass info after multipass launch failure

---

src/platform/backends/shared/base_virtual_machine.cpp

The `ssh_exec` method used to acquire the `state` mutex for its entire duration, which might've led to a deadlock if the method entered the `renew_ssh_session` flow, since that also tries to get the mutex. Now `ssh_exec` locks for more discrete periods of time.
This is not a final solution to the underlying problem. But it does seems to bring back the behavior observed so far. An `info` call might still block while a VM is launching, but at least it does not deadlock the entire daemon, and only gives an error and can be retried.

LXD deadlock quickfix

---

src/daemon/daemon.cpp

Copied https://github.com/canonical/multipass/pull/3670 to the original repo in order to pass all the CI builds

Unify unknown state err msg

---

src/client/cli/cmd/launch.cpp
tests/test_cli_client.cpp

Improve cloud-init error messages

---

include/multipass/dart_ffi.h
include/multipass/memory_size.h
src/client/gui/ffi/dart_ffi.cpp
src/client/gui/lib/catalogue/launch_form.dart
src/client/gui/lib/dropdown.dart
src/client/gui/lib/extensions.dart
src/client/gui/lib/ffi.dart
src/client/gui/lib/grpc_client.dart
src/client/gui/lib/main.dart
src/client/gui/lib/settings/hotkey.dart
src/client/gui/lib/settings/virtualization_settings.dart
src/client/gui/lib/vm_details/cpus_slider.dart
src/client/gui/lib/vm_details/disk_slider.dart
src/client/gui/lib/vm_details/mapping_slider.dart
src/client/gui/lib/vm_details/memory_slider.dart
src/client/gui/lib/vm_details/ram_slider.dart
src/client/gui/lib/vm_details/spec_input.dart
src/client/gui/lib/vm_details/vm_details_resources.dart
src/client/gui/pubspec.lock
src/client/gui/pubspec.yaml
src/daemon/daemon.cpp
src/daemon/daemon.h
src/daemon/daemon_rpc.cpp
src/daemon/daemon_rpc.h
src/rpc/multipass.proto
src/utils/memory_size.cpp
tests/mock_client_rpc.h
tests/mock_daemon.h

This PR introduces a new way to input VM specs using sliders.
See https://warthogs.atlassian.net/browse/MULTI-959 for reference.

Vm resource sliders

---

src/client/gui/pubspec.yaml

[gui] set version to 1.14.1

---

README.md

[readme] Need VCPKG_FORCE_SYSTEM_BINARIES set on non-x64; add note (#3741)

---

src/client/gui/lib/vm_details/vm_details_general.dart

Scale VMStats according to the text scale in use. Also extract a magic number. Thanks for the tip @andrei-toterman !
[MULTI-1571]
[MULTI-1571]: https://warthogs.atlassian.net/browse/MULTI-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Scale VMStats in GUI details according to platform 

---

src/platform/platform_linux.cpp
tests/linux/test_platform_linux.cpp

Clone (+ rebase) of #3740 in our repo, to run CI.
MULTI-1658

Clone of #3740: "Fix multipass_tests target on Ubuntu ARM64 (#3739)"

---

src/client/gui/lib/settings/general_settings.dart

Just making the label prettier for the setting regarding what to do when closing the GUI.

[gui] update settings label for closing app behavior

---

3rd-party/xz-decoder/CMakeLists.txt

Clone of @ntorresalberto's https://github.com/canonical/multipass/pull/3904, to get it through CI.

Fix #3898 by adding -fPIC to xz-embedded [clone]

---

docs/conf.py

the site has been down for one day.

[docs] add straightrunning to linkcheck_ignore

---

.github/workflows/automatic-doc-checks.yml

[ci] Skip docs checks on unrelated changes

---

.github/workflows/linux.yml

Reverts canonical/multipass#3993

Revert "[ci] Skip Linux CI on unrelated changes"

---

renovate.json5

Unless @andrei-toterman wants to continue doing reviews for Multipass 😉

[renovate] Remove Andrei from renovatebot

---

.github/workflows/linux.yml

Jobs started running out of disk space.

[ci] Free disk space on Linux builds

---

.github/workflows/windows-macos.yml

[workflows/windows-macos] sprinkle a bunch of !cancelled() to jobs

---

tests/test_sftp_client.cpp

This pull request refactors the `SFTPClient` tests by removing the dependency on `Poco::TeeStream` and replacing it with standard C++ streams. This is the only non-blueprint related usage of POCO, in preparation for removing the already-deprecated blueprints and therefore dependency on POCO entirely in the future.
* Removed the `#include <Poco/TeeStream.h>` directive from `tests/test_sftp_client.cpp` as `Poco::TeeStream` is no longer used.
* In `TEST_F(SFTPClient, pull_file_success)`, replaced `Poco::TeeOutputStream` with a standard `std::ostream` using `test_file.rdbuf()` for mocking file writing.
* In `TEST_F(SFTPClient, pull_dir_success_regular)`, similarly replaced `Poco::TeeOutputStream` with `std::ostream` for mocking file writing.

Remove Poco from sftp client tests

---

.github/workflows/windows-macos.yml

[workflows/windows-macos] introduce gh macos runners

---

src/client/gui/lib/main.dart
src/client/gui/lib/tray_menu.dart

Clone of #4068. See original for details.
*Authored by [Artem-OSSRevival](https://github.com/Artem-OSSRevival).*

Honour the close setting when quitting from the tray (clone of #4068)

---

src/client/gui/lib/before_quit_dialog.dart
src/client/gui/lib/close_terminal_dialog.dart
src/client/gui/lib/confirmation_dialog.dart
src/client/gui/lib/main.dart

resolves #4102 
This pull request refactors the confirmation dialogs in the GUI to improve user experience and consistency. Key changes include replacing custom `Switch` widgets with `Checkbox` widgets, updating dialog layouts, and swapping the button placements.
<br>

[gui] Refactor confirmation dialogs

---

.github/actions/lint/action.yml
src/client/gui/lib/catalogue/catalogue.dart
src/client/gui/lib/catalogue/launch_form.dart
src/client/gui/lib/extensions.dart
src/client/gui/lib/ffi.dart
src/client/gui/lib/grpc_client.dart
src/client/gui/lib/logger.dart
src/client/gui/lib/main.dart
src/client/gui/lib/notifications/notification_entries.dart
src/client/gui/lib/notifications/notifications_list.dart
src/client/gui/lib/notifications/notifications_provider.dart
src/client/gui/lib/platform/linux.dart
src/client/gui/lib/platform/macos.dart
src/client/gui/lib/platform/windows.dart
src/client/gui/lib/providers.dart
src/client/gui/lib/settings/autostart_notifiers.dart
src/client/gui/lib/settings/hotkey.dart
src/client/gui/lib/settings/usage_settings.dart
src/client/gui/lib/settings/virtualization_settings.dart
src/client/gui/lib/sidebar.dart
src/client/gui/lib/tray_menu.dart
src/client/gui/lib/vm_action.dart
src/client/gui/lib/vm_details/disk_slider.dart
src/client/gui/lib/vm_details/ram_slider.dart
src/client/gui/lib/vm_details/terminal.dart
src/client/gui/lib/vm_details/vm_details.dart
src/client/gui/lib/vm_details/vm_details_bridge.dart
src/client/gui/lib/vm_details/vm_details_resources.dart
src/client/gui/lib/vm_table/vms.dart
src/client/gui/lib/window_size.dart

Fetch Flutter deps before running the formatter, as it can influence the outcome.
MULTI-2102

[ci/lint] add `flutter pub get` before `dart format`

---

.github/actions/whitespace/action.yml
.github/workflows/lint.yml

Drop leading `set` calls for options that are now default in bash steps.
See https://is.gd/4HQTkt.

[ci] Remove redundant shell setup

---

.github/workflows/windows-macos.yml
3rd-party/qemu/CMakeLists.txt

Fixes #3851 
Fixes #4111 
---
MULTI-1716

[3rd-party] Upgrade QEMU to v10.0.3

---

renovate.json5

Tweak Renovate's commit message in accordance with our guidelines.

[deps] Tweak Renovate's commit message

---

docs/how-to-guides/manage-instances/index.md

I just created an update on internal cross-references to use recommended MyST targets

Updated internal cross-references to use recommended MyST targets
