canonical/multipass

src/ssh/ssh_client.cpp
Prevent hangs by checking for ssh channel EOF before blocking
waiting for the next event which won't occur. Fixes #16
=> [ssh client] Check for EOF before event poll

snap/snapcraft.yaml, tests/travis-Coverage.patch
Since we're in a git checkout already, using `source-type: git` only
really hurts us, because it pulls all the submodules from the network
instead locally, and that's 500MB of git repos at the moment...
=> snap: use plain source-type

snap/snapcraft.yaml, src/network/ip_address_pool.cpp, src/platform/backends/qemu/CMakeLists.txt, src/platform/backends/qemu/dnsmasq_server.cpp, src/platform/backends/qemu/dnsmasq_server.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.h
- This also supports VM's that have already been created with the old static IP method.
=> qemu: Use dnsmasq for DNS and DHCP of VM's. Fixes #1

include/multipass/ip_address_pool.h, include/multipass/optional.h, src/network/ip_address_pool.cpp, src/platform/backends/qemu/dnsmasq_server.cpp, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h
When c++17 support is enabled, use std::optional, instead of
std::experimental::optional.
=> Use std::optional if c++17 is enabled.

completions/bash/multipass
This changes the calls to "grep" to use the unaliased form. "\grep"
This helps me because I tend to "alias grep='grep --color -nI'" which ends up putting the line numbers in front of the instance list. By using '\grep' it avoids my aliases.
=> ignore shell aliases when determining instances for autocomplete

snap/bin/launch-multipassd, snap/hooks/configure, snap/snapcraft.yaml
Allow proxy configuration via "snap set proxy.{http,https}=...". Fixes #53
=> [snap] Allow proxy configuration via "snap set"

src/platform/backends/qemu/qemu_virtual_machine_factory.cpp
Sanitize unit if it ends with 'B' such as 'GB'. Fixes #67
=>  qemu: Sanitize units for --disk option during launch

src/sshfs_mount/sshfs_mount.cpp
When handling a rename from sshfs and the new path already exists, then remove
the existing file first before calling rename().
=> sshfs_mount: Fix issue with rename in the sftp server. Fixes #71

include/multipass/start_exception.h, src/daemon/daemon.cpp, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h
Catch if the qemu process is not running during IP discovery and wait for ssh. Fixes #64
=> qemu: Catch if the qemu process is not running during start

src/sshfs_mount/sshfs_mount.cpp
There is a race when using QFile where if a write has not made it to disk before an ensuing instantiation of QFile occurs, then the new QFile will get the older file information and use that even when the write does make it to disk.
This was exposed by git and how it handles its pack file.  git will write out a bunch of data to the pack file, and then turn right around and begin reading from it from new threads via a new open().  This is exacerbated further when multiple CPU's are defined in a VM and git uses multiple read threads.
The easy solution for now is to flush() after each write() to ensure the data is on disk.  This does impact performance a bit, but performance is already bad due to other reasons.  I plan on making the flush() unnecessary in a later PR by trying to use POSIX …
=> sshfs_mount: Force a flush() after write. Fixes #77, Fixes #83.

src/utils/utils.cpp
This fixes some cases where QDir::cleanPath() does not sanitize the leading '/'.
=> utils: Match one or more leading '/' when invalidating target paths

include/multipass/ssh/ssh_session.h, include/multipass/sshfs_mount/sshfs_mount.h, src/ssh/ssh_session.cpp, src/sshfs_mount/sshfs_mount.cpp
Unblock the sftp server thread by adding a way to forcefully shut
down an ssh session. This simplifies stopping an sshfs mount, no
longer needing to access potentially dead objects (indirectly
through the session factory).
Fixes #82.
=> [sshfsmount] Simplify shutdown

.travis.yml
Travis uses a default of 50 commits when cloning. If we go over
50 commits after the last tag however, the snapcraft build will fail
since our snapcraft recipe uses git describe to compute the version.
git describe fails if it doesn't find a tag in the history.
=> [travis] Disable default depth

.travis.yml
A classic snap has too much to do with the host it runs on, run the
tests in the lxc container instead.
=> [travis] run tests inside the container

src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.h
Fixes #75 
In addition to deleting the virtual bridge, the tap devices also have to be removed on shutdown or else networking will not work on the subsequent start up.  With that, make QemuVirtualMachine() responsible for deleting its tap device in its dtor.
=> qemu: Remove virtual bridge and VM tap devices on daemon shutdown

src/client/cmd/animated_spinner.cpp, src/network/url_downloader.cpp
QNetworkAccessManager has no built in QNetworkReply timeout, so need to use a
QTimer to do the dirty work.
Fixes #108
=> url_downloader: Set a 10 sec. timeout when downloading files

include/multipass/virtual_machine.h, src/client/formatter/format_utils.cpp, src/daemon/daemon.cpp, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/rpc/multipass.proto
Add these new statuses for finer control of what output should be shown in
`list` and `info`.
Fixes #121
=> virtual_machine: Add new `starting` and `unknown` status

include/multipass/optional.h, include/multipass/virtual_machine.h, include/multipass/vm_status_monitor.h, src/client/formatter/format_utils.cpp, src/client/formatter/table_formatter.cpp, src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/rpc/multipass.proto, src/ssh/ssh_session.cpp, tests/mock_status_monitor.h, tests/stub_status_monitor.h, tests/test_format_utils.cpp, tests/test_output_formatter.cpp
Use the QEMU Machine Protocol (QMP) interface for getting asynchronous events and
sending commands.
Fixes #50
=> qemu: Use qmp to get VM events and detect VM reboots

README.md, completions/bash/multipass, src/client/client.cpp, src/client/cmd/CMakeLists.txt, src/client/cmd/shell.cpp, src/client/cmd/shell.h, tests/test_cli_client.cpp
The `lxc` command line has a (non-advertised yet) `shell` command, let's
rename our `connect` to align. It's a better name as well.
I've left `connect` as an alias to not break people's muscle memory.
=> cli: rename `connect` to `shell` to align with lxd (Fixes: #115)

include/multipass/ssh/ssh_session.h, include/multipass/utils.h, include/multipass/virtual_machine.h, include/multipass/virtual_machine_description.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/daemon_rpc.cpp, src/daemon/daemon_rpc.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/ssh/ssh_session.cpp, tests/stub_virtual_machine.h, tests/test_cli_client.cpp, tests/test_daemon.cpp, tests/test_qemu_backend.cpp, tests/test_utils.cpp
Daemon's constructor could return before the rpc signals where connected to the daemon's slots. 
Remove unnecessary threading that removes that condition. 
In addition, daemon tests tried to make an ssh connection. To avoid that, moved the wait for cloud init into the VirtualMachine interface instead (which has the upside of letting the backend decide how to check for cloud-init).
I refactored the timeout code (which waits for a deadline) into common code in utils as it was replicated in a few places.
=> Fix intermittent failures in daemon tests

include/multipass/platform.h, include/multipass/sshfs_mount/sftp_server.h, src/platform/platform.cpp, src/sshfs_mount/sftp_server.cpp, tests/test_sftpserver.cpp
Support the "hardlink@openssh.com" and "posix-rename@openssh.com" extended methods.
Fixes #144
=> sftpserver: Support extended SFTP methods

src/client/client.cpp, src/client/cmd/CMakeLists.txt, src/client/cmd/delete.cpp, src/client/cmd/delete.h, src/client/cmd/launch.cpp, src/client/cmd/launch.h, src/client/cmd/purge.cpp, src/client/cmd/purge.h, src/client/formatter/format_utils.cpp, src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/daemon_rpc.cpp, src/daemon/daemon_rpc.h, src/rpc/multipass.proto, tests/test_daemon.cpp, tests/test_format_utils.cpp
Depends on #147
Use [this diff view instead](https://github.com/albaguirre/multipass/compare/fix-daemon-tests...rename-classes-to-match-cmds) before #147 is merged
=> Rename classes to match cmd names

src/ssh/ssh_session.cpp
libssh expects this to be long and `auto` likely made it int, causing
random failures.
=> [ssh] initialize the timeout as long

completions/bash/multipass
Add the `--format` option for list and info. Fixes #152.
Autocomplete the supported types for `--format`/`-f`.
Fix mount source completion on non-empty folders. Fixes #157.
Support option autocompletion for command aliases. Fixes #153.
Show instance name only once when it has been selected in the command line. Fixes #163.
Autocomplete instance names for the `delete` command.
=> bash: Fix various bugs in bash completion

include/multipass/ssh/ssh_session.h, include/multipass/sshfs_mount/sftp_server.h, src/sshfs_mount/sftp_server.cpp
The sftp server does not need an extra ssh session object.
=> [sftpserver] Avoid creating extra ssh_session

src/sshfs_mount/sftp_server.cpp
=> sftpserver: Use QFileDevice *Owner for showing permissions

src/daemon/daemon.cpp
If no instance names are provided by the client, then assume all instances are to be started.
Fixes #182
=> daemon/start: Assume '--all' when no vm names are sent by the client

src/daemon/daemon_main.cpp
=> rpc: Use 'sudo' group instead of 'adm' group for rpc socket.

src/daemon/daemon.cpp
Limit log to every 10% when automatically updating an image.
=> [daemon] limit logging when downloading an updated image

snap/snapcraft.yaml, src/daemon/daemon_config.cpp, src/platform/CMakeLists.txt, src/platform/logger/CMakeLists.txt, src/platform/logger/journald_logger.cpp, src/platform/logger/journald_logger.h, src/platform/platform.cpp, tests/travis-Coverage.patch
The default platform logger logs to journald.
The logs can be filtered through "journalctl _COMM=multipassd"
A CATEGORY field is recorded which can be the name of an instance,
"daemon", "rpc", among others.
To filter by category: "journalctl _COMM=multipassd CATEGORY=<value>"
Fixes #156
=> Add platform logger

include/multipass/auto_join_thread.h, include/multipass/console.h, include/multipass/platform.h, include/multipass/platform_unix.h, include/multipass/ssh/ssh_client.h, src/daemon/daemon_main.cpp, src/platform/CMakeLists.txt, src/platform/console/console.cpp, src/platform/console/unix_console.cpp, src/platform/console/unix_console.h, src/platform/platform_linux.cpp, src/platform/platform_unix.cpp, src/ssh/ssh_client.cpp, src/sshfs_mount/CMakeLists.txt, tests/stub_console.h, tests/test_daemon.cpp, tests/test_ssh_client.cpp
This avoids a delay in resizing the output when changing the size of
an interactive terminal.
=> console: Change ssh pty size from within the console class

include/multipass/backend_utils.h, snap/bin/launch-libvirtd, snap/bin/launch-multipassd, snap/hooks/configure, snap/hooks/install, snap/snapcraft.yaml, src/platform/CMakeLists.txt, src/platform/backends/CMakeLists.txt, src/platform/backends/backend_utils/CMakeLists.txt, src/platform/backends/backend_utils/backend_utils.cpp, src/platform/backends/libvirt/CMakeLists.txt, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.h, src/platform/backends/libvirt/libvirt_virtual_machine_factory.cpp, src/platform/backends/libvirt/libvirt_virtual_machine_factory.h, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.h, src/platform/platform_linux.cpp, tests/travis-Coverage.patch
To test with a local build:
`$ MULTIPASS_VM_BACKEND=LIBVIRT ./multipassd`
For a snap, after installing it, do:
`$ sudo snap set multipass vm-backend=LIBVIRT`
Also, when installed as a snap, `multipass.virsh` also works for administering the VM via virsh.
=> Support libvirt backend

.travis.yml, snap/snapcraft.yaml, tests/travis-Coverage.patch, tests/travis-Debug.patch
Instead, use `wget` and `dkpg-source` for retrieving and unpacking the package source.
Also, build multipass against our built libvirt instead of libvirt-dev from the archive.
=> snap: Remove using `apt-get source` for fetching libvirt package sources

snap/snapcraft.yaml
I can confirm in a private build on build.s.i, that this fixes the issue.
=> snap: Add missing build dependencies for wget and dpkg-source

snap/hooks/configure
`snap get multipass` shows the `driver-saved` setting otherwise.
=> [snap] don't use snap config for driver-saved

CMakeLists.txt, snap/bin/launch-multipass, snap/bin/launch-multipassd, snap/snapcraft.yaml, src/platform/backends/backend_utils/backend_utils.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/simplestreams/simple_streams_manifest.cpp
Some notes about this:
- The snap will not build for i386 due to the version of libicu we pull needs to be liked using gcc7 and the trusty environment it is built in does not have that version.
- The snap does build for amd64, armhf, and arm64, but it has not been tested on armhf nor arm64.
=> Detect host arch

src/daemon/default_vm_image_vault.cpp, src/daemon/default_vm_image_vault.h
This is not needed since the background image maintenance task will take care of
removing cached images and records when they are not needed.
Fixes #200
=> image_vault: Remove expunge_invalid_image_records()

include/multipass/vm_image.h, src/client/formatter/table_formatter.cpp, src/daemon/daemon.cpp, src/daemon/default_vm_image_vault.cpp, src/daemon/ubuntu_image_host.cpp, tests/stub_vm_image_vault.h, tests/test_image_vault.cpp, tests/test_output_formatter.cpp, tests/test_qemu_backend.cpp
In case the image is removed from the image server, cache the image's original release version so it can be displayed in info & list.
This only applies to any images downloaded after this is applied.  Retrieving information for images already downloaded will still query SimpleStreams.
=> image_vault: Cache the image release version

src/client/cmd/find.cpp
Also, reword the help for the optional search string to be more clear.
Fixes #215
=> find: Fix help to be consistent with `launch`

.travis.yml
Seems `lxd init --auto` now sets up networking on its own, no need to override.
=> [travis] let `lxd init` handle networking

include/multipass/virtual_machine.h, include/multipass/vm_status_monitor.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/utils/utils.cpp, tests/mock_status_monitor.h, tests/stub_status_monitor.h, tests/stub_virtual_machine.h, tests/test_qemu_backend.cpp
Persist the instance state in the DB and read this when the daemon starts. If instance
was running but is not currently, then start the instance.
Fixes #130
=> daemon: Restore instance state when starting

snap/snapcraft.yaml
Only send sigterm to libvirtd and not any of its spawned qemu processes.
Also, start multipassd after libvirtd has started.
Fixes #55.
=> snap: Do not kill libvirt's qemu processes on snap refresh

src/daemon/default_vm_image_vault.cpp, src/daemon/ubuntu_image_host.cpp, tests/test_ubuntu_image_host.cpp
This is a temporary measure for enabling launching via the `core` alias and will be replaced
by a more robust configuration.
=> image_vault: Support using `core` alias for launching Ubuntu Core images

snap/snapcraft.yaml
This is causing problems with other processes that are spawned by libvirtd.
=> snap: Revert libvirtd 'stop-mode: sigterm' daemon mode

src/daemon/daemon.cpp
=> daemon: Do not set a default remote during `launch`

3rd-party/CMakeLists.txt, 3rd-party/libssh/CMakeLists.txt, completions/bash/multipass
Highlights:
- support custom VM images (#24)
- support "core" as an alias (#87)
- switched to a dedicated "multipass" user inside the instance
- avoid hardcoding "/home/ubuntu" in your commands
Significant improvements:
- multiple bash completion fixes (#206, #207, #220, #239)
- fixed image caching if removed from streams (#200)
- caching info data to display when instance is stopped (#199)
- support for custom SSH keys (#52)
- (re)storing instance state (#130)
- verify downloaded images (#275)
=> Release 2018.6.1

src/ssh/ssh_session.cpp
libssh upstream has merged chacha20-poly1305 support to their master branch. 
The multipass-next branch is now based on that master branch + one patch to support sftp hardlink/rename extensions.
=> Update libssh version

src/sshfs_mount/sftp_server.cpp
Remove the QDir::System filter as it can sometimes lead to unpredictable behavior when
listing files.
Fixes #335
=> sftp-server: Remove QDir::System filter

src/sshfs_mount/sftp_server.cpp
Removing the filter has even more unintended consequences than leaving it there.
This reverts commit 6c7b340f539c16acac9873b6625de41be16442a2.
=> Revert "sftp-server: Remove QDir::System filter"

src/client/cmd/launch.cpp, src/rpc/multipass.proto
Also, add stub grpc messages for the actual metrics data to pass back to the client.
=> metrics: Update wording of the opt-in prompt to match the spec

src/daemon/daemon.cpp, src/daemon/daemon.h, tests/test_daemon.cpp
This includes the status of the opt-in as well as a counter that will prompt the
user on the third launch and every third launch if the user chooses `Later`.
=> metrics: Use a YAML config file for holding the metrics opt-in data

include/multipass/metrics_provider.h, src/daemon/daemon.cpp, src/metrics/metrics_provider.cpp, tests/test_metrics_provider.cpp
In case the daemon exits while the provider is trying to send the metrics,
persist the metrics so they can be retried after the daemon starts again.
=> metrics_provider: Persist metrics in case daemon exits

src/daemon/daemon.cpp
Rather than make the user think cloud-init is the only thing running in the background, update the message to instead be more generic while waiting for system to boot and initialize.
=> change boot wait message

3rd-party/libssh/CMakeLists.txt, src/ssh/ssh_process.cpp, src/ssh/ssh_session.cpp
Use newest libssh version.
When attempting to read a stream, a closed channel means there's
no data - make sure to check this condition instead of reporting
an error.
Since 0.8, libssh no longer requires a mutex/threads implementation
nor does it need an explicit call to ssh_init() to initialize the
library.
=> 3rd-party: Update libssh

tests/c_mock_defines.cmake, tests/mock_ssh.cpp, tests/mock_ssh.h, tests/test_ssh_process.cpp, tests/test_sshfsmount.cpp
Mock ssh_channel_is_closed.
Include tests that verify SSHProcess deals with closed channels
appropriately.
=> tests: ssh: Ensure ssh_channel_is_closed is mocked

src/sshfs_mount/sshfs_mount.cpp
This is so the daemon can catch exceptions thrown in run_cmd() instead on std::stoi() catching them.
This is to try to get more information about what is causing the failure for #425.
=> sshfs_mount: Split out run_cmd() calls out of std::stoi()

src/ssh/ssh_process.cpp, src/sshfs_mount/sshfs_mount.cpp
Also add more verbose debugging info for catching cases like this in the future.
Fixes #425
Co-authored-by: Chris Townsend <christopher.townsend@canonical.com>
=> ssh_process: Return any data already read if the channel is closed

include/multipass/sshfs_mount/sftp_server.h, src/sshfs_mount/sftp_server.cpp, tests/test_sftpserver.cpp
handle_opendir only put file names on the open_dir_handles so handle_readdir had no directory information. QFileInfo returns default file attributes if the file it points to does not exist. Combination
of these facts meant sometimes incorrect file metadata could be returned.
The test I added fails without the patch, so this is correcting something.
=> [sshfs] fix file metadata passthrough

snap-wrappers/bin/launch-multipassd
This way we can ask for debug logs when people report issues, and they can choose with `--priority` what they're interested in.
=> [snap] log up to debug level by default

snap/snapcraft.yaml
Without git our version script doesn't work in build environments, and
setting libvirt's source to `snap` means we no longer copy the whole
source.
=> [snap] add git to build packages and change libvirt's source

include/multipass/virtual_machine.h, src/daemon/daemon.cpp
Fix bug #461 
ssh_info returns connection data if machine is still running
=> shell to machine in delayed-shutdown state

src/client/cmd/mount.cpp, tests/test_cli_client.cpp
=> client/mount: Better uid/gid validation to account for larger values

src/client/cmd/common_cli.cpp
This fixes build issues with some compilers.
=> common_cli: Need namespace prefix for function parameters

snap/snapcraft.yaml, tests/travis-Coverage.patch, tests/travis-Debug.patch
Use `override-pull` to avoid pulling in any source when not needed.
=> [snap] reduce pull load

include/multipass/logging/multiplexing_logger.h, src/daemon/daemon_config.cpp, src/daemon/daemon_config.h, src/logging/multiplexing_logger.cpp
The "system" loggers have different lifecycle to the client loggers.
Client loggers register/unregister themselves with the
MultiplexingLogger on creation/destruction. However "system" loggers did
not, and would leave a dangling pointer in the MultiplexingLogger if
they were destroyed before it was.
Fix is to treat system logger ownership differently from client, i.e.
have MultiplexingLogger own the system logger.
Crash without this patch can be easily reproduced by adding a throw in
the QemuVirtualMachineFactory constructor.
=> Fix crash if exception thrown during daemon startup

src/platform/backends/backend_utils/backend_utils.cpp
Confining Bash and its friends is much harder than the actual utility.
=> Avoid using bash script for text processing, use code instead

src/daemon/daemon.cpp
It's possible that the suspend_finished signal is missed when the backend's suspend function is fast.
=> daemon/suspend: Use a QueuedConnection to avoid missing a signal

src/daemon/daemon.cpp
This will avoid a state where the sftp_server/sshfs pair is not running, but the daemon still holds the info in memory.
Fixes #511
=> daemon/mount: Avoid potential race if sshfs_mount exits quickly

src/client/argparser.cpp
=> client: Add 2 newlines after CLI parser error for better readability

src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.cpp
Fixes #505 
Notes:
- Any QEMU based instances will need to start from cold, ie, not suspended to enable this.
- Any LIBVIRT based instances will need be launched anew.
=> backends: Use host CPU passthrough for all CPU features in the VM

include/multipass/cli/command.h, src/client/cmd/CMakeLists.txt, src/client/cmd/common_cli.cpp, src/client/cmd/launch.cpp, src/daemon/daemon_main.cpp
I combined a few fixes in this as separate commits since they all went hand in hand and solve a couple of issues together.
Fixes #456, fixes #460
=> Fix daemon missing group

src/daemon/daemon.cpp
This avoids a race when delete & purge will start tearing down the VM itself before mounts are completely stopped and causes unexpected behavior.
=> daemon/delete: Explicitly stop mounts when deleting instances

src/daemon/custom_image_host.cpp
`/stable/current` is a better place to get the `core` image from, the former is 4 months older.
=> [daemon] use a better `core` image

src/daemon/daemon.cpp
Just a tiny detail: while the log message `Mount '/this/and/that' in instance "something_another" stopped` is perfectly correct, when glancing at it, it is easy to mistakenly read only the first bit, interpret "mount" as a verb, and think something was mounted (which is the opposite). 
This happened to me at least and this PR attempts to improve that.
=> Try to make log message's meaning easier to perceive at a glance.

src/daemon/daemon.cpp
This makes `grpc_status_for` return `Status::OK` when there are no errors, rather than repeating the same check in each call.
=> Make grpc_status_for handle no error case.

CMakeLists.txt
This reverts commit 760c9e2dd57df5d5291e0a989dfc46903d5825f9.
Unfortunately snapcraft dirtifies the build dir on Launchpad, so all our builds from there now have a `-dirty` suffix.
=> Revert "[cmake] mark dirty tree in the version string"

src/daemon/daemon.cpp
This picks up refactoring changes to how VM resources are released and extends them to other places that do the same thing, simplifying the corresponding code along the way.
=> Release resources consistently

CMakeLists.txt
- On Linux, suspending/resuming the instance to/from disk is now supported. (#374)
- Better handling of delayed shutdown including posting `wall` messages to logged in users and allowing log ins to the instance unless 1 minute or less remains until shutdown. (#461, #50) 
- On Linux, all CPU flags should be passed into the running instance on newly created instances. (#516)
- Fixed some races around mount handling. (#514, #520)
- make the recover command idempotent (#528)
- explicitly stop mounts when deleting an instance to avoid a race (#520)
- be smarter about what group owns the multipass socket (#513, #523) 
- pass through all CPU flags when launching QEMU or libvirt instances (#516)
- use `info` log level for metrics issues (#515)
- fix potential race when starting a mount (#514)
- …
=> Release 2018.12.1

src/daemon/daemon.cpp, src/daemon/daemon.h
Fixes #536. This adds a boolean field to each instance specification indicating whether or not it is deleted. 
This change is backward compatible: the daemon can still load VM specs that do not contain the new flag. Such VMs are regarded as not deleted.
=> Persistify deleted state and load it on daemon startup.

README.md
The readme currently does not provide an example of using cloud-init with multipass. This pull request fixes that and links to the blog post on the subject from the Ubuntu blog.
=> Add cloud-init usage example and link to blog post

src/platform/backends/qemu/qemu_virtual_machine.cpp
Fix #559 and also hangs when suspending a stopped instance.
=> Fix daemon hangs when suspending a suspended instance.

include/multipass/delayed_shutdown_timer.h, include/multipass/optional.h, src/daemon/daemon.cpp, src/daemon/delayed_shutdown_timer.cpp
=> delayed_shutdown: Only broadcast `wall` messages if SSHSession is valid 

debian/control
=> [debian] drop cmake-extras from build deps

include/multipass/vm_status_monitor.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, tests/mock_qemu_system.cpp, tests/mock_status_monitor.h, tests/stub_status_monitor.h
This is to allow resuming from suspend when changing QEMU versions in the snap.
Fixes #598
=> qemu: Save qemu "machine type" as metadata for the instance

.gitmodules, tests/test_sftpserver.cpp
This fixes compilation errors with recent toolchains. Replace deprecated INSTANTIATE_TEST_CASE calls. Fix subobject-linkage warning by moving tests to anonymous namespace.
=> Update googletest (sub-)submodule

include/multipass/utils.h, src/platform/backends/qemu/qemu_virtual_machine.cpp
Due to how we are interacting with the Qt event loop, it's possible to crash
when deleting an instance while it's still launching. The after effect of this
is that concurrent client connections will block until launch (or other long
running commands) finishes.
A plan has been fleshed out to alleviate the concurrent blocking and will be
implemented later.
Fixes #585
=> qemu: Remove QCoreApplication::processEvents() to avoid a crash

src/daemon/daemon.cpp
Removing QCoreApplication in #632 resulted in this symbol being missing.
=> [daemon] add missing QEventLoop include

tests/mock_qemu_system.cpp
The qemu-system mock was looking in the wrong position for the `-dump-vmstate` arg.
Fixes #629
=> tests/qemu: Fix arg that qemu-system mock looks for

include/multipass/cli/return_codes.h, src/client/cmd/shell.cpp, src/client/cmd/shell.h, src/daemon/daemon.cpp
=> client/shell: Start instance if it's not running

include/multipass/utils.h, include/multipass/virtual_machine.h, src/client/cmd/common_cli.cpp, src/client/cmd/common_cli.h, src/client/cmd/mount.cpp, src/client/cmd/start.cpp, src/daemon/base_cloud_init_config.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/rpc/multipass.proto, src/sshfs_mount/sshfs_mount.cpp, src/utils/utils.cpp, tests/stub_virtual_machine.h
Also move "just in time" sshfs install logic into the daemon.
Fixes #615
=> Remove sshfs install from cloud-init

tests/image_host_remote_count.cpp, tests/mischievous_url_downloader.cpp
Some platforms are sensitive to name spacing and have build errors
when the namespace is left out.
=> tests: Use namespace on function paramaters to fix build errors

src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/qemu/qemu_virtual_machine.cpp
The EventLoop tied to the QTimer was causing unintended behavior.  Instead, just wait
on suspend to finish in the particular backend code.
Fixes #609
=> daemon: Remove timer that waits for the suspend operation to finish

snap-wrappers/bin/launch-multipassd, snap/hooks/configure
Also use a 'snap_config' file for holding saved config values and no longer
use the "driver" file.
Fixes #626
=> snap: Detect proxy config changes and restart multipass

src/platform/backends/libvirt/libvirt_virtual_machine.cpp
When starting an instance with a managed save after snap base core18 upgrade,
match the error condition of mismatched ROM size and pass recovery steps to
the client.
=> backends/libvirt: Match invalid ROM size error on instance restore

src/platform/console/unix_console.cpp
=> Do not muck with PTY sizing when stdin is live (stdout irrelevant)

tests/test_cli_client.cpp
This prepares the ground for the testing the pet-env feature in the CLI client. It improves CLI client tests, by checking 
- the expected RPC calls are triggered
- no unexpected RPC calls are triggered
A future step is to check that the request parameters correspond to expectations.
=> Improve cli client tests

CMakeLists.txt, snap/snapcraft.yaml
Adhere to https://semver.org/, using the latest tag, number of commits since
latest annotated tag and commit abbreviation as version, pre-release
identifier and build metadata, respectively.
=> [release] use semantic versioning format

CMakeLists.txt
Be explicit about using *-dev and *-rc tags for interim builds and rely
on `git describe --exact` for releases.
=> [cmake] rework version detection (Fixes #713)

src/platform/backends/qemu/qemu_vm_process_spec.cpp
=> backends/qemu: Use -cdrom option instead of -drive to fix Disco instances

src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/platform/backends/qemu/qemu_vm_process_spec.cpp
This fixes the case where an instance is suspended using '-drive' for the cloud-init
iso and then the newer version of the daemon is started that uses the '-cdrom' option
instead and qemu fails to load the saved memory snapshot.
Fixes #738
=> backends/qemu: Use '-drive' option for already suspended instances

completions/bash/multipass, include/multipass/query.h, include/multipass/vm_image_host.h, src/client/cmd/find.cpp, src/client/cmd/launch.cpp, src/daemon/custom_image_host.cpp, src/daemon/custom_image_host.h, src/daemon/daemon.cpp, src/daemon/ubuntu_image_host.cpp, src/daemon/ubuntu_image_host.h, src/rpc/multipass.proto, tests/stub_image_host.h, tests/test_cli_client.cpp, tests/test_custom_image_host.cpp, tests/test_data/releases/multiple_versions_manifest.json, tests/test_image_vault.cpp, tests/test_ubuntu_image_host.cpp
This uses an `--allow-unsupported` option for `launch` and `find`.
Fixes #736
=> launch/find: Allow using and searching for unsupported cloud images

3rd-party/CMakeLists.txt, CMakeLists.txt, include/multipass/utils.h, src/network/url_downloader.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine_factory.cpp, src/platform/backends/qemu/dnsmasq_server.cpp, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, tests/mock_dnsmasq_server.cpp, tests/mock_qemu_system.cpp
Activates unused parameter warnings. Fixes all such cases, homogenizing implicated code.
Fixes #697
=> Warn unused param

include/multipass/vm_image_info.h, src/client/cli/cmd/launch.cpp, src/daemon/custom_image_host.cpp, src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/default_vm_image_vault.cpp, src/daemon/default_vm_image_vault.h, src/daemon/ubuntu_image_host.cpp, src/rpc/multipass.proto, src/simplestreams/simple_streams_manifest.cpp, tests/stub_image_host.h, tests/test_image_vault.cpp
The first launch will download and prepare the image while other launches of the
same image will block until the download and prepare is complete.
Fixes #664
=> image_vault: Allow for simultaneous launching of new images

src/daemon/daemon.cpp, tests/test_daemon.cpp
Fixes #764. We were omitting to set a promised future, which caused the client to hang.
I've added a basic test to catch this behaviour for this command. Later PR will try to generalise it for the other commands.
=> Fulfil promise for restart error condition

include/multipass/utils.h, include/multipass/virtual_machine_factory.h, src/daemon/daemon.cpp, src/daemon/daemon_config.cpp, src/platform/backends/libvirt/libvirt_virtual_machine_factory.h, src/platform/backends/qemu/qemu_virtual_machine_factory.h, src/utils/utils.cpp, tests/mock_virtual_machine_factory.h, tests/stub_virtual_machine_factory.h, tests/test_utils.cpp
=> backends/daemon: Allow for backend to determine its data/cache dirs

include/multipass/ssh/sftp_client.h, src/client/cli/cmd/transfer.cpp, src/client/cli/cmd/transfer.h, src/ssh/CMakeLists.txt, src/ssh/sftp_client.cpp, tests/CMakeLists.txt, tests/c_mock_defines.cmake, tests/mock_sftp.cpp, tests/mock_sftp.h, tests/mock_sftpserver.cpp, tests/mock_sftpserver.h, tests/sftp_server_test_fixture.h, tests/test_cli_client.cpp, tests/test_sftp_client.cpp
=> Add stdin & stdout to the transfer command

src/daemon/daemon.cpp, tests/test_daemon.cpp
=> launch: Clean up instance data if an error occurs during image prep

.travis.yml, snap/snapcraft.yaml, tests/travis.patch
- move to `base:`-enabled `snapcraft.yaml`
- improve snap metadata
- use `snapcraft --use-lxd` on travis
- add missing package
=> [snap] snapcraft.yaml cleanup and improvements

include/multipass/exceptions/settings_exceptions.h, src/client/cli/cmd/common_cli.cpp, src/client/cli/cmd/common_cli.h, src/client/cli/cmd/get.cpp, src/client/cli/cmd/set.cpp, src/utils/settings.cpp, tests/test_cli_client.cpp
This improves upon the code that was merged in #805 for #766 . I missed error handling and noticed when working on #776 .
=> Handle errors in reading/writting from/to persistent setttings

src/network/url_downloader.cpp
Due to how QNetwork handles caching via QNetworkAccessManager and issues it
causes, instead directly access the network cache. This includes comparing the
Last-Modified header of the URL to what is cached and also use cached data (if
availble) when there is an issue downloading the data from the URL.
Fixes #825, fixes #829
=> url_downloader: Directly use network cache when downloading data

include/multipass/utils.h, include/multipass/virtual_machine.h, src/client/cli/cmd/launch.cpp, src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/libvirt/libvirt_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine.h, src/utils/utils.cpp, tests/stub_virtual_machine.h
This allows launch to wait for a long running custom cloud-init.
Fixes #696
=> utils: Re-add wait_for_cloud_init()

README.md
According to [docs](https://discourse.ubuntu.com/t/multipass-exec-command/10851) and reality.
> The -- separator is required if you want to pass options to the command being run.
```
munit-258:~ develar$ multipass exec build-service lsb_release -a
Unknown option 'a'.
munit-258:~ develar$ multipass exec build-service lsb_release -- -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
munit-258:~ develar$ 
```
=> [readme] fix exec command example

CMakeLists.txt
=> [cmake] only use -rc tags on release/* branches

src/daemon/daemon.cpp, src/network/url_downloader.cpp, tests/test_daemon.cpp
Bugfixes:
###
- #680: Daemon leaks instances when launching with low `--disk`
- #825: Image hashes may not match when a new cloud-image is uploaded
- #829: `multipass launch…` should work offline for all cached images
- #840: `multipass find` with no args FATAL error
=> Release 0.7.1

src/utils/utils.cpp
This is an initial fix to avoid the deadlock, but a subsequent fix will come to
fix this and waiting for ssh better.
=> utils: Fix deadlock in waiting for cloud-init to finish

snap-wrappers/bin/launch-libvirtd, snap/hooks/install, snap/hooks/post-refresh, snap/snapcraft.yaml, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine_factory.cpp, src/platform/backends/libvirt/libvirt_virtual_machine_factory.h, tests/test_libvirt_backend.cpp, tests/travis-Coverage.patch, tests/travis-Debug.patch, tests/travis.patch
Maintaining libvirt in the snap causes burdens for not much gain. Anyone wanting to
use libvirt can just use the one installed on the host.
Fixes #482, fixes #846
=> snap: Remove libvirt from the snap

src/platform/backends/libvirt/libvirt_virtual_machine_factory.cpp, src/platform/backends/libvirt/libvirt_virtual_machine_factory.h, src/platform/backends/qemu/dnsmasq_server.cpp, src/platform/backends/qemu/dnsmasq_server.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.h, src/platform/backends/shared/linux/backend_utils.cpp, src/platform/backends/shared/linux/backend_utils.h, src/platform/backends/shared/linux/process_factory.cpp, src/platform/backends/shared/linux/process_factory.h, src/platform/platform_linux.cpp, tests/CMakeLists.txt, tests/stub_process_factory.cpp, tests/stub_process_factory.h, tests/test_dnsmasq_server.cpp, tests/test_libvirt_backend.cpp, tests/test_qemu_backend.cpp
We need to launch Processes all around our codebase. Piping a ProcessFactory pointer around to all those location is tedious. Instead I was inspired by @ricab 's Singleton work, and wish to propose this.
We'll be able to use this to launch a Process as conveniently as we do with QProcess, but it will be fully mockable & testable.
I've added StubProcessFactory to enhance our testing, as it keeps track of each process we launch, so we can check their arguments (just applied to Qemu backend tests currently, will do others next). I'll have a Mock ready shortly in a followup PR.
=> Make ProcessFactory a (testable) singleton

snap/snapcraft.yaml, tests/travis-Coverage.patch
`build.snapcraft.io` does not have it preinstalled.
=> [snap] add missing pkg-config

snap/snapcraft.yaml
It's considered an error to define a plug while using classic confinement.
=> snap: Remove the libvirt plug since we are using classic confinement

.travis.yml
This ensures we don't introduce problems with the snap that only
appear in the store.
=> [travis] review the built snap

src/daemon/default_vm_image_vault.cpp
This fixes an issue where the wrong hash id was being used when finalizing
an image used in launch.
Also, always use all info when updating the prepared_image_records map.
Fixes #867
=> image_vault: Use proper id when finding an existing image

snap/hooks/configure
If there is no driver set, configure will always fail.
Fixes #904
=> snap: Check for an empty 'driver' string first before comparing

tests/test_cli_client.cpp
This fixes new failures when moving to other platforms, on tests that rely on the qemu->libvirt switch specifics. It basically bypasses those tests when not applicable, changing names accordingly. It also adds a grpc-related test to complement the previous one.
This supersedes #914
=> Disable platform set tests

include/multipass/snap_utils.h, src/platform/backends/qemu/qemu_vm_process_spec.cpp, src/platform/platform_linux.cpp, src/utils/CMakeLists.txt, src/utils/snap_utils.cpp, tests/CMakeLists.txt, tests/mock_environment_helpers.h, tests/test_snap_utils.cpp
The multipass socket can be located in $SNAP_COMMON while both the daemon and client are in the same snap.
While doing this, deduplicate reads of the SNAP env var by using a small utility.
=> Locate socket in $SNAP_COMMON while snapped

src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/qemu/qemu_vm_process_spec.cpp, tests/test_qemu_backend.cpp, tests/test_qemu_vm_process_spec.cpp
This adjusts the Qemu command to enable Qemu's image "discard=unmap" feature, which causes the disk image to shrink when blocks are trimmed by the VM kernel.
A way to see this in action is to monitor the disk image size, while running these commands in the VM:
dd if=/dev/zero of=bigfile bs=1M count=1024
which will increase its size, and then
rm bigfile
sudo fstrim -v /
which should cause it to shrink again.
=>  Qemu: enable image compaction/garbage collection

src/daemon/daemon.cpp
api.staging.jujucharms.com is a test deployment and has no guarantee of
reliability or data retention. This updates multipass to send KPI
metrics to the correct deployment.
=> Send metrics to correct endpoint.

tests/test_cli_client.cpp
Just a little tweek to keep it tidy &ndash; I failed to use the constant here before.
=> [test] Replace literal with constant in test

include/multipass/process.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/shared/linux/backend_utils.cpp, src/platform/backends/shared/linux/linux_process.cpp, src/platform/backends/shared/linux/linux_process.h, tests/CMakeLists.txt, tests/mock_process.cpp, tests/mock_process_factory.cpp, tests/mock_process_factory.h, tests/mock_qemuimg.cpp, tests/stub_process_factory.cpp, tests/test_linux_process.cpp, tests/test_qemu_backend.cpp
It's not perfect, but I think it improves typical Process use.
Most of the time we run a short-lived utility process and want to read either its exit code, or output, so the old API provided methods for each. But it's inflexible, as what if you want both exit code & output? And then, what if the utilty process fails? 
The goal here is to return an object that contains all the state that is of interest when a process completes (and if it completes inside the timeout), i.e. the exit code, and then any the error state info.
The process output can already be read from Process::read_all_standard_output/error, which can be called after ProcessExitState indicates success anyway.
I'm curious what you think. I'll admit does make a quick Process call a little more wordy, but I prefer that to …
=> ProcessFactory exit state improvements

src/daemon/daemon.cpp
When restarting an eoan instance, 'reboot' will return an exit code.
Fixes #903
=> daemon: It's possible reboot can return an exit code

include/multipass/virtual_machine_factory.h, src/daemon/daemon.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.h, src/platform/backends/libvirt/libvirt_virtual_machine_factory.cpp, src/platform/backends/libvirt/libvirt_virtual_machine_factory.h, src/platform/backends/qemu/check_kvm_support, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.h, src/platform/backends/shared/linux/backend_utils.cpp, src/platform/backends/shared/linux/backend_utils.h, tests/c_mock_defines.cmake, tests/mock_libvirt.cpp, tests/mock_libvirt.h, tests/mock_virtual_machine_factory.h, tests/stub_virtual_machine_factory.h, tests/test_libvirt_backend.cpp, tests/test_platform_linux.cpp
This enables the backends to define how they check if their prerequisites are met before running and to also handle error conditions better and surface those to the user,
Fixes #6, Fixes #770, Fixes #775, Fixes #811
=> Implement backend healthcheck

include/multipass/delayed_shutdown_timer.h, src/daemon/daemon.cpp, src/daemon/delayed_shutdown_timer.cpp, tests/test_delayed_shutdown.cpp
Pass in the function to stop mounts before shutting down the instance.
Fixes #964
=> delayed_shutdown: Shut down mounts before shutting down vm

src/utils/settings.cpp
Derive the client configuration path without relying on the `ApplicationName` (which is set on `QApplication`). This allows the GUI client to look for the client config in the correct place.
This is required for #978 to function properly and clears up the stage for further development on #944.
=> [settings] Fix client config path on the GUI

include/multipass/process.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/shared/linux/backend_utils.cpp, src/platform/backends/shared/linux/linux_process.cpp, src/platform/backends/shared/linux/linux_process.h, tests/mock_process.cpp, tests/mock_process_factory.cpp, tests/mock_process_factory.h, tests/stub_process_factory.cpp, tests/test_linux_process.cpp, tests/test_qemu_backend.cpp
This renames ProcessExitState with ProcessState, and allows user to fetch process state from Process at any stage.
And quoting myself:
> The wait_for functions return false if the process exits unexpectedly, or the timeout hits. 
Not always true! wait_for_finished will return true if process crashes. wait_for_started return true after forking, so if the program doesn't exist, it doesn't notice.
=> Process - add API to fetch process state and close_write_channel

snap/snapcraft.yaml
Seems the archive has removed a newer version of libssl that is compatible with
Qt, so need to download the older version instead.
Note: The newer version of libssl was tried, but QSslSocket failed with
unresolved symbols.
=> snap: Fix missing libssl package in the archive

src/client/gui/gui_cmd.cpp, src/client/gui/gui_cmd.h
The petenv instance gets its own section at the top of the tray icon menu.
Fixes #966
---
I followed the design spec found at https://github.com/CanonicalLtd/multipass-design#status-menu as closely as I could.  A couple of things though.
- Currently, there is no clean way to determine if the petenv instance is using the default name or another name, so I always put the petenv name in the `Start` line whereas the spec (I think) specifies only putting the alternate petenv name and don't put a name if it's the default.
- We currently have no way to determine if `suspend` is available in the backend, so I always use `Stop` for now.
=> gui: Put the petenv instance at the top of the tray icon menu

src/utils/settings.cpp
Submitting this separately just for the sake of focused PRs.
=> [settings] Drop leftover include after c++17 move

include/multipass/cli/format_utils.h, tests/test_output_formatter.cpp
As part of that, refactor the formatter test suite into a parametrized one.
---
Take that, C++ tests!
=> [list] sort list reply alphabetically (Fixes #836)

snap/hooks/remove
Clean up any non-persistent data to avoid snapshotting it.
See https://forum.snapcraft.io/t/automatic-snapshot-opt-out/12131 for
reference.
---
The difference:
```
$ snap saved
Set  Snap       Age    Version                  Rev   Size    Notes
10   multipass  13.7m  0.9.0-dev.118+g8169155e  x1     3682B  auto
11   multipass  1m43s  0.9.0-dev.117+g37892a1   1101   339MB  auto
```
=> [snap] add remove hook (Fixes #916)

src/platform/backends/libvirt/libvirt_virtual_machine.cpp, tests/test_libvirt_backend.cpp
Better detect when an instance is started/stopped outside of Multipass.
Fixes #993
=> backend/libvirt: Fix not detecting new instance state

tests/test_platform_linux.cpp
Autostart tests were failing when instructions in #1045 were followed. This is because they were not accounting for a matching desktop file in HOME. This fixes that.
=> Fix autostart tests

include/multipass/platform.h, include/multipass/process.h, include/multipass/sshfs_mount/sshfs_mount.h, include/multipass/sshfs_mount/sshfs_mounts.h, include/multipass/sshfs_server_config.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/shared/CMakeLists.txt, src/platform/backends/shared/basic_process.cpp, src/platform/backends/shared/basic_process.h, src/platform/backends/shared/linux/process_factory.cpp, src/platform/backends/shared/sshfs_server_process_spec.cpp, src/platform/backends/shared/sshfs_server_process_spec.h, src/platform/platform_linux.cpp, src/platform/platform_unix.cpp, src/sshfs_mount/CMakeLists.txt, src/sshfs_mount/sshfs_mount.cpp, src/sshfs_mount/sshfs_mounts.cpp, src/sshfs_mount/sshfs_server.cpp, tests/CMakeLists.txt, tests/mock_process_factory.h, tests/mock_virtual_machine.h, tests/stub_process_factory.cpp, tests/test_sshfs_server_process_spec.cpp, tests/test_sshfsmount.cpp, tests/test_sshfsmounts.cpp
Move sshfs server from thread to separate process. Each mount spawns a new sshfs process.
Move book-keeping of mounts into dedicated SSHFSMounts class to simplify Daemon.
Make creation of this sshfs server process a platform responsibility (as different platforms will apply different security policies - will be applied in followup).
=> Split sshfs into separate process

tests/CMakeLists.txt, tests/mock_process_factory.h, tests/reset_process_factory.h, tests/stub_process_factory.h, tests/test_sshfs_server_process_spec.cpp, tests/test_sshfsmounts.cpp
And fix tests to not rely on the ordering from iterating over an unordered_map
=> Prepare for tests using ProcessFactory to not be linux-only

include/multipass/process.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/shared/basic_process.cpp, src/sshfs_mount/sshfs_mounts.cpp
- If an error occurs, while ProcessError does say why, the errorString() can reveal more details as to what happened (e.g. on Windows it can return Windows API error messages that are useful)
- fix bug where ProcessError enum wasn't registered with the signal/slot mechanism
=> Small Process API improvements/fixes

include/multipass/platform.h, src/platform/platform_linux.cpp, src/platform/platform_unix.cpp, src/sshfs_mount/sshfs_server.cpp, tests/stub_process_factory.cpp
Main change: while signal.h is a Windows header too, is it far more limited in functionality. Best not use it except in platform-specific places
=> Small changes to enhance cross-platform support

src/sshfs_mount/sshfs_server.cpp
Exceptions should be caught by reference to avoid slicing. My compiler (gcc 8.3) detected that and failed the build. This fixes it.
=> Fix exception slicing

src/platform/backends/qemu/iptables_config.cpp
To only add rules to a clean `iptables` slate. Fixes #1093.
=> [iptables] Clear rules on also when daemon starts

src/daemon/daemon.cpp, src/daemon/default_vm_image_vault.cpp
This will avoid blocking the daemon when an image is being updated.
Fixes #984
=> updater: Run image updater in a separate thread

include/multipass/settings.h, src/client/cli/cmd/common_cli.cpp, src/client/cli/cmd/common_cli.h, src/client/cli/cmd/get.cpp, src/client/cli/cmd/set.cpp, src/utils/settings.cpp
Addresses #1023 
This lists available configuration keys in `get` and `set`. I ideally they should offer guidance on what each key means and what values are allowed, but that will require more thought.
=> Provide available settings (Fixes #1023)

include/multipass/exceptions/unsupported_image_exception.h, src/daemon/default_vm_image_vault.cpp, src/daemon/ubuntu_image_host.cpp, tests/test_ubuntu_image_host.cpp
Catch issues when updating an image, log the issue, and then continue checking other images.
Fixes #1106
=> image_vault: Catch updater errors and continue

snap/snapcraft.yaml
No point depending on the whole dnsmasq daemon. This allows manual runtime dependencies to mimic snaps more closely without interfering with libvirt's own dnsmasq (see https://wiki.libvirt.org/page/Libvirtd_and_dnsmasq).
=> [snap] Skim dnsmasq dependency.

src/platform/backends/shared/basic_process.cpp, src/platform/backends/shared/basic_process.h, tests/test_basic_process.cpp
Add the program name to process error messages. This makes it easier to
quickly understand what process failed. Fixes #613 as a particular case.
=> [proc] Mention program name in process error

README.md
Add instructions to install run-time dependencies and split existing running instructions into several steps for coherency.
Fixes #612
=> [doc] Document runtime dependencies

src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/default_vm_image_vault.cpp, tests/test_image_vault.cpp
This will delete old images in the cache when updating an image and will also remove
any "leaked" images that are no longer in the database.
Fixes #1014
=> image_vault: Delete old images from the cache

snap/snapcraft.yaml
Transition from core16 to core18 requires those.
=> [snap] include missing compat ROMs (Fixes #1150)

src/daemon/daemon.cpp, src/platform/backends/shared/linux/process_factory.cpp
- If the SSHFSMissingError exception is thrown, the deleteLater() needs to run
immediately to avoid removing the ssfs_server apparmor profile at the wrong time.
- Catch exception if the apparmor profile cannot be removed.
Fixes #1131
=> daemon: Force the DeleteLater event to run

include/multipass/platform.h, src/platform/platform_linux.cpp, src/sshfs_mount/sshfs_server.cpp
When starting mounts asynchronously, ie, on start, when the thread that starts the mount
exits, this code would send a SIGHUP to sshfs_process, causing it to exit prematurely.
This code is mostly unnecessary since it's only for Linux and systemd takes care of killing
child processes if the main process dies unexpectedly when running the snap.
Fixes #1143
=> platform: Do not detect parent dying and send SIGHUP to ssfs_server

src/sshfs_mount/sshfs_server.cpp
---
This is the order in which the process spec [is calling with](https://github.com/CanonicalLtd/multipass/commit/696c51284bc4ad9a04a48fecefe9e27cb2216a56#diff-bc563b8588faba37e88672d27126cc96R52-R53).
This is a hotfix, and we should probably `typedef` `UidMap` and `GidMap` so they don't get mixed up.
=> [sshfs] fix UID/GID mapping (Fixes #1157)

src/platform/console/terminal.cpp
---
The only place this i used is https://github.com/CanonicalLtd/multipass/blob/a91c9c9a214841ba6f97e5c99b953180f8efd8bc/src/client/cli/cmd/launch.cpp#L177-L187
TTY is not a requirement for stdio, this check is wrong.
To test:
```
$ multipass launch --cloud-init - < file
error loading cloud-init config: cannot read from stdin without a TTY
Launched: …
```
=> [launch] do not require a TTY for --cloud-init via stdin

include/multipass/utils.h, src/platform/platform_linux.cpp, src/utils/utils.cpp
This refactors finding and linking of the autostart file, providing a generic utility to reuse in other platform implementations that rely on this mechanism (namely macos).
=> Platform refactor for autostart

src/platform/console/unix_console.cpp
=> console/unix: Only use interactive tty if both stdin & stdout are live

src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h
This avoids a Qt issue where writing to a socket from another thread causes issues.
Fixes #725
=> backends/qemu: Emit signal when deleting memory snapshot

src/platform/backends/shared/basic_process.cpp, src/platform/backends/shared/basic_process.h, src/platform/backends/shared/linux/apparmor.cpp, src/platform/backends/shared/linux/apparmor.h, src/platform/backends/shared/linux/process_factory.cpp
---
To test:
```shell
multipass stop --all
sudo modprobe -r kvm_intel
sudo modprobe kvm_intel nested=1
multipass start
multipass shell primary
wget \
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.0.21/linux-headers-5.0.21-050021_5.0.21-050021.201906040731_all.deb \
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.0.21/linux-headers-5.0.21-050021-generic_5.0.21-050021.201906040731_amd64.deb \
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.0.21/linux-image-unsigned-5.0.21-050021-generic_5.0.21-050021.201906040731_amd64.deb \
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.0.21/linux-modules-5.0.21-050021-generic_5.0.21-050021.201906040731_amd64.deb
sudo dpkg -i *.deb
sudo reboot
multipass shell primary
uname -a
sudo snap install multipass --beta --classic
multipass launch …
```
=> [linux] do not fail when AppArmor policy loading fails (Fixes #1216)

include/multipass/cli/client_platform.h, src/client/gui/gui_cmd.cpp, src/platform/client/client_platform_linux.cpp
Adds a notification for when an update is available.
Adds a first run notification to alert the user that the Multipass tray icon menu is running.
Fixes #1072 
---
The easiest way to test this is on Windows and modify the following files:
- `src/version.h.in`
-  Change `constexpr auto version_string = "@MULTIPASS_VERSION@";` to `constexpr auto version_string = "0.6.0";` (or a version less than what is currently released).
- `src/client/gui/gui_cmd.cpp`
- Change `about_update_timer.start(24h);` to `about_update_timer.start(60s);` (or whatever duration you'd like the notification to show).
Also, for the first run notification, due to a bug in Qt, the custom Multipass icon will not show in this notification on Ubuntu.  It should be there for the other platforms though.
=> Add update balloon notification

src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, tests/qemu/test_qemu_backend.cpp
Arguments needed to support suspend/resume were getting missed since arguments were only
defined on QemuVirtualMachine construction.
Fixes #1243
=> backends/qemu: Create/destroy Process as needed to avoid stale args

.travis.yml
Release _candidate_, so let's push there instead.
=> [travis] publish release candidates properly

src/platform/backends/qemu/qemu_virtual_machine.cpp, tests/qemu/test_qemu_backend.cpp
Fixes #1266. `vm_process` is a pointer now and it is null when in off state. Shutdown is called when deleting, which was dereferencing the ptr to kill the process, even if it wasn't there.
=> Fix delete crash

include/multipass/utils.h, src/client/gui/gui_cmd.cpp, src/daemon/daemon_monitor_settings.cpp, src/utils/utils.cpp, tests/test_utils.cpp
Creates an empty config file if it doesn't exists.
Fixes #1242
=> utils: Add function to check for a config file

3rd-party/libssh/CMakeLists.txt, src/ssh/CMakeLists.txt, src/utils/CMakeLists.txt
Also had to change the name of one of Multipass's libraries due to name collision in the
new libssh.
=> libssh: Update submodule to version 0.9.3

tests/mock_process_factory.cpp
Reset the ProcessFactory singleton when injecting a mock, since it could
have already been initialized. Fixes #1003.
OK, I finally got this. Unlike `MockSettings`, which is registered at the beginning of a testing run and stays alive until the end, `MockProcessFactory` works with "[scopes](https://github.com/canonical/multipass/blob/15f82c97749c4f4a000b231cda489f494e20a3db/tests/mock_process_factory.h#L47)" to register and reset the factory mock repeatedly over program execution. But tested code can still call `ProcessFactory::instance()` outside of the lifetime window of these scopes. The first such call after each scope's d'tor encounters a null singleton and initializes it with the real thing. 
Subsequent calls to instance() encounter the real factory, including when next trying to …
=> [test] Fix MockProcessFactory inject when existing

src/daemon/daemon.cpp
No need to issue a backend start() when the instance is in a restarting state.
Fixes #1315
---
I tested using the following method:
- Create an instance.
- `multipass exec <foo> -- sudo reboot`
- Confirm instance is in the `restarting` state.
- Issue `multipass start <foo>` while instance is in the `restarting` state.
=> daemon: Also check for the restarting state on start()

src/platform/backends/qemu/qemu_virtual_machine.cpp, tests/qemu/test_qemu_backend.cpp
Fixes #882. The error message from qemu says it all, and we had it already saved, but it was being overwritten in `on_shutdown`. This is useful also for other cases beside OOM (see tests below).
I tried adding tests for this, but I am being bitten by a variation of #1003. That is something that I would like to have a go at, otherwise it may always byte us back when we try to add tests. So keeping this no-merge for now, will check next week.
Here is how I tested manually:
1. `multipass launch --mem 1234G`
Output before fix:
```
launch failed: The following errors occurred:
first-crane: shutdown called while starting
```
And after fix:
```
launch failed: The following errors occurred:
qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory
equipped-robin: shutdown …
```
=> [qemu] Keep qemu error when shutdown during start

src/sshfs_mount/sshfs_mounts.cpp
Do not clear the whole `instance_mounts` map when removing all mounts for a particular instance.
This causes very bad behavior for other instances with mounts running as their info is cleared as well!
Fixes #1322
=> sshfs_mounts: Only clear the mounts for a particular instance

include/multipass/url_downloader.h, src/daemon/daemon_config.cpp, src/daemon/daemon_config.h, src/network/url_downloader.cpp, tests/test_daemon.cpp
Fixes #885
---
This was tricky to test.  I had to create an Ubuntu VM using Hyper-V and then in the VM, install `squid` and set it up.  Then I would set the `http_proxy` environment variable before running `multipassd`.
Also, after trying this and manually testing various failure scenarios, I have found the `URLDownloader` class, `CommonVMImageHost` and its derived classes, and the daemon need some pretty major refactoring to better handle long running network operations like when a host is unreachable and to also better getting these issues back to the user.
That said, this PR is *only* for getting the proxy values, but does nothing for failure scenarios.  That will come with a follow up PR.
=> daemon_config: Detect proxy env var and use it if found

src/platform/backends/qemu/qemu_vm_process_spec.cpp, tests/qemu/test_qemu_backend.cpp, tests/qemu/test_qemu_vm_process_spec.cpp
Rather than hardcoding xenial, as it's unlikely that someone's still
transitioning from core16 to core18.
=> [qemu] fall back to system default machine type

src/client/cli/argparser.cpp, src/client/cli/cmd/get.cpp, src/client/cli/cmd/help.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/shared/basic_process.cpp, src/platform/backends/shared/linux/backend_utils.cpp, src/platform/update/new_release_monitor.cpp
This is supposed to be used for logging and will also help with proper UTF8 output
on Windows.
---
This PR in conjunction with canonical/multipass-private#216 should make unicode characters in our help output properly.
Also note that this is Qt's recommendation: https://doc.qt.io/qt-5/qtglobal.html#qPrintable
> ...qUtf8Printable() should be used for logging strings instead of qPrintable().
=> output: Use qUtf8Printable() instead of qPrintable()

.travis.yml, CMakeLists.txt
We incorrectly published on PRs of `release/0.9` branches, and the version determination required for `release/*` to be a local ref instead of one in the `origin` remote.
---
Testing:
1. `MULTIPASS_UNLOCK` is required on a `release/*` branch
```console
$ git checkout -b release/0.0
$ cmake .
CMake Error at CMakeLists.txt:87 (message):
You need to set MULTIPASS_UPSTREAM for a release build.
Use an empty string to make local the authoritative repository.
```
1. setting `MULTIPASS_UPSTREAM=origin` makes it ignore the `release/*` branch
```console
$ git checkout -b release/0.0
$ MULTIPASS_UPSTREAM=origin cmake .
-- Setting version to: 1.1.0-dev.84+g4a33a0a9
$ git tag -as v0.0.0 -m Foo
$ MULTIPASS_UPSTREAM=origin cmake .
-- Setting version to: 1.1.0-dev.84+g4a33a0a9
$ git tag -d v0.0.0
```
1. …
=> [travis] fix release handling

.travis.yml, CMakeLists.txt
Rather than reading straight from the environment.
---
Working in real life:
https://github.com/canonical/multipass/pull/1375#issuecomment-589569113
Testing:
1. `MULTIPASS_UPSTREAM` is required on a `release/*` branch
```console
$ git checkout -b release/0.0
$ cmake . -UMULTIPASS_UPSTREAM
CMake Error at CMakeLists.txt:87 (message):
You need to set MULTIPASS_UPSTREAM for a release build.
Use an empty string to make local the authoritative repository.
```
1. setting `MULTIPASS_UPSTREAM=origin` makes it ignore the `release/*` branch
```console
$ git checkout -b release/0.0
$ cmake . -DMULTIPASS_UPSTREAM=origin
-- Setting version to: 1.1.0-dev.84+g4a33a0a9
$ git tag -as v0.0.0 -m Foo
$ cmake . -DMULTIPASS_UPSTREAM=origin
-- Setting version to: 1.1.0-dev.84+g4a33a0a9
$ git tag -d v0.0.0
```
1. …
=> [cmake] use a CMake variable for MULTIPASS_UPSTREAM

src/platform/console/unix_console.cpp, src/platform/console/unix_console.h
On OSX, SIGWINCH is ignored by default and thus, the way the console code was waiting on the signal,
it was never being delivered and the console size would never change.
Since OSX and Linux handle the console code the same, this change is for both platforms.
Fixes #1327
---
On Linux, `sigwait()` will not ignore any signals set in the `sigset` even if any of the signals are ignored by default.  However, OSX will ignore any signals in this case and `SIGWINCH` is ignored by default.
For testing, on Linux, the behavior should not change at all.  This does simplify the code though.  On OSX, you'll notice that the console stty would never change when `shell`ed into an instance, but with this change, that should work now.
=> unix_console: Better handle SIGWINCH

include/multipass/logging/level.h, src/client/cli/argparser.cpp, src/daemon/cli.cpp, src/platform/backends/shared/linux/apparmor.cpp, src/platform/logger/journald_logger.cpp
Move AppArmor profile logging contents to the trace level to avoid spamming the logs.
=> [logging] add trace level (Fixes #1371)

.gitmodules, include/multipass/process.h, src/daemon/default_vm_image_vault.cpp, src/utils/settings.cpp, tests/mock_process_factory.cpp, tests/test_basic_process.cpp
To keep our minimal macOS version lower, we need to work around some limitations of their c++17 support. What we know so far:
- `std::optional::value()` and `::reset()` are not supported
- `std::bad_optional_access` has no d'tor (so we mustn't throw it manually either)
- `std::optional::emplace` non-conformant (returns `void` rather than `T&`)
- `std::scoped_lock` is not supported
- `std::lock_guard` needs to be templated
Fixes #1258
=> [general] compatibility with macOS's c++17 support

src/platform/console/unix_console.cpp
=> console/unix: Only set terminal attributes when stdin & stdout are live

src/daemon/daemon_main.cpp
=> [daemon] try `wheel` socket group ownership, too

src/daemon/daemon.cpp
On particular platforms, it's possible that some aliases that are found for a
particular remote are not valid, so the created entry needs to be removed in
this case.
Fixes #1411
=> daemon/find: Account for no valid aliases being found

include/multipass/logging/cstring.h, include/multipass/top_catch_all.h, src/client/cli/main.cpp, src/client/gui/main.cpp, src/daemon/daemon_main.cpp, tests/CMakeLists.txt, tests/mock_logger.h, tests/test_top_catch_all.cpp
Fixes #1429.
---
Manual test examples (beyond unit tests):
- Daemon :
```console
$ ./bin/multipassd --logger=stderr -V debug  # non-admin user, no sudo
```
- CLI client:
```console
$ chmod -r ~/.local/share/multipass/client-certificate/multipass_cert.pem  # don't forget to revert
$ multipass
```
- GUI client:
```console
$ echo asdf > ~/.config/multipass/multipass.conf  # don't forget to revert
$ multipass.gui
```
=> Top level catch all

src/sshfs_mount/sshfs_mount.cpp, tests/test_sshfsmount.cpp
Fixes #953
When a path to a mount point must be created, all created directories except the last were owned by root.root.
Instead of creating the full path with a mkdir, now we check the existence of each directory in the path, create it and set the correct owner.
=> Correct ownership of mount directories

.travis.yml
The tests get run in Coverage, and RelWithDebInfo tries to publish after a successful build, for which we don't have credentials.
=> [snap] skip RelWithDebInfo if we don't have secure vars

src/daemon/custom_image_host.cpp
cdimage.u.c does not support https connections.
Fixes #1456
=> custom_image_host: Revert to http for cdimage.ubuntu.com

include/multipass/sshfs_mount/sftp_server.h, include/multipass/sshfs_mount/sshfs_mount.h, include/multipass/utils.h, src/client/cli/formatter/CMakeLists.txt, src/daemon/daemon.cpp, src/metrics/CMakeLists.txt, src/sshfs_mount/sftp_server.cpp, src/sshfs_mount/sshfs_mount.cpp, src/utils/utils.cpp, tests/test_sftpserver.cpp, tests/test_sshfsmount.cpp, tests/test_utils.cpp
Fixes #627
---
Notes about testing:
1. If an instance already has a mount defined, then `multipassd` should just use the `sshfs` that is already installed.
1. Any new instances or existing instances without a mount defined that then has a mount defined should install the `multipass-sshfs` snap and use that.
1. Mounts on `core16` and `core18` should work now.
=> Install the multipass-sshfs Snap for mount support 

src/platform/backends/qemu/dnsmasq_process_spec.cpp, tests/qemu/test_dnsmasq_process_spec.cpp
Otherwise it may try (and fail) to read /etc/dnsmasq.conf, when it exists, and die.
=> [qemu] pass --conf-file to dnsmasq (Fixes #1468)

include/multipass/standard_paths.h, src/client/common/client_common.cpp, src/client/gui/gui_cmd.cpp, src/daemon/daemon_config.cpp, src/platform/platform_linux.cpp, src/ssh/ssh_session.cpp, src/utils/CMakeLists.txt, src/utils/settings.cpp, src/utils/standard_paths.cpp, src/utils/utils.cpp, tests/CMakeLists.txt, tests/main.cpp, tests/mock_settings.cpp, tests/mock_settings.h, tests/mock_singleton_helper.h, tests/mock_standard_paths.cpp, tests/mock_standard_paths.h, tests/test_mock_settings.cpp, tests/test_mock_standard_paths.cpp
Adds a mockable `StandardPaths` singleton, as a thin wrapper around `QStandardPaths`. Implements the corresponding mock with the same approach as `MockSettings`, that is, via:
1. a test environment, to run custom code during test setup and tear down
2. a test event listener, to verify and clear mock expectations on the singleton at the end of each test
3. default operations delegating on the parent
To achieve that, this PR also extracts common stuff into a `MockSingletonHelper`.
This approach enforces accounting of mock expectations in the respective test. It also avoids singleton state leaking from test to test and affecting the results based on execution order. Finally, it ensures that tests only deal with the mock. They use only parent operations that are deemed safe for testing, …
=> Mockable standard paths

.github/ISSUE_TEMPLATE/config.yml
---
Result: https://github.com/Saviq/multipass/issues/new/choose
=> [github] add a link to documentation in issue templates

src/platform/backends/shared/linux/backend_utils.cpp, tests/linux/test_backend_utils.cpp
Also add unit tests for the convert_to_qcow_if_necessary() backend util function.
Fixes #1092
=> utils: Don't reuse unique_ptr vars when converting qcow image

include/multipass/utils.h, src/sshfs_mount/sshfs_mount.cpp, src/utils/utils.cpp, tests/test_sshfsmount.cpp, tests/test_utils.cpp
1. refactor `make_exec_to_check_commands()`, using `std::find_if()`;
2. add `\n` to all answers of the sshfs mock, because the real server always returns the newline and we were missing this behavior in the mock;
3. enforce newline checks in sshfs server code; and
4. use parameterized tests.
=> Refactor SSH tests

include/multipass/utils.h, src/sshfs_mount/sshfs_mount.cpp, src/utils/utils.cpp, tests/test_sshfsmount.cpp, tests/test_utils.cpp
The commands `id -u` and `id -g` are called two times each, consecutively, in sshfsmount. This can be refactored so each one is called only once.
=> Refactor many `id` calls in sshfsmount

include/multipass/utils.h, src/sshfs_mount/sshfs_mount.cpp, src/utils/utils.cpp, tests/test_sshfsmount.cpp, tests/test_utils.cpp
This commit adds support for specifying mount points starting with ~.
It also handles the case on which mount points or home paths end with a space character.
=> Expand `~` in mount target (Fixes #1230)

.travis.yml, tools/process_snaps.py
---
Before: https://travis-ci.org/github/canonical/multipass/builds/677570529
After: https://travis-ci.org/github/canonical/multipass/builds/677643390
The cron job is meant to fail until we rebuild `release/1.2` with this patch (or build/release on Launchpad, which we just did…).
=> [travis] fix process_snaps to deal with missing revisions in output

src/daemon/custom_image_host.cpp, tests/test_custom_image_host.cpp, tests/test_data/custom/SHA256SUMS
While we're working on the buildd images, `core20` can now be supported using the `minimal` images.
=> [custom] add snapcraft:core20 minimal image (Fixes #1417)

include/multipass/cli/client_common.h, include/multipass/constants.h, include/multipass/platform.h, src/client/cli/client.cpp, src/client/common/client_common.cpp, src/client/gui/client_gui.cpp, src/platform/platform_linux.cpp, src/utils/settings.cpp, tests/linux/test_platform_linux.cpp, tests/mock_logger.h, tests/test_cli_client.cpp, tests/test_daemon.cpp, tests/test_sshfsmount.cpp, tests/test_top_catch_all.cpp
Yet another approach. Addresses #1449 .
The setting is checked upon set, but applied separately.
Depends on #1467. Diff against that: https://github.com/canonical/multipass/compare/mockable-standard-paths...winterm-integration-take3
=> Windows Terminal integration

src/client/cli/argparser.cpp, tests/CMakeLists.txt, tests/test_argparser.cpp
Multipass accepted more than 3 vs in `-v` but kept the verbosity as error. This sets it to debug on 3 or more vs.
I couldn't find tests for arg parsing or verbosity. I am not sure if this is the PR to add them, so I just tested manually by editing code to print the configured verbosity.
=> [args] Enable debug verbosity on more than 3 vs

include/multipass/network_access_manager.h, src/network/CMakeLists.txt, src/network/local_socket_reply.cpp, src/network/local_socket_reply.h, src/network/network_access_manager.cpp, tests/CMakeLists.txt, tests/test_local_network_access_manager.cpp
This is needed to communicate with the LXD Unix socket.
This is a minimal implementation and can be modified later for more/better functionality.
---
We should be able to replace anywhere we use `QNetworkAccessManager` with this class and have just one implementation.
=> [network] Implement Qt classes to communicate with a Unix socket

src/daemon/daemon_main.cpp
macOS has a `wheel` group, but admin users are not part of it…
In support:
- [Debian](https://wiki.debian.org/sudo)/[Ubuntu](https://wiki.ubuntu.com/QuantalQuetzal/TechnicalOverview/Alpha1#General): `sudo`
- [Fedora](https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/basic-system-configuration/Gaining_Privileges/)/[CentOS/RHEL](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/chap-gaining_privileges)/[Arch](https://wiki.archlinux.org/index.php/Users_and_Groups#Group_list)/[SuSE](https://en.opensuse.org/SDB:Administer_with_sudo): `wheel`
Fixes #1563
=> [daemon] Prefer `admin` over `wheel` group and remove `adm`

snap-wrappers/bin/launch-multipassd
This is so that you can override `--verbosity` with a systemd `.override` file.
=> [snap] pass daemon arguments in `launch-multipassd`

include/multipass/exceptions/empty_manifest_exception.h, include/multipass/exceptions/manifest_exceptions.h, src/daemon/common_image_host.cpp, src/daemon/common_image_host.h, src/daemon/ubuntu_image_host.cpp, src/simplestreams/simple_streams_manifest.cpp, tests/test_simple_streams_manifest.cpp
If products are missing, don't fail, but log info instead.
It may be a valid situation on LXD at the moment.
=> [streams] don't die on missing products

snap/snapcraft.yaml
- This will ease the restriction a bit of where the client can mount and copy-files.
---
This is just partial fix for where user's can mount and copy-files.  The better long term solution is to use `multipass-support` for the clients.
=> [snap] Allow CLI client to use the "all-home" interface

include/multipass/platform.h, include/multipass/virtual_machine_factory.h, include/multipass/vm_image_vault.h, src/daemon/daemon_config.cpp, src/platform/backends/libvirt/CMakeLists.txt, src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.h, src/platform/backends/lxd/lxd_vm_image_vault.cpp, src/platform/backends/lxd/lxd_vm_image_vault.h, src/platform/backends/qemu/CMakeLists.txt, src/platform/backends/shared/base_virtual_machine_factory.h, src/platform/backends/shared/linux/CMakeLists.txt, src/platform/platform_linux.cpp, tests/CMakeLists.txt, tests/mock_virtual_machine_factory.h, tests/stub_virtual_machine_factory.h, tests/test_base_virtual_machine_factory.cpp
- All LXD backend classes will share a single NetworkAccessManager object owned by LXDVirtualMachineFactory.
=> [lxd] Use a single NetworkAccessManager object

src/platform/backends/qemu/dnsmasq_server.cpp, src/platform/backends/qemu/dnsmasq_server.h
Remove an explicitly-defaulted move ctor that actually gets implicitly deleted because the QTemporaryFile member is non-copyable. Make the class non-copyable instead (since it owns a dnsmasq process resource).
The class should still have been non-copyable, but just to be sure, since an unintentional copy could explain the behavior I experienced yesterday, where dnsmasq seemingly failed to come up. That's kind of what I would expect if a) dnsmasq was found to be running and b) a temporary dtor immediately killed it.
Also add some debug logging to help untangle problems in the future.
=> Dnsmasq server fix

src/platform/console/unix_console.cpp
Previously, all Multipass sessions used the default TERM value "xterm". With this change, we pull TERM in from the environment and set it explicitly.
Cleaned up the code that updates the pty size. This makes it simpler to pull in geometry values for the initial call to request a channel.
Also removed unused setup_environment method in Console. I can revert this commit if we want this to stick around.
This fixes: #1004
=> Switch to ssh_channel_request_pty_size to set TERM explicitly

include/multipass/constants.h, src/client/cli/cmd/get.cpp, src/client/cli/cmd/get.h, src/client/cli/cmd/set.cpp, src/client/gui/gui_cmd.cpp, src/client/gui/gui_cmd.h, src/platform/CMakeLists.txt, src/platform/platform_linux.cpp, src/platform/platform_shared.cpp, src/platform/platform_shared.h, src/utils/CMakeLists.txt, src/utils/settings.cpp, tests/CMakeLists.txt, tests/linux/test_platform_linux.cpp, tests/test_cli_client.cpp, tests/test_platform_shared.cpp
Fixes #1311. Also introduces `get --raw`.
=> Hotkey config

include/multipass/virtual_machine_factory.h, src/daemon/daemon.cpp, src/platform/backends/shared/base_virtual_machine_factory.h, tests/mock_virtual_machine_factory.h, tests/stub_virtual_machine_factory.h, tests/test_base_virtual_machine_factory.cpp, tests/test_daemon.cpp
---
The factory configure() method is a no-op for all backends and I see no reason to keep it around.
=> [factory] Remove configure() as it's not used by any factory

src/process/basic_process.cpp
This logging is implemented in BasicProcess, thus it will work for all processes launched as a ProcessSpec.
The feature was discussed in https://github.com/canonical/multipass-private/pull/273
=> Log the command-line of the command being executed

src/process/basic_process.cpp
So that direct calls to `BasicProcess::start` are also logged.
=> Move process logging to start

CMakeLists.txt, snap/snapcraft.yaml, tests/CMakeLists.txt, tests/libvirt/CMakeLists.txt, tests/travis-Clang.patch, tests/travis.patch
- Add "build-snaps" for specifying cmake snap for building snap.
- target_link_libraries() will now work in subdirectories so get rid of libvirt test hack.
---
This will allow for better gRPC build handling: https://grpc.io/blog/cmake-improvements/
=> [build] Require cmake version 3.13 or higher

snap/snapcraft.yaml
This fixes launchpad-buildd builds where Snapcraft does not set the /snap/bin at beginning of $PATH.
=> [snap] Set 'build-environment' PATH

include/multipass/exceptions/snap_environment_exception.h, src/platform/backends/qemu/dnsmasq_process_spec.cpp, src/platform/backends/qemu/qemu_base_process_spec.cpp, src/platform/backends/qemu/qemu_vm_process_spec.cpp, src/platform/backends/shared/linux/CMakeLists.txt, src/platform/backends/shared/linux/apparmor.cpp, src/platform/backends/shared/linux/process_factory.cpp, src/platform/backends/shared/sshfs_server_process_spec.cpp, src/platform/platform_linux.cpp, src/process/qemuimg_process_spec.cpp, src/utils/snap_utils.cpp, tests/linux/CMakeLists.txt, tests/linux/mock_aa_syscalls.cpp, tests/linux/mock_aa_syscalls.h, tests/linux/test_apparmored_process.cpp, tests/linux/test_platform_linux.cpp, tests/linux/test_snap_utils.cpp, tests/qemu/test_dnsmasq_process_spec.cpp, tests/qemu/test_qemu_vm_process_spec.cpp, tests/test_qemuimg_process_spec.cpp, tests/test_sshfs_server_process_spec.cpp
- When a snap-related directory environment variable is not found, throw the new SnapEnvironmentException exception.
=> [snap_utils] Throw exception when snap dir env vars are not found

include/multipass/virtual_machine_factory.h, src/daemon/daemon.cpp, src/platform/backends/libvirt/libvirt_virtual_machine_factory.cpp, src/platform/backends/libvirt/libvirt_virtual_machine_factory.h, src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.h, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.h, src/platform/backends/shared/base_virtual_machine_factory.h, tests/mock_virtual_machine_factory.h, tests/stub_virtual_machine_factory.h, tests/test_base_virtual_machine_factory.cpp
Hey @luis4a0, I added a few tweaks to the backends' `list_networks`. 
I am not entirely sure about the middle commit, because it's still not clear to me how we'll want to integrate the info from the platform and the backends, how to handle overlaps, etc. If it turns out that multiple backends just get everything from the platform and need nothing else, then it would make sense to call that in the base factory. 
For the time being, the empty impl was just a placeholder, so I thought we'd better have placeholders for each backend, to avoid forgetting the placeholder in the base and proper implementation in the backends. Let's discuss this later today :slightly_smiling_face:
=> Use net info in backend

3rd-party/CMakeLists.txt, 3rd-party/libssh/CMakeLists.txt, src/cert/CMakeLists.txt, src/rpc/CMakeLists.txt
- boringssl-with-bazel
- boringssl itself has been dropped.
- Point openssl includes to boringssl-with-bazel directory.
- Drop libssh link to decrepit library is this is no longer built.
- Explicitly link the cert library to the ssl library.
- protobuf
- Drop '-Wno-extended-offsetof' check as this is no longer used by protobuf.
- Add '-Wno-error' for rpc builds since new protobuf uses the zero byte array extension
and ISO C++ forbids causing -pendantic to issue a warning that gets treated like an error.
=> [grpc] Changes needed to support updating gRPC to version 1.30.2

src/platform/backends/lxd/lxd_virtual_machine.cpp, tests/lxd/test_lxd_backend.cpp
The image is downloaded separately, so there is no need to send source info that tells LXD where to download an image during instance creation.
=> [lxd] Do not send unnecessary source info on instance creation

include/multipass/vm_image.h, src/daemon/custom_image_host.cpp, src/daemon/default_vm_image_vault.cpp, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/lxd/lxd_vm_image_vault.cpp, tests/libvirt/test_libvirt_backend.cpp, tests/lxd/test_lxd_backend.cpp, tests/lxd/test_lxd_image_vault.cpp, tests/qemu/test_qemu_backend.cpp, tests/qemu/test_qemu_vm_process_spec.cpp, tests/stub_vm_image_vault.h, tests/test_image_vault.cpp
The LXDVMImageVault is the only class that needs stream_location as provide by the ImageHost. There is no need to save this or make it available for LXDVirtualMachine.
=> [lxd] Drop saving stream_location as this is only needed for LXDVMImageVault

src/platform/backends/lxd/lxd_vm_image_vault.cpp, tests/lxd/test_lxd_image_vault.cpp
Previously, when the "multipass" project didn't exist on daemon start, there would be an unhandled exception and the daemon would exit.
Fixes #1689
=> [lxd] Add try/catch around updating and pruning images

include/multipass/exceptions/http_local_socket_exception.h, src/network/local_socket_reply.cpp, src/network/local_socket_reply.h, src/network/network_access_manager.cpp, src/platform/backends/lxd/lxd_request.cpp, tests/linux/mock_q_buffer.h, tests/linux/mock_q_local_socket.h, tests/linux/test_local_network_access_manager.cpp, tests/lxd/test_lxd_backend.cpp
Don't set "Multipass" specific data in the NetworkAccessManager and LocalSocketReply.
Support chunked transfers for uploading data.
=> [network_manager] Generalize requests and support chunked uploads

tests/lxd/test_lxd_backend.cpp
Instead of using an arbitrary sleep, loop to make sure the state is really set from shutdown().
Fixes #1703
---
Supersedes #1705
=> [tests] Fix hang in LXDBackend.shutdown_while_starting_throws_and_sets_correct_state

include/multipass/virtual_machine.h, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/shared/shared_backend_utils.h, tests/libvirt/test_libvirt_backend.cpp, tests/qemu/test_qemu_backend.cpp
Also, instead of changing the instance state to detect if an instance is shutdown while starting, use a flag.
=> Add common ensure_vm_is_running_for() function

include/multipass/process/basic_process.h, include/multipass/process/process.h, src/process/basic_process.cpp, tests/mock_process_factory.cpp, tests/mock_process_factory.h, tests/stub_process_factory.cpp
Public pre-requisites to move PS to `mp::Process`.
=> Move ps to proc factory

debian/control, snap/snapcraft.yaml
boringssl is no longer built and that is what required golang.
=> [snap] Remove golang build dependency

src/platform/backends/qemu/dnsmasq_server.cpp
Increases the period we wait to detect immediate failures of the dnsmasq process.
=> Increase period for immediate dnsmasq wait

.github/actions/build-params/action.yml
The message in context is full, we need just the subject, and that's not available in the context.
=> [gha] fix build params with multi-line commit messages

.github/workflows/linux.yml
The global variable does not transfer into the LXD environment.
=> [gha] move CTest environment variable

src/client/gui/main.cpp
Hopefully fixes #1770.
Qt consumes `-session <id>` from the command line before we have a chance to parse it. When we parse the `QApplication::arguments()`, it's no longer there, so we continued happily. But then we were not running with a proper environment, so no luck reaching the daemon.
Since we don't implement session restoring, we need to explicitly refuse the attempt. 
This is only applicable to `QGuiApplication`s, so it does not affect our other binaries.
References:
- https://doc.qt.io/qt-5/qguiapplication.html#supported-command-line-options
- https://code.woboq.org/qt5/qtbase/src/gui/kernel/qguiapplication.cpp.html#1547
- https://code.woboq.org/qt5/qtbase/src/gui/kernel/qguiapplication.cpp.html#1573
- https://doc.qt.io/qt-5/session.html
=> [gui] Refuse session restoring

tests/disabling_macros.h, tests/test_cli_client.cpp, tests/test_image_vault.cpp, tests/test_qemuimg_process_spec.cpp
Disable failing tests on Windows and macOS. This is meant as a temporary measure, so that we can otherwise fail CI on failing tests, thereby avoiding pile up of further test failures.
Addresses #1515.
=> Disable failing tests

src/platform/backends/qemu/dnsmasq_server.cpp
There are still some occasional CI test failures due to the timeout being a little short.
=> [dnsmasq_server] Increase wait timeout to 100ms

include/multipass/vm_image_vault.h, src/daemon/default_vm_image_vault.cpp, src/utils/vm_image_vault_utils.cpp, tests/test_image_vault.cpp
Check the instance_image_records map if an image is not found in the prepared_image_records map.
Fixes #1818
=> [default_image_vault] Fix regression for file-based launches

src/platform/backends/lxd/lxd_virtual_machine.cpp
This impacts only the "Instance shutdown during start" situation on LXD. I verified 5s is not enough on a Pi4, and the worst case is that this will delay `launch` failing when someone did indeed stop the instance being started.
=> [lxd] increase first boot timeout to 20s

tests/qemu/test_dnsmasq_server.cpp
Clang complains about capturing not needed variables. In particular, we are capturing a non-mutable constexpr, which does not need to be captured. See [here](https://en.cppreference.com/w/cpp/language/lambda).
=> Fix lambda captures

include/multipass/virtual_machine_description.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/qemu/qemu_vm_process_spec.cpp, tests/libvirt/test_libvirt_backend.cpp, tests/lxd/test_lxd_backend.cpp, tests/qemu/test_qemu_backend.cpp, tests/qemu/test_qemu_vm_process_spec.cpp
We had left this for after the main PRs were merged. 
Revert to mac address only instead of a full network interface struct in VM description. This keeps the code aligned with persistent records and avoids failure to honor the extra properties (id and mode).
=> [networking] Drop unused traits in VM description

include/multipass/cli/argparser.h, src/client/cli/argparser.cpp, src/client/cli/cmd/exec.cpp, tests/test_cli_client.cpp
Addresses #531 . When a user forgets to separate options with `--` when running the `exec` command, provides a suggested command that includes the `--`. Below is a screenshot of the behavior with the change.
=> Add suggested command when 'exec' gets an unrecognized option

src/client/cli/cmd/launch.cpp
It needs to use the input stream in its `Terminal` attribute instead.
=> Fix direct use of `std::cin` in launch cmd

src/daemon/daemon.cpp, tests/stub_virtual_machine_factory.h, tests/test_daemon.cpp
This PR includes code to validate the network names given as argument to `--networks`.
This address one of the first concerns in the review of https://github.com/canonical/multipass/pull/1745 and implements what is described in https://github.com/canonical/multipass/projects/12#card-47746768
=> Validate network names

include/multipass/virtual_machine_factory.h, src/daemon/daemon.cpp, src/platform/backends/shared/base_virtual_machine_factory.h, tests/mock_virtual_machine_factory.h
Stop reinterpreting network IDs at the daemon, and remove the corresponding interface from the VM factories. Network ID reinterpretation can be treated as an implementation detail of the VirtualBox backend.
=> [daemon] Remove network ID reinterpretation

src/daemon/daemon.cpp, tests/test_daemon.cpp
To address #938 I used the std::filesystem library to check for available space in the user’s directory.
=> Add check for available disk space on launch

include/multipass/snap_utils.h, src/client/cli/cmd/launch.cpp, src/utils/snap_utils.cpp, tests/linux/test_snap_utils.cpp
Use utility to obtain home for auto-mount. This fixes a failure when running with an environment inherited from another snap (e.g. CLion). The test in question would change `HOME` but still get an auto-mount of `SNAP_REAL_HOME`, if this was defined.
=> Fix testing in foreign snap

tests/mock_environment_helpers.h
Just a couple of mends to `SetEnvScope` (which I happened to have a close look at when investigating a test failure when running within CLion).
=> Tiny mockenv change

tests/libvirt/CMakeLists.txt
Another tiny fix that I found when trying to better integrate with CLion. Without this, tests fail if built on their own (e.g. `make covreport`).
=> [cmake] Fix a missing dependency for tests

snap/snapcraft.yaml
The core18 snap already includes everything we need, so this part is no longer necessary.
=> [snap] Drop the network-utils part

tests/lxd/mock_network_access_manager.h, tests/lxd/test_lxd_backend.cpp
LXD test improvements extracted from #1912: provide an empty but non-null reply from the mock network mgr by default, to avoid crashing on unexpected mock calls. Expect calls explicitly. Remove superfluous calls to `unique_ptr::get`
=> LXD test improvements

src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.h, tests/lxd/mock_lxd_server_responses.h, tests/lxd/test_lxd_backend.cpp
This implements network listing from the LXD backend. As discussed, only bridges are returned. 
If available, descriptions from LXD are used. Otherwise, we fall back to "Network bridge". 
Example:
```
$ multipass networks
Name    Type    Description
lxdbr0  bridge  Network bridge
mpbr0   bridge  Network bridge for Multipass
virbr0  bridge  Network bridge
```
Bridge members are left for another PR, as well as `launch --network`.
=> Implement `networks` in LXD backend

src/daemon/daemon.cpp, tests/test_daemon.cpp
We use to configure the network interfaces using cloud-init. Specifically, we use version 2 of the network configuration. However, old images, like xenial, don't support this version of the network configuration file.
In this PR, we do the following to overcome the situation:
1. don't allow old images to use bridging (which needed configuration via cloud-init);
2. don't use cloud-init at all to configure network interfaces in the case on which bridging is not used.
This addresses issue https://github.com/canonical/multipass/issues/1904
=> Don't use cloud-init to configure network in old images

include/multipass/virtual_machine.h, src/client/cli/formatter/csv_formatter.cpp, src/client/cli/formatter/json_formatter.cpp, src/client/cli/formatter/table_formatter.cpp, src/client/cli/formatter/yaml_formatter.cpp, src/daemon/daemon.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.h, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/lxd/lxd_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/platform/backends/shared/shared_backend_utils.h, src/rpc/multipass.proto, tests/lxd/test_lxd_backend.cpp, tests/mock_virtual_machine.h, tests/qemu/test_qemu_backend.cpp, tests/stub_virtual_machine.h, tests/test_output_formatter.cpp
This PR adds the ability to gather all the IP's used by each instance.
The private bits of this PR are in https://github.com/canonical/multipass-private/pull/338.
=> Show multiple IP's in `list` and `info` commands

src/platform/backends/lxd/lxd_virtual_machine.cpp, tests/lxd/test_lxd_backend.cpp
=> [LXD] Fix regression when stopping an instance when it's already stopped

src/platform/backends/lxd/lxd_request.cpp, src/platform/backends/lxd/lxd_request.h, tests/lxd/test_lxd_backend.cpp
This will keep the user from seeing a bunch of JSON from being spewed in their client.
Fixes #1927
=> [lxd_request] Set JSON parsing error dump to debug

src/daemon/daemon.cpp, tests/test_daemon.cpp
Skip entries where all members are 0/empty, which we know are ghosts of
purged instances. They get removed in the following DB update.
Addresses #1935.
=> [daemon] Skip ghost instances in JSON DB

src/client/cli/client.cpp, src/daemon/daemon.cpp, tests/test_daemon.cpp
Allow over-committing disk space, as that's a feature, not a bug. Still fail on disk space lower than image size, and warn on over-committing.
=> Rework disk space check. Fixes #1926

src/daemon/daemon.cpp
`netplan` in the image is too old to handle our config:
```plain
Stderr: Error in network definition //etc/netplan/50-cloud-init.yaml line 12 column 12: unknown key dhcp4-overrides
```
---
For reference: https://bugs.launchpad.net/netplan/+bug/1759014
=> [daemon] disallow `--network ...,mode=auto` on Ubuntu Core 16

src/client/cli/cmd/launch.cpp, src/daemon/daemon.cpp, tests/test_cli_client.cpp, tests/test_daemon.cpp
`multipass launch --network` accepts `id=` as the key to the interface name argument. This must be changed to `name=` in order to avoid confusion with the network listing, on which interface names are listed using 'name' as field name.
=> Rename 'id' to 'name' in launch command

src/client/cli/cmd/list.cpp, src/client/gui/gui_cmd.cpp, src/daemon/daemon.cpp, src/rpc/multipass.proto
The GUI issues one `list` request to the daemon per second. Since now `list` asks the instances for the IP's it's using, this consumes lots of resources.
This PR fixes that, by adding a hidden parameter to the `list` command, telling the daemon whether it should ask the instance for the IP's.
=> Don't ask for IP when querying the daemon from the GUI

include/multipass/platform.h, src/platform/platform_linux.cpp, tests/mock_platform.h, tests/mock_settings.h, tests/mock_singleton_helper.h, tests/mock_singleton_helpers.h, tests/mock_standard_paths.h
Create a `Platform` singleton to facilitate mocking. Move `get_network_interfaces_info()` into it. Provide a `MockPlatform` for it.
Note: I kept it in the `multipass::platform` namespace for now, for consistency with the free functions. When/if we move all free functions to the class, we should probably get rid of the `platform` namespace altogether, to reduce verbosity in things like `using multipass::platform::Platform::Platform` :)
=> Platform singleton

src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, src/platform/platform_linux.cpp, src/platform/platform_linux_detail.h, tests/linux/test_platform_linux.cpp, tests/lxd/test_lxd_backend.cpp
Include members in bridge descriptions, by implementing bridge inspection on the Linux platform. Example output:
```
$ multipass networks
Name    Type    Description
lxdbr0  bridge  Empty network bridge
mpbr0   bridge  Network bridge for Multipass
mybr0   bridge  Network bridge with enxe4bf7a032432
virbr0  bridge  Network bridge with virbr0-nic
```
=> Bridge members lxd

src/daemon/daemon.cpp
In our first implementation of IP listing in the `list` command, we used to create a SSH session in the daemon to communicate with the instance. We moved later creating that session to the VirtualMachine class, but we forgot to remove the code in the daemon to create such session. As a result, we created two sessions each time we wanted to ask an instance for its IP's.
This PR just removes the spurious SSH session in the daemon.
=> Remove useless SSH session in the daemon

completions/bash/multipass, src/client/cli/cmd/list.cpp, src/client/cli/cmd/list.h, tests/test_cli_client.cpp, tests/test_daemon.cpp
So far we added in the RPC the ability to list instances without asking them for the IP. This saves precious time in situations on which the IP is not needed. In this PR, we add an option to the CLI to do this.
=> Add --no-ipv4 hidden parameter to list command

bors.toml
---
According to [this](https://bors.tech/documentation/), setting this supposedly keeps any child branches from being deleted when merging and deleting parent branches:
```
If turned on, and if delete_merged_branches is also turned on, then when a pull request is merged and its
base branch is about to be deleted, any other pull requests made against the base branch will be fixed up.
```
Thought we should give it a try.
=> [bors] Do not delete any child branches if parent branch is deleted

src/client/cli/cmd/list.cpp, src/client/gui/gui_cmd.cpp, src/daemon/daemon.cpp, src/rpc/multipass.proto
Test platforms:
Test plan:
- verify an instance launch
- confirm Multipass GUI running does not hog the CPU
=> Release 1.6.2

completions/bash/multipass
This PR implements bash autocompletion of the networks available in the host (listed with `multipass networks`). It pops in when the parameter `--network` is specified in the command line.
=> Networks bash completion

include/multipass/file_ops.h, include/multipass/platform.h, src/platform/platform_linux.cpp, src/platform/platform_unix.cpp, src/sshfs_mount/sftp_server.cpp, src/utils/CMakeLists.txt, src/utils/file_ops.cpp, tests/mock_file_ops.h, tests/mock_platform.h, tests/test_sftpserver.cpp
- Handle when NULL is returned when trying to allocate a handle in libssh
- Add much more logging for error conditions to account for the SFTP protocol's weak error reporting.
Fixes #1933, Fixes #1950
=> [sftp_server] Add better logging and handle failure conditions

include/multipass/virtual_machine_factory.h, src/daemon/CMakeLists.txt, src/daemon/daemon.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.h, src/platform/backends/shared/CMakeLists.txt, src/platform/backends/shared/base_virtual_machine_factory.cpp, src/platform/backends/shared/base_virtual_machine_factory.h, tests/lxd/test_lxd_backend.cpp, tests/mock_virtual_machine_factory.h, tests/test_base_virtual_machine_factory.cpp
Move cloud-init ISO image creation to the VirtualMachineFactory.
Have a base implementation in BaseVirtualMachineFactory.
Override in LXDVirtualMachineFactory as the ISO is not used with the LXD backend.
Fixes #1977
=> [virtual_machine_factory] Handle creating cloud-init ISO image

src/daemon/default_vm_image_vault.cpp
---
There was a question in https://github.com/canonical/multipass/pull/1931#discussion_r595008464 about whether returning an empty path in `vault::copy()` is the right thing to do.  This is done because of https://github.com/canonical/multipass/blob/afbea256e07cde725f32807adb11fb08782e1b97/src/daemon/default_vm_image_vault.cpp#L656-L657 where there may not be a kernel and initrd to copy.  It basically makes it a no-op on platforms that don't need that and is the easiest way to handle all cases.
=> [default_image_vault] Use new common copy util

tests/mock_singleton_helpers.h, tests/test_custom_image_host.cpp, tests/test_daemon.cpp, tests/test_ubuntu_image_host.cpp
Add and use singleton-mock public types, to facilitate injecting into test fixture classes (whose attributes need a fixed type).
=> Add helper types to singleton mocks

tests/extra_assertions.h, tests/libvirt/test_libvirt_backend.cpp, tests/linux/test_backend_utils.cpp, tests/lxd/test_lxd_backend.cpp, tests/lxd/test_lxd_image_vault.cpp, tests/qemu/test_dnsmasq_server.cpp, tests/qemu/test_qemu_backend.cpp, tests/test_custom_image_host.cpp, tests/test_image_vault.cpp, tests/test_platform_shared.cpp, tests/test_ubuntu_image_host.cpp, tests/test_utils.cpp
Another ancillary PR that I am using for bridging tests, providing a helper function to match against runtime_error messages, often needed with the extra assertions.
=> [test] Extract property matching for exceptions

CMakeLists.txt
The whole `-Weffc++` doesn't work for us because:
> When selecting this option, be aware that the standard library headers do not obey all of these guidelines; use grep -v to filter out those warnings.
Puzzling why `-Wnon-virtual-dtor` is not part of `-Wall` or even `-Wextra`. It built fine here and we could remove it if it started failing on external headers.
=> [cmake] Catch base classes with non-virtual dtors

.github/workflows/linux.yml
`!failure()` meant that cancelling a workflow was ignored.
=> [gha] react to workflow cancellation

.github/actions/build-params/action.yml, .github/workflows/integration.yml, .github/workflows/linux.yml, bors.toml
This will run the `Integration` workflow on four platforms:
- Linux / qemu
- Linux / LXD
- Windows / Hyper-v
- macOS / hyperkit
---
The functioning of this can be seen in https://github.com/Saviq/multipass/pull/1#issuecomment-815273255, as things need to be on main branches for dispatches to work.
=> [gha] add basic integration tests on bors runs

tests/daemon_test_fixture.h, tests/mock_daemon.h, tests/stub_cert_store.h, tests/test_daemon.cpp
Adds a daemon test fixture that can be used across multiple daemon command testing files.
Makes the MockDaemon class external.
=> [tests] Refactor daemon testing

src/daemon/daemon.cpp
---
```gcc
multipass/src/daemon/daemon.cpp:218:26: error: loop variable 'entry' is always a copy because the range of type 'QJsonArray' does not return a reference [-Werror,-Wrange-loop-analysis]
for (const auto& entry : record["extra_interfaces"].toArray())
^
multipass/src/daemon/daemon.cpp:218:14: note: use non-reference type 'QJsonValueRef'                                                                                                                     
for (const auto& entry : record["extra_interfaces"].toArray())
^~~~~~~~~~~~~~~~~~~
```
=> [daemon] fix invalid Json reference

include/multipass/top_catch_all.h, src/client/cli/main.cpp, src/client/gui/main.cpp, src/daemon/daemon_main.cpp, tests/test_top_catch_all.cpp
Generalize catch-all wrapper, to handle other sorts of callables, with different return types.
=> Generalize catch all

README.md
Homebrew deprecated the `brew cask` command a while ago (starting from [version 2.6.0](https://brew.sh/2020/12/01/homebrew-2.6.0/) in Dec 2020) and it was deleted recently in [version 3.0.6](https://github.com/Homebrew/brew/releases/tag/3.0.6).
=> [doc] Fix brew instructions in README

include/multipass/utils.h
Avoid timing out up to 1 second early. Prefer erring on the long side.
Found this out when reviewing #2046.
=> [util] Fix eager timeouts

include/multipass/cli/command.h, src/client/cli/cmd/animated_spinner.cpp, src/client/cli/cmd/animated_spinner.h, src/client/cli/cmd/launch.cpp, src/client/cli/cmd/mount.cpp, src/client/cli/cmd/start.cpp, src/daemon/daemon.cpp, tests/test_cli_client.cpp
Create logger for thread and slot during the VM creation.
Let the client's streaming callback handle log message printing since different operations such as launch may handle this differently.
Modify AnimatedSpinner to save the current message and start again using the saved current message.
Fixes #962, Fixes #459
=> [cli] Fix launch client logging messages

include/multipass/network_interface_info.h, include/multipass/virtual_machine_factory.h, src/daemon/daemon.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.h, src/platform/backends/shared/base_virtual_machine_factory.h, src/platform/backends/shared/linux/backend_utils.cpp, src/platform/backends/shared/linux/backend_utils.h, src/platform/platform_linux.cpp, tests/linux/test_backend_utils.cpp, tests/linux/test_platform_linux.cpp, tests/mock_virtual_machine_factory.h
Creates bridges if needed, uses existing otherwise.
=> Create and use bridge

include/multipass/constants.h, src/client/cli/cmd/launch.cpp, src/daemon/daemon.cpp, src/utils/settings.cpp, tests/test_cli_client.cpp, tests/test_daemon.cpp
---
For context: the other options we were considering (`--public`, `--exposed`) would not be intuitive to anyone. Even if "bridging" isn't strictly correct, e.g. on Hyper-V, that is the term other hypervisors use and people that know what it is will likely know from the get go what it's about. Even ourselves we refer to the feature as "bridging", because that's the prevalent term.
I decided against validating on `multipass set local.bridged-interface` as the given interface may not exist at that point in time for whatever reason, and on `launch` we'll communicate well what the problem is, if any.
=> [launch] add support for `--bridged` network

src/platform/backends/shared/base_vm_image_vault.h
I noticed MSVC complaining about this:
```
Z:\src\platform\backends\shared/base_vm_image_vault.h(63): warning C4834: discarding return value of function with 'nodiscard' attribute
```
=> Fix discard warning

include/multipass/file_ops.h, include/multipass/platform.h, include/multipass/url_downloader.h, src/network/url_downloader.cpp, src/utils/file_ops.cpp, src/workflow_provider/CMakeLists.txt, tests/CMakeLists.txt, tests/extra_assertions.h, tests/mock_file_ops.h, tests/mock_network.h, tests/test_url_downloader.cpp
This better handles trying to get cached network data if the network is unreachable.
Also adds unit testing to URLDownloader.
=> [network] Better handle network caching

src/platform/backends/qemu/dnsmasq_server.cpp, tests/qemu/test_dnsmasq_server.cpp
**_With respect to issue #1118:_**
Added a check on `DNSMasq` bootstrapping for `dnsmasq.hosts` file in the constructor. If absent, an empty file will be created in the `data_dir`.
=> [qemu] ensure `dnsmasq.hosts` exists

src/daemon/daemon.cpp, tests/mock_vm_image_vault.h, tests/test_daemon.cpp
Let exceptions that arise when creating a VM in the daemon constructor through. This avoids erasing instance data that could be recoverable and important for the user, but aborts the daemon since it can't honor its database, which would otherwise be out of sync. More robust approaches for particular causes can always added. Fixes #1658.
=> Fix eclipsing vms in ctor

3rd-party/submodule_info.md
Needed to avoid warning in newer clangs:
```
`ISO C++ requires the name after '::~' to be found in the same scope as the name before '::~' [-Werror,-Wdtor-name]
sg::detail::scope_guard<Callback>::~scope_guard() noexcept´
```
=> [3rd-party] Bump scope_guard to v1.0.0

src/platform/backends/lxd/lxd_virtual_machine.cpp
This should help with integration tests that are under load.
=> [lxd] Increase instance creation timeout to 10 minutes

include/multipass/timer.h, src/utils/timer.cpp, tests/test_timer.cpp
Adds a getter function for current Timer state for better testing Timer state expectations.
Relax timeouts in some tests to improve reliability.
=> Improve Timer test reliability part deux

src/daemon/ubuntu_image_host.cpp, tests/test_data/daily/daily_manifest.json, tests/test_ubuntu_image_host.cpp
It's possible that the same full hash will exist in both the release and daily remotes, so don't reject it.
Fixes #2072
=> [ubuntu_image_host] Only reject multiple hash matches if not a full hash

src/client/cli/cmd/launch.cpp, tests/test_cli_client.cpp
**_Issue #2045:_**
I have added validation for alpha, alphanumeric, and natural number valued inputs for this option in the `launch` command.
=> [cli] Validate CPU Parameter in Launch

src/client/cli/formatter/table_formatter.cpp, tests/test_output_formatter.cpp
**_Issue #2108:_**
Should output `--` when no active mounts are available in conformity with `table` output for other unavailable information:
https://github.com/surahman/multipass/blob/5f9ba4bd6db5fa31f59cbae0fbbf8fb3556e2d29/tests/test_output_formatter.cpp#L431-L452
The other formatters seem to already handle this situation. `YAML` outputs its `null` indicator as a tilde `~` character, `JSON` will create a `null` sub-record, and  `CSV` will output an empty field.
=> [cli] Info For No Active Mounts

snap/snapcraft.yaml
To be able to read the host's os-release.
=> [snap] Add system-observe interface

include/multipass/file_ops.h, include/multipass/platform.h, include/multipass/poco_zip_utils.h, include/multipass/url_downloader.h, include/multipass/utils.h, src/network/url_downloader.cpp, src/platform/platform_linux.cpp, src/platform/platform_unix.cpp, src/utils/file_ops.cpp, src/utils/poco_zip_utils.cpp, src/utils/utils.cpp, tests/mock_file_ops.h, tests/mock_network.h, tests/mock_platform.h, tests/mock_poco_zip_utils.h, tests/mock_utils.h
Add missing `const`s to singleton methods. I left a couple of conceptual exceptions untouched, like `Utils::exit` or `Settings::set`. The latter would allow caching without changing the interface.
=> Singleton consts

src/daemon/daemon.cpp, tests/test_daemon.cpp
This PR fixes https://github.com/canonical/multipass/issues/1953.
The check assumed the remote to be `release` when the user did not specify one. This is not true, because there are images which do not accept a remote name (such as `core`). This worked but it was confusing in the code. It was fixed to check separately such images (called 'remoteless images' in the code). The error message was corrected as well, not showing a remote name if the user did not specify one.
=> Fix non-bridging check for images

include/multipass/constants.h, include/multipass/platform.h, src/client/cli/cmd/launch.cpp, src/daemon/daemon.cpp, src/platform/platform_linux.cpp, src/utils/settings.cpp, tests/test_cli_client.cpp, tests/test_daemon.cpp
---
Documentation updated at: https://multipass.run/docs/set-command?#local.privileged-mounts
=> [daemon] add `local.privileged-mounts` setting

src/platform/backends/shared/base_virtual_machine_factory.cpp, src/platform/backends/shared/base_virtual_machine_factory.h, tests/test_base_virtual_machine_factory.cpp
When creating a new bridge, update the internal host-networks reference, so that the new bridge is considered for ensuing interfaces. Fixes #2159
=> Fix double bridging

src/daemon/daemon.cpp, tests/test_daemon.cpp
Perform a hypervisor health check before inspecting networks. This is
required in the particular case of LXD because `mp::lxd_request` assumes
that the "multipass" project already exists, and that project is created
in the health check. More generally, it makes sense to require a healthy
backend before asking it for the network inspection. Fixes #2139.
=> [daemon] Perform a health check on `networks`

completions/bash/multipass
This PR adds bash completions for the options `--bridged` and `--network bridged` of the `launch` command.
=> Complete bridge options in `launch` command

src/daemon/daemon.cpp, tests/test_daemon.cpp
=> [daemon] Fix regression in Workflows-based launches

tests/qemu/test_firewall_config.cpp
Clang is picky with lambda captures.
=> Fix compilation with Clang 12 on Linux.

src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, tests/lxd/test_lxd_backend.cpp
Only mention snap connections if running in the multipass snap.
=> [lxd] Make snap mention conditional in error msg

src/client/gui/gui_cmd.cpp
**_Issue #2188:_**
Introducing a check for signal connection to the GUI when an update is available.
We could also, potentially, do the following and move the `disconnect` from the `else` statement out to before the update check - which is what you suggested. It is the same code as the original, but just refactored:
```c++
void cmd::GuiCmd::update_about_menu()
{
auto reply = version_future.result();
about_client_version.setText("multipass version: " + QString::fromStdString(multipass::version_string));
about_daemon_version.setText("multipassd version: " + QString::fromStdString(reply.version()));
QObject::disconnect(&tray_icon, &QSystemTrayIcon::messageClicked, 0, 0);
tray_icon_menu.removeAction(&update_action);
if (update_available(reply.update_info()))
{ …
```
=> [gui] Update available multiple msgs bugfix

include/multipass/logging/client_logger.h, src/daemon/daemon.cpp, src/daemon/daemon.h, tests/common.h, tests/mock_daemon.h, tests/test_daemon.cpp
This continues with the approach in #2205 (replacing it) to enable `Daemon` testing by calling its public slots directly, providing a `MockServerWriter`. To allow that, slot signatures are changed to receive a `ServerWriterInterface` param in place of the concrete `ServerWriter` implementation.
=> Daemon testing with RPC mocking

src/daemon/daemon_rpc.cpp
This addresses the 1 second each daemon test has been taking on Windows. Basically that was how much time we were waiting in the check for an existing daemon. I'm not sure why we don't see the same on other platforms, but I suppose it fails immediately when using unix sockets.
BTW, GRPC itself already logs an error when trying to create the second server, mentioning:
> Only one usage of each socket address (protocol/network address/port) is normally permitted
I am not sure if that's a default message whenever it can't open the port, or if it somehow knows that it is being used for another server of its own. I looked for some sort of API to get that error info, but I didn't find any.
=> Fix slow daemon tests on Windows

src/daemon/daemon.cpp
Since we can't throw anything out of `QTimer` (qt slot), we need to catch all exceptions types. Fixes #2197
=> [daemon] Handle exceptions starting VMs in ctor

.github/ISSUE_TEMPLATE/config.yml
In the GitHub issue template, there was a link to join to `#multipass` on FreeNode. Since we moved to Libera.Chat, this PR reflects it.
=> Update IRC network

completions/bash/multipass
This PR adds completion for the Multipass commands `alias`, `unalias` and `aliases`.
=> Bash completions for the aliases features

completions/bash/multipass
Fixes https://github.com/canonical/multipass/issues/2237.
Bash 3 complains when an array is indexed with a negative number. This PR checks for negative subindices where they can appear, so we can use the script with older versions.
=> Fix bash completions for old versions

snap/snapcraft.yaml
Fix #2258 by enabling [Qt to work around limited appindicator support for icons over DBus (IIUC)](https://code.woboq.org/qt6/qtbase/src/gui/platform/unix/dbustray/qdbustrayicon.cpp.html#_ZN13QDBusTrayIcon8tempIconERK5QIcon). To that end, plug `system-observe` to allow inspecting running processes.
The icon is cropped, but at least it shows now.
=> [gui] Add system-observe plug

tests/fake_alias_config.h, tests/json_utils.cpp, tests/test_alias_dict.cpp
In a couple of places, plus an old one which fell through the cracks. In order to get us pretty printers without breaking ODR. Related to #2142 .
=> [tests] Include common.h instead of gmock, gtest

include/multipass/file_ops.h, include/multipass/platform.h, include/multipass/settings.h, src/client/cli/cmd/set.cpp, src/platform/platform_linux.cpp, src/utils/file_ops.cpp, src/utils/qsettings_wrapper.h, src/utils/settings.cpp, src/utils/wrapped_qsettings.h, tests/CMakeLists.txt, tests/common.h, tests/linux/test_platform_linux.cpp, tests/mock_file_ops.h, tests/mock_platform.h, tests/test_settings.cpp
Finally get our `Settings` tested. At least the parts we know will have to remain (even if moved to handlers).
Depends on #2277.
=> Test settings

src/client/cli/cmd/CMakeLists.txt
PLATFORM_COMMANDS is nowhere to be found.
=> [cmake] Remove obsolete variable

tests/test_daemon.cpp
It is already covered by `test_get` above.
=> [tests] Remove superfluous `get` test

tests/CMakeLists.txt
Relying on gRPC's submodule does not give us the control over googletest
versions we'd like.
Let's "[Live at head](https://github.com/google/googletest#live-at-head)" instead, using CMake's FetchContent.
Based on [GTests's Quickstart: Building with CMake](https://google.github.io/googletest/quickstart-cmake.html).
=> [tests] move to upstream googletest

src/sshfs_mount/sshfs_mount.cpp
Avoids an exception reaching the thread boundary and aborting the whole process. Addresses #2390.
=> [sshfs] Catch exceptions in the sftp thread

3rd-party/CMakeLists.txt
Did its job, no longer needed :)
=> [cmake] Drop needless grpc compilation option

src/daemon/daemon.cpp
This will try to ensure the backend is set up before launching any instances.
Fixes #2401
=> [daemon] Call hypervisor_health_check() in ctor

src/platform/backends/qemu/qemu_virtual_machine.cpp
Updating our qemu branch to v6.2.0 fixes suspend on M1.
Fixes #2308
=> [backends/qemu] Allow suspending instance on Apple M1

include/multipass/cli/prompters.h, include/multipass/terminal.h, src/client/cli/cmd/register.cpp, src/client/cli/cmd/set.cpp, src/client/common/prompters.cpp, src/platform/console/CMakeLists.txt, src/platform/console/unix_terminal.cpp, src/platform/console/unix_terminal.h, tests/mock_terminal.h, tests/stub_terminal.h, tests/test_cli_client.cpp, tests/test_cli_prompters.cpp, tests/unix/CMakeLists.txt, tests/unix/mock_libc_functions.cpp, tests/unix/mock_libc_functions.h, tests/unix/test_unix_terminal.cpp
This allows entering the passphrase for `set local.passphrase` and `register` at the terminal without echo.
=> [prompter] Add echoless passphrase prompt

src/daemon/daemon.cpp, src/utils/settings.cpp
This will instead unset the passphrase.
Fixes #2410
=> [settings] Do not generate a hash for an empty passphrase

src/daemon/daemon.cpp
SnapD sends that to the store, so we could use that to filter installed snaps through that.
=> [cloud-init] set `cloud-name` to `multipass`

src/client/cli/cmd/exec.cpp, tests/test_cli_client.cpp
The error message when launching an alias using `multipass` was incorrect. This PR fixes https://github.com/canonical/multipass/issues/2317 by improving the error message.
=> Fix error message when not using `--` for alias arguments

snap/snapcraft.yaml
=> [snap] drop packaged libssh

src/client/common/client_common.cpp
This is due to this log message being called before the logger is actually set up to
match the passed in verbosity.
Fixes #2499
=> [client] Remove logging message that is always printed

tests/linux/test_platform_linux.cpp, tests/mock_platform.h, tests/qemu/mock_qemu_platform.h
This is to get rid of all of the "Uninteresting calls" when tests run.
---
This is needed as a prerequisite for #2485.
=> [tests] Fix "Uninteresting mock function call" messages

src/client/common/client_common.cpp
These also get called before client sets up the proper logger.
Fixes #2499
=> [client/common] Remove additional trace logging around cert discovery

include/multipass/constants.h, include/multipass/settings/settings.h, include/multipass/settings/settings_handler.h, src/client/cli/cmd/common_cli.cpp, src/client/cli/cmd/common_cli.h, src/client/cli/cmd/get.cpp, src/client/cli/cmd/get.h, src/client/cli/cmd/remote_settings_handler.cpp, src/client/cli/cmd/set.cpp, tests/test_cli_client.cpp, tests/test_remote_settings_handler.cpp
Expand the `get` command in a couple of ways:
1. Expand the command's syntax to
- accept multiple keys;
- accommodate wildcards instead of concrete keys.
2. Add a `--keys` option, to obtain available settings at any given time;
1. restrict the output to the specified single key, if given.
As discussed, parts of the implementation are postponed for now (so we can prioritize instance mod). Step 1 above opens the command for future support of multiple keys and wildcards (which are meant to work with and without the `--keys` flag) but stops short of implementing that support for now. Step 2 is implemented in a way that will accommodate the same wildcard arg(s) for `--keys`, but interprets only a single key arg at the moment. That's a particular case of wildcard matching which, although not …
=> Get `--keys` and prepare the ground for wildcards

include/multipass/exceptions/invalid_memory_size_exception.h, include/multipass/memory_size.h, include/multipass/virtual_machine.h, src/daemon/instance_settings_handler.cpp, src/daemon/vm_specs.h, src/network/local_socket_reply.cpp, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/lxd/lxd_virtual_machine.h, src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.h, src/utils/memory_size.cpp, tests/CMakeLists.txt, tests/test_instance_settings_handler.cpp, tests/test_memory_size.cpp
Implements instance modification through `set` and inspection through `get`.
Fixes #1158, Fixes #62
---
=> Instance mod

src/daemon/daemon.cpp
This allows any initialization of any hypervisor specific primitives to be complete
before any existing instances are instantiated.
Fixes #2519
=> [daemon] Move hypervisor health check sooner in ctor

src/daemon/daemon.cpp, tests/test_daemon.cpp
It was on the non-bridging remote list. Since we don't support it anymore, it doesn't make sense for it to stay there.
=> [daemon] Remove `snapcraft:core` remote

include/multipass/sshfs_mount/sftp_server.h, src/sshfs_mount/sftp_server.cpp, tests/test_sftpserver.cpp
The reverse id mapping function returned `-1` if the current user was not found on the reverse mappings. Since the folder is created as root, when `0` did not exist in the reverse mappings the new folder retained the `0` id, because `-1` makes `chown` to keep the owner.
We use now the user/groups id's of the parent folder if the current user is not found on the reverse mappings. This was the behavior before implementing reverse id mapping.
Fixes https://github.com/canonical/multipass/issues/2553.
=> Fix ownership of a folder created under a mount

src/client/common/client_common.cpp
In the logic to figure out if a cert has been accepted by the daemon, if the client cannot
establish a connection and get status if it's authenticated or not, it should just throw.
This will avoid the client from generating a new cert until communication with the daemon
is established.
Fixes #2552
=> [client/common] Throw when unable to connect to daemon

src/client/cli/cmd/launch.cpp, src/client/cli/cmd/launch.h, src/client/cli/cmd/mount.cpp, tests/test_cli_client.cpp
This adds the `--mount` option to the `launch` command. The syntax is `--mount <local-path>[:<instance-path>]`. If `<instance-path>` is omitted, it is the same as the absolute path of `<local-path>`. This option can be specified multiple times e.g. `multipass launch --mount /path/one --mount /path/two:two`.
In the case of the primary instance, which mounts the user's home directory to the `Home` directory inside the instance (`/home/user => Home`), if we specify the option `--mount /some/path:Home`, it will override the default mounting route of the primary instance (`/some/path => Home`).
fix #833
=> [cli] add mount option on launch command

src/ssh/sftp_client.cpp, tests/c_mock_defines.cmake, tests/mock_sftp.cpp, tests/mock_sftp.h, tests/test_sftp_client.cpp
This PR allow the `transfer` command to have a directory as the target, either locally or on an instance.
fix #1165
=> [cli][transfer] allow for remote target to be a directory

src/client/cli/cmd/exec.cpp, tests/test_cli_client.cpp
The `--no-map-working-directory` flag at alias creation did not work. We fix it, as well as an incorrect test which avoided us to detect the problem earlier.
=> [cli] Fix mapping working directory.

src/client/cli/argparser.cpp
`--help-all` is handled by Qt and does not add any output to --help.
Fixes #2635.
=> [cli] Remove --help-all option

completions/bash/multipass, src/client/cli/cmd/launch.cpp, tests/daemon_test_fixture.h, tests/test_cli_client.cpp, tests/test_daemon.cpp
This PR changes the long option for memory allocation of the `launch` command from `--mem` to `--memory`. `--mem` is still supported for backwards compatibility, but will not be displayed in the help text. If both options are used, `--memory` will take precedence.
Fixes #2490 for original change request.
=> Change long option

README.md, src/client/cli/formatter/csv_formatter.cpp, src/client/cli/formatter/json_formatter.cpp, src/client/cli/formatter/table_formatter.cpp, src/client/cli/formatter/yaml_formatter.cpp, src/daemon/daemon.cpp, src/rpc/multipass.proto, tests/test_output_formatter.cpp
This PR adds a CPU count to the `info` command. Displayed CPU count is based on the number of processing units.
Sample output:
```
ubuntu:~$ multipass info foo
Name:           foo
State:          Running
IPv4:           192.168.1.1
Release:        Ubuntu 20.04.4 LTS
Image hash:     692406940d6a (Ubuntu 20.04 LTS)
CPU(s):         1
Load:           0.00 0.00 0.00
Disk usage:     1.4G out of 4.7G
Memory usage:   137.2M out of 976.8M
Mounts:         --
```
Fixes #1804 for original change request.
=> Add cpu count to info cmd

.github/ISSUE_TEMPLATE/bug_report.md
Currently we often need to follow up with a request for this. Better get it from the get go.
=> Request driver in bug report template

include/multipass/constants.h, include/multipass/simple_streams_manifest.h, src/daemon/daemon_config.cpp, src/daemon/daemon_init_settings.cpp, src/daemon/ubuntu_image_host.cpp, src/daemon/ubuntu_image_host.h, src/simplestreams/simple_streams_manifest.cpp, tests/path.cpp, tests/path.h, tests/test_data/invalid_image_mirror/releases/multiple_versions_manifest.json.in, tests/test_data/invalid_image_mirror/releases/streams/v1/index.json.in, tests/test_data/valid_image_mirror/releases/multiple_versions_manifest.json.in, tests/test_data/valid_image_mirror/releases/streams/v1/index.json.in, tests/test_data/valid_outdated_image_mirror/releases/multiple_versions_manifest.json.in, tests/test_data/valid_outdated_image_mirror/releases/streams/v1/index.json.in, tests/test_simple_streams_manifest.cpp, tests/test_ubuntu_image_host.cpp
Hi team, I would like to present a PR for issue: https://github.com/canonical/multipass/issues/717
**Feature: mirror of cloud images**
By setting `local.image.mirror`, users can download images from mirror sites instead of the official one. The feature can be disabled by leaving the config empty.
**Implementation**
When updating product versions, it will choose the manifest from mirror site if possible. Since mirror sites is syncing with official site periodically, the latest version in official site may not exist in mirror sites.
Only if the content of a version is *identical* to the same version from official site, it will be updated into the `manifests` cache of `UbuntuVMImageHost` instance.
=> Download image from mirror site

src/client/cli/formatter/csv_formatter.cpp, src/client/cli/formatter/json_formatter.cpp, src/client/cli/formatter/yaml_formatter.cpp, tests/test_output_formatter.cpp
Fixes `list` output so that all formats output `release` + `image` for the `release` field. eg.
```
ubuntu:build$ multipass list --format yaml
foo:
- state: Running
ipv4:
- 10.3.183.81
release: Ubuntu 20.04 LTS
persuasive-ruff:
- state: Deleted
ipv4:
[]
release: Not Available
```
Fixes #2464
=> Fix inconsistent `list` output

tests/CMakeLists.txt, tests/daemon_test_fixture.cpp, tests/daemon_test_fixture.h, tests/test_daemon.cpp, tests/test_daemon_authenticate.cpp, tests/test_daemon_start.cpp, tests/unix/test_daemon_rpc.cpp
The `Daemon*` tests take lots of RAM to compile and part of it is due to all of the method definitions being in `daemon_test_fixture.h`.  This moves most of the definitions to a `daemon_test_fixture.cpp` compilation unit so each `Daemon` test file doesn't have to compile everything in DaemonTestFixture every time.
=> [tests] Add a DaemonTestFixture compilation unit

src/platform/backends/lxd/lxd_virtual_machine.cpp, tests/lxd/test_lxd_backend.cpp
LXD instances do not update instance state within multipass when they are externally shutdown (ie. `sudo poweroff` within the instance) and so will reboot them when the daemon restarts. To fix this, we force multipass to update the state of LXD instances before shutting down to ensure that they are put into the correct state when multipass reboots.
Fixes #2672
=> Fix LXD not updating state

src/client/cli/cmd/launch.cpp
Passing a process substitution to `--cloud-init` didn't work since it was checking if it received a regular file, but a process substitution returns a named pipe. Unfortunately QT doesn't have a way to check if a path is a named pipe, but fortunately `std::filesystem` does.
fix #1589
=> Allow using process substitution for cloud-init file

.github/workflows/integration.yml
With the new Mini, we need more context than just `vmware-fusion` in the
job queue. For now Windows is left alone.
=> ci: rework job-queues for new format

src/platform/backends/lxd/lxd_virtual_machine.cpp, tests/lxd/test_lxd_backend.cpp
Ignore `LXDNotFoundException` which is thrown when an instance has been purged. This isn't a particularly nice fix, but seems to be the simplest without a complete refactor of the LXD backend. Another potential way of accounting for this situation could be through the use of the `update_shutdown_status` boolean, but I felt like that would just add unnecessary complexity to an already complex state machine.
Fixes #2714
=> Ignore LXDNotFoundException on purge

src/daemon/daemon.cpp, src/platform/backends/qemu/linux/dnsmasq_server.cpp, src/platform/backends/qemu/linux/dnsmasq_server.h, src/platform/backends/qemu/linux/qemu_platform_detail.h, src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp, src/platform/backends/qemu/qemu_platform.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, tests/qemu/linux/mock_dnsmasq_server.h, tests/qemu/linux/test_dnsmasq_server.cpp, tests/qemu/linux/test_qemu_platform_detail.cpp, tests/qemu/mock_qemu_platform.h
This PR makes it so that when a Linux QEMU instance reboots, it checks the `dnsmasq.leases` file for leases that have the same MAC address as the instance but under a different host name and releases them. This is needed for core20 and core22, which change host names during launching and get the daemon confused about which IP is the correct one.
It also makes sure that when an instance is done rebooting, it has a `Running` state, since those instances were getting stuck in a `Restarting` state.
fix #2690
=> Make core 20/22 not change IP address over reboot

src/client/gui/gui_cmd.cpp
This PR fixes the text shown in the gui when no primary instance is found.
Fixes #1241
=> [gui] not reacting to primary instance being purged

include/multipass/file_ops.h, src/client/cli/cmd/restart.cpp, src/daemon/daemon.cpp, src/sshfs_mount/sshfs_mounts.cpp, src/utils/file_ops.cpp, tests/linux/test_backend_utils.cpp, tests/mock_file_ops.h, tests/test_alias_dict.cpp, tests/test_cli_client.cpp, tests/test_sshfsmounts.cpp, tests/test_utils.cpp
This PR add a check to make sure that the given directory exists before attempting to mount it. If the directory is not found, the host and target directories will be removed from the database.
Fixes #1677
=> sshfs infinitely looping on missing mount directory

src/sshfs_mount/sshfs_mounts.cpp, tests/test_sshfsmounts.cpp
This PR adds logic to force a process to wait until the process has exited before continuing. If the process does not terminate within the specified amount of time, kill it.
Fixes #1132
=> sshfs not cleanly shutdown when stopping an instance

completions/bash/multipass, src/ssh/sftp_client.cpp, tests/c_mock_defines.cmake, tests/mock_sftp.cpp, tests/mock_sftp.h, tests/test_sftp_client.cpp
This PR fixes a bug in the `transfer -r` command that did not set the copied directories permissions accordingly
=> Recursive transfer dir perms

include/multipass/file_ops.h, include/multipass/ssh/sftp_client.h, include/multipass/ssh/sftp_utils.h, src/client/cli/cmd/transfer.cpp, src/ssh/sftp_client.cpp, src/ssh/sftp_utils.cpp, src/utils/file_ops.cpp, tests/mock_file_ops.h, tests/mock_sftp_client.h, tests/mock_sftp_utils.h, tests/test_file_ops.cpp, tests/test_sftp_client.cpp, tests/test_sftp_utils.cpp
This PR adds the `-p|--parents` option to the `transfer` command, to create any missing parent directories
fix #1434
=> Transfer p flag

include/multipass/utils.h, src/sshfs_mount/sshfs_mount.cpp, src/utils/utils.cpp, tests/test_base_virtual_machine.cpp
Move common ssh functions to `utils.cpp` This refactor is needed for adding performance mounts.
=> [refactor] Move common ssh functions to `utils.cpp`

src/daemon/custom_image_host.cpp, src/daemon/default_vm_image_vault.cpp, tests/test_custom_image_host.cpp
The dates used by the image vault and custom image host are formatted in the system locale. This PR formats them using the C locale for consistency.
fix #2442
=> Format dates in image vault and custom image host in c locale

.github/workflows/linux.yml
Having this resulted in 4 copies of the same file in my work with Mir…
While here, upgrade the action.
Signed-off-by: Michał Sawicz <michal.sawicz@canonical.com>
=> ci: drop `**` from ccache `path:`

src/utils/memory_size.cpp
Ignore leading and trailing whitespace in a string passed to the memory sizer.
=> Ignore leading and trailing whitespace in strings for memory sizes

.github/workflows/integration.yml
Windows stucks a \0a\0d at the end. Because why not.
Signed-off-by: Michał Sawicz <michal.sawicz@canonical.com>
=> integration: fix getting driver

src/client/cli/cmd/mount.cpp, tests/test_cli_client.cpp
The client specified default maps only when both UID, GID maps were not specified. It failed in case one and only one of the two was specified.
Fixes #2801.
=> Fix default UID/GID mappings.

include/multipass/file_ops.h, src/client/cli/cmd/launch.cpp, src/utils/file_ops.cpp, tests/mock_file_ops.h, tests/test_cli_client.cpp, tests/test_sftpserver.cpp
Verify client source directories before launching an instance and fail the launch if they are invalid.
Fixes #2817
=> Verify launch mount source path before launching

src/daemon/daemon.cpp
Replace backticks in shell commmands with posix compliant `$()`.
Fixes #2819
=> remove backticks in multipass info

src/client/cli/cmd/launch.cpp, src/client/common/client_common.cpp, tests/test_cli_client.cpp
When launching an instance with a duplicate name, the multipass cli will by default print out the serialized binary string of the protobuf message resulting in extra newlines appearing in the console. 
Ex:
```
scott:~$ multipass launch -n foo                                            
Launched: foo                                                                   
scott:~$ multipass launch -n foo
launch failed: instance "foo" already exists                                    
scott:~$  
```
After changes:
```
scott:~$ multipass launch -n foo
launch failed: instance "foo" already exists                                    
Invalid instance name supplied: foo
scott::~$
```
=> Catch `INSTANCE_EXISTS` error from daemon

src/process/qemuimg_process_spec.cpp
This is needed so Multipass can still create vm instances under snap confinement after changing `MULTIPASS_STORAGE`.
=> Update apparmor profile for qemu

src/daemon/daemon.cpp
Replace `lsb_release` bash command with a readout of `/etc/os-release`
Fixes #2799
=> Replace source for os release for `multipass info`

src/settings/persistent_settings_handler.cpp, src/settings/wrapped_qsettings.h, tests/mock_qsettings.h, tests/test_persistent_settings_handler.cpp
Be robust to bad setting values read from disk, by logging the occurrence, resetting, and returning the default.
The lazy approach taken here reuses `SettingSpec::interpret`, but it imposes a new constraint on it: it needs to be able to validate already "interpreted" (marshalled) settings. I want to see how this goes on different platforms and integration tests. 
If this works, we can rely on it to reset `hyperkit` to `qemu` once the former is gone (because the latter will be the default by then). Otherwise, we could try to finally move to a marshall/unmarshall scheme, or just tackle the hyperkit case with dedicated code.
=> Handle bad settings read from disk

src/client/cli/cmd/transfer.cpp, tests/test_cli_client.cpp
=> [cli/transfer] don't treat windows absolute paths as instance:path pair

src/platform/backends/qemu/linux/dnsmasq_process_spec.cpp, src/platform/backends/qemu/linux/dnsmasq_server.cpp, src/platform/backends/qemu/linux/dnsmasq_server.h, src/platform/backends/qemu/linux/qemu_platform_detail.h, src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp, src/platform/backends/qemu/qemu_platform.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, tests/qemu/linux/mock_dnsmasq_server.h, tests/qemu/linux/test_dnsmasq_process_spec.cpp, tests/qemu/linux/test_dnsmasq_server.cpp, tests/qemu/linux/test_qemu_platform_detail.cpp, tests/qemu/mock_qemu_platform.h
This is a follow-up to #2717 which required a more convoluted fix to get the correct IP address based only on the MAC address of an instance. In a newer version of `dnsmasq` available in core22, there is the `--dhcp-ignore-clid` option which does just that.
=> Use `--dhcp-ignore-clid` option for `dnsmasq`

src/sshfs_mount/sshfs_mount_handler.cpp
This avoids the case when the port may not be available yet or chages.
Fixes #2904
=> [mount_handler/sshfs] Get SSH port when starting the mount

src/client/gui/gui_cmd.cpp
The tray icon application is not aware if there are multiple instances of itself running. This PR adds a lock file to the app in order to make sure that only one instance of the app is allowed to start.
fix #2900
=> [gui] allow only one tray icon app to run

include/multipass/default_vm_blueprint_provider.h, include/multipass/platform.h, include/multipass/vm_blueprint_provider.h, src/blueprint_provider/default_vm_blueprint_provider.cpp, src/daemon/daemon.cpp, src/daemon/default_vm_image_vault.cpp, src/platform/platform_linux.cpp, tests/mock_platform.h, tests/mock_vm_blueprint_provider.h, tests/stub_vm_blueprint_provider.h, tests/test_blueprint_provider.cpp, tests/test_daemon.cpp, tests/test_data/blueprints/v2/test-blueprint1.yaml
This introduces the ability to launch (only in Linux) a Blueprint defined on a YAML file. The syntax for doing so is the same as when launching a local image:
```
multipass launch file://blueprint.yaml
```
This works on top of the interface of Blueprints v2. Private bits are in https://github.com/canonical/multipass-private/pull/485.
=> Launch Blueprints from file

include/multipass/mount_handler.h, include/multipass/sshfs_mount/sshfs_mount_handler.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/qemu/qemu_mount_handler.cpp, src/platform/backends/qemu/qemu_mount_handler.h, src/sshfs_mount/sshfs_mount_handler.cpp, tests/qemu/test_qemu_mount_handler.cpp, tests/test_sshfs_mount_handler.cpp
This PR modifies the mount handlers by adding specialized checks for whether a mount is still active or not. It also makes use of the way in which some backends can notify the daemon when a VM reboots, so that the mounts can also be stopped. This allows the mount handlers to have a consistent state when a VM is shut down internally and, in those specific backend cases, when rebooted internally.
fix #2917
=> Detect mount active state

include/multipass/cli/client_platform.h, src/client/cli/CMakeLists.txt, src/client/cli/client.cpp, src/client/cli/cmd/animated_spinner.cpp, src/platform/client/client_platform.cpp, tests/CMakeLists.txt, tests/test_common_callbacks.cpp
Use [ANSI escape characters](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797) to manipulate cursor and overwrite test in the cli. 
---
public side of [pr512](https://github.com/canonical/multipass-private/pull/512)
Fixes #958
=> [cli] Remove padded chars in cli output

src/daemon/daemon.cpp
Increase the timeout of the image repair step of the migration of Hyperkit instances to QEMU, to 5 minutes. Fixes https://github.com/canonical/multipass/issues/2938.
=> [daemon] Increase timeout in Hyperkit migration

.gitmodules, 3rd-party/CMakeLists.txt, 3rd-party/submodule_info.md
Remove gRPC as a git submodule and be explicit about what gRPC submodules to fetch.
Fixes #2927
=> [build] Use FetchContent for getting gRPC

3rd-party/CMakeLists.txt, CMakeLists.txt
> We added a new way to fetch the grpc module and it uses the GIT_SUBMODULES_RECURSE directive for [FetchContent_Declare](https://cmake.org/cmake/help/latest/module/ExternalProject.html) and unfortunately, that directive was made available starting with cmake version 3.17.
Fixes #2959
=> Update min cmake version

src/client/cli/cmd/animated_spinner.cpp, tests/test_common_callbacks.cpp
Add an extra ASCII escape character that moves the cursor up 0 lines. This stops newlines from appearing in a new/empty terminal when running a command that uses the animated spinner. Don't ask exactly why this works, but it does :shrug: 
---
Fixes #2953
=> [cli] Stop erroneous newlines from appearing in empty terminal

include/multipass/default_vm_blueprint_provider.h, include/multipass/exceptions/image_vault_exceptions.h, include/multipass/vm_blueprint_provider.h, src/blueprint_provider/default_vm_blueprint_provider.cpp, src/client/cli/cmd/find.cpp, src/client/cli/formatter/csv_formatter.cpp, src/client/cli/formatter/json_formatter.cpp, src/client/cli/formatter/table_formatter.cpp, src/client/cli/formatter/yaml_formatter.cpp, src/daemon/daemon.cpp, src/daemon/default_vm_image_vault.cpp, src/platform/backends/lxd/lxd_vm_image_vault.cpp, src/platform/backends/shared/base_vm_image_vault.h, src/rpc/multipass.proto, tests/lxd/test_lxd_image_vault.cpp, tests/mock_vm_blueprint_provider.h, tests/stub_vm_blueprint_provider.h, tests/test_blueprint_provider.cpp, tests/test_cli_client.cpp, tests/test_daemon.cpp, tests/test_daemon_find.cpp, tests/test_image_vault.cpp, tests/test_output_formatter.cpp
This PR adds the flags `--only-images` and `--only-blueprints` which modifies the behavior of `multipass find` causing it to display only images or blueprints respectively. Additionally, when no flag is specified, `multipass` will make the distinction between images and blueprints by separating them. Sample output is as follows:
```
scott:build-debug$ bin/multipass find
Image                       Aliases           Version          Description
snapcraft:core18            18.04             20201111         Snapcraft builder for Core 18
snapcraft:core20            20.04             20210921         Snapcraft builder for Core 20
snapcraft:core22            22.04             20220426         Snapcraft builder for Core 22
snapcraft:devel                               20220808         Snapcraft …
```
=> Discern between images and blueprints in `multipass find`

src/client/gui/gui_cmd.cpp
Create the AppDataLocation dir for the Multipass GUI if it does not yet exist. Keep `first_run`, in case the directory could be created some other way. Fixes #2975.
=> [gui] Fix creating first_run file if dir not there

3rd-party/libssh/CMakeLists.txt, src/ssh/ssh_session.cpp
Fixes #2754
In the orginal code, when multipass `class SSHSession` is being constructed, he always calls libssh function `int ssh_connect(ssh_session session)`. That function by default always tries to load a configuration file either from user or from the system (/etc/ssh/ssh_config ). Setting the option SSH_OPTIONS_PROCESS_CONFIG to false makes him to skip that.
=> Do not read global SSH config

src/daemon/daemon.cpp
Edit how disk usage is gotten so that it outputs the correct in core instance as well as regular ubuntu images. The command now takes the output from `fdisk -l` and courses references the devices found in `df`. Instead of returning the size of the root directory, `/`, the device marked as `Linux filesystem` in `dfisk` will be taken from `df`.
Fixes #1245
=> [daemon] Edit disk usage info

src/client/cli/cmd/launch.cpp
When launching, do not contact the daemon to find whether mounts are enabled - and do not complain if they are not - unless a mount is actually required. Compare petenv name with computed vm name. Fixes #2981.
=> [cli] Only check for enabled mounts in `launch` if needed

include/multipass/file_ops.h, src/ssh/sftp_client.cpp, src/utils/file_ops.cpp, tests/mock_file_ops.h, tests/test_sftp_client.cpp
The SFTP client opened files in text mode, which made the transfer of binary files on Windows fail. This PR makes the SFTP client open files in binary mode.
fix #2990
=> [sftp] open local files in binary mode

src/client/cli/cmd/snapshot.cpp, tests/test_cli_client.cpp
Turn name into an option in `snapshot` and allow `-c` for comments.
=> tweak snapshot cmd

src/daemon/daemon.cpp, tests/test_daemon_find.cpp
fixed #2957
---
The original behavior is: 
```
./multipass find nonsense:22.10 # the case where the search string is a valid image name
No images or blueprints found.
./multipass find nonsense:22.10 --only-images
No images found.
./multipass find nonsense:22.10 --only-blueprints
No blueprints found.
./multipass find nonsense:charm-dev # the case where the search string is a valid blueprint
Blueprint                   Aliases           Version          Description
charm-dev                                     latest           A development and testing environment for charmers
./multipass find nonsense:charm-dev --only-images
No images found.
./multipass find nonsense:charm-dev --only-blueprints
Blueprint                   Aliases           Version          Description
charm-dev …
```
=> Honor remote name when used with a Blueprint

src/network/url_downloader.cpp, src/platform/backends/lxd/lxd_vm_image_vault.cpp, src/xz_decoder/xz_image_decoder.cpp
=> [cli] Only update progress when percentage goes up

src/sshfs_mount/sshfs_mount_handler.cpp
When determining if multipass-sshfs is installed in an instance, wait up to 15 seconds for snap to return in case snapd is busy.
Fixes #2986
=> [mount_handler/sshfs] Wait up to 15 seconds for snap query

include/multipass/snapshot.h, include/multipass/virtual_machine.h, src/daemon/daemon.cpp, src/platform/backends/shared/base_snapshot.cpp, src/platform/backends/shared/base_snapshot.h, src/platform/backends/shared/base_virtual_machine.cpp, src/platform/backends/shared/base_virtual_machine.h, tests/mock_virtual_machine.h, tests/stub_snapshot.h, tests/stub_virtual_machine.h
Share ownership of a VM's snapshots to avoid locking the VM's client. Lock only VM and Snapshot class's internal code.
=> [snapshots] Safer threading

src/daemon/daemon_config.cpp
Avoid setting permissions on an empty dir. Also, let new storage dirs inherit permissions.
=> Fix Qt warning

src/client/cli/cmd/launch.cpp
Add an explanation to the `launch --help` for what valid instance names are.
TODO: If the wording looks good, [multipass.run](https://multipass.run/docs/launch-command) docs needs to be updated as well
Fixes #1277
=> [cli] Add valid name desc to help

src/daemon/daemon.cpp
Since there are sometimes multiple entries that are labeled as Linux Filesystem, edit the command to sort them and take the largest one. This is under the assumption that the main filesystem is the largest.
This command is getting a bit convoluted at this point, so other suggestions on where to get this info is welcome.
Fixes #3041
=> Pull disk info from home partition

src/network/url_downloader.cpp
Fixes #3049
---
@nathan-j-hart This will be in the form of something like:
`Multipass/1.11.1 (macos-11.3; arm64)`
Let me know what you think.
=> [url_downloader] Add HTTP UserAgent header info

src/platform/backends/shared/linux/dbus_wrappers.h
=> [dbus] Avoid DBus calls with invalid variant args

src/daemon/daemon.cpp
Replaces #3056. That work becomes outdated if this is merged in.
Fixes #3055
=> Filter duplicate instances

include/multipass/constants.h, include/multipass/vm_image_info.h, src/daemon/common_image_host.cpp, src/daemon/common_image_host.h, src/daemon/custom_image_host.cpp, src/daemon/daemon_config.cpp, src/daemon/ubuntu_image_host.cpp, src/daemon/ubuntu_image_host.h, src/platform/platform_linux.cpp, src/platform/platform_shared.h, tests/test_custom_image_host.cpp, tests/test_ubuntu_image_host.cpp
Fixes #3069
---
Corresponding private PR is at canonical/multipass-private#523.
There a couple of things to keep in mind with this PR:
1. The `snapcraft:` remote will no longer show when doing a `multipass find`.  I think this is fine since the `snapcraft` remote is really only intended for Snapcraft usage and should really have never been shown by default in the first place.  That said, `multipass find snapcraft:` will show the supported images.
2. To go along with `multipass find snapcraft:`, there are a couple of extra aliases that are shown from Simplestreams that we don't support in Multipass.  It would require a pretty big refactor to properly filter those out and now is not the time for that.  I think since the `snapcraft` remote would no longer be shown by default, this isn't a …
=> [image_host] Switch to using buildd Simplestreams for snapcraft remote

.github/workflows/linux-Clang.patch, .github/workflows/linux-Coverage.patch, .github/workflows/linux-Debug.patch, .github/workflows/linux.patch, CMakeLists.txt
This is a small improvement for developers who use ccache to accelerate the multipass build. With the change, the developer only has to install ccache and does not have to manually append the cmake arguments because it is taken care of by the cmake script itself.  
Reference: https://crascit.com/2016/04/09/using-ccache-with-cmake/
=> Added ccache to cmakefile and updated the corresponding patches.

src/client/cli/cmd/restore.cpp
Accept empty answer and default to yes on the snapshot question asking whether an automatic snapshot should be taken on restore. 
This is unlike what we do in the bridging question because here we have a natural, safe, default answer, unlike in that other one.
=> [vm] Default auto snapshot answer to yes on restore question

src/platform/platform_shared.h
=> [platform/shared] Fix missing comma in snapcraft set

include/multipass/id_mappings.h, include/multipass/mount_handler.h, include/multipass/sshfs_mount/sshfs_mount_handler.h, src/daemon/daemon.cpp, src/platform/backends/lxd/CMakeLists.txt, src/platform/backends/lxd/lxd_mount_handler.cpp, src/platform/backends/lxd/lxd_mount_handler.h, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/lxd/lxd_virtual_machine.h, src/platform/backends/qemu/qemu_mount_handler.cpp, src/platform/backends/qemu/qemu_mount_handler.h, src/sshfs_mount/sshfs_mount_handler.cpp, tests/lxd/CMakeLists.txt, tests/lxd/test_lxd_mount_handler.cpp, tests/mock_mount_handler.h, tests/mock_virtual_machine.h, tests/qemu/test_qemu_mount_handler.cpp, tests/stub_mount_handler.h, tests/test_daemon_mount.cpp, tests/test_daemon_start.cpp, tests/test_daemon_umount.cpp, tests/test_sshfs_mount_handler.cpp
[JIRA story link](https://warthogs.atlassian.net/browse/MULTI-188)
[spek link](https://docs.google.com/document/d/1LAnT92_lhfsIQD_JIbb4JfsqVakRXVpJnFYT1gpNMCQ/edit#)
The current workflow and behaviors are as follows: 
`./multipass info peaceable-tadpole
`
```
Name:           peaceable-tadpole
State:          Running
IPv4:           10.156.2.154
Release:        Ubuntu 22.04.2 LTS
Image hash:     d900c08af2be (Ubuntu 22.04 LTS)
CPU(s):         1
Load:           0.00 0.00 0.00
Disk usage:     1.6GiB out of 9.5GiB
Memory usage:   190.9MiB out of 946.1MiB
Mounts:         --
```
`./multipass mount -t native /home/georgel/mount peaceable-tadpole:/home/ubuntu/native
`
`mount failed: Please stop the instance peaceable-tadpole before mount it natively.
`
`./multipass stop peaceable-tadpole
` …
=> lxd native mount

include/multipass/alias_definition.h, include/multipass/cli/alias_dict.h, include/multipass/cli/format_utils.h, include/multipass/client_launch_data.h, include/multipass/json_utils.h, src/client/cli/client.cpp, src/client/cli/cmd/CMakeLists.txt, src/client/cli/cmd/alias.cpp, src/client/cli/cmd/create_alias.cpp, src/client/cli/cmd/create_alias.h, src/client/cli/cmd/delete.cpp, src/client/cli/cmd/launch.cpp, src/client/cli/cmd/prefer.cpp, src/client/cli/cmd/prefer.h, src/client/cli/cmd/purge.cpp, src/client/cli/cmd/unalias.cpp, src/client/cli/cmd/unalias.h, src/client/cli/formatter/csv_formatter.cpp, src/client/cli/formatter/json_formatter.cpp, src/client/cli/formatter/table_formatter.cpp, src/client/cli/formatter/yaml_formatter.cpp, src/client/common/alias_dict.cpp, src/daemon/daemon.cpp, src/daemon/default_vm_image_vault.cpp, src/utils/CMakeLists.txt, src/utils/json_utils.cpp, tests/test_alias_dict.cpp, tests/test_cli_client.cpp, tests/test_daemon.cpp, tests/test_format_utils.cpp
Alias contexts avoid clash between alias names. Specification is [here](https://docs.google.com/document/d/1L8q0TdQMiwvd5iAELiAuWqU3fVii0_nPF5dKzUdYOLY/edit#heading=h.a291qhvyhsw3).
=> Introduce alias contexts

src/utils/utils.cpp, tests/test_utils.cpp
This fixes #3116, the execution of strings containing quotes and newlines, like `multipass exec instance -- bash -c 'blah\nblah'`.
This also fixes #3119, the execution of strings containing empty substrings delimited with single or double quotes.
=> Fix newlines and empty strings which go through SSH

CMakeLists.txt
This reverts commit b9a097f6a5a959cf9df59e8ded78b2b44fcf59a3.
---
Seems the change I made before broke the current `dev` build and we get the wrong version for `edge`.  Let's revert this for now and re-evaluate if the `rc` builds get messed up again.
=> Revert "[build] Use top commit when determing rc and dev versions"

src/utils/utils.cpp, tests/test_utils.cpp
When we need to pass a string through SSH, we escape some characters. But we forgot about newlines, which are eliminated unless quoted. This PR just put newlines in double quotes, and leave escaping the rest of the characters untouched.
Fixes https://github.com/canonical/multipass/issues/3116.
=> Quote '\n' in strings which go through SSH.

src/client/cli/cmd/common_cli.cpp, src/client/cli/cmd/common_cli.h, src/client/cli/cmd/delete.cpp, src/client/cli/cmd/info.cpp, src/daemon/daemon.cpp, src/rpc/multipass.proto
=> [snapshots] Delete snapshot cli and daemon placeholder

include/multipass/snapshot.h, src/daemon/daemon.cpp, src/platform/backends/qemu/qemu_snapshot.cpp, src/platform/backends/shared/base_snapshot.cpp, src/platform/backends/shared/base_snapshot.h, tests/stub_snapshot.h
Debated the use of `QDateTime` vs `std::chrono::time_point`, but some functions that would be useful for serializing the object to a string and vice versa are only available in C++20. You can still make it work with the C++17 STL, but you will be forced to use `std::time_t` in places. Depending on the platform, `std::time_t` can be only 32 bits, meaning that its maximmum date is sometime in 2038.
=> [snapshots] record snapshot creation time

include/multipass/exceptions/internal_timeout_exception.h, include/multipass/exceptions/ip_unavailable_exception.h, src/platform/backends/shared/shared_backend_utils.h, src/utils/utils.cpp
Two main changes to improve the step of waiting for SSH, when starting/launching instances:
1. Increase the time allotted for each iteration of the loop to wait for SSH, to 1 second. Log each such iteration of the loop.
2. Retry only on specific exceptions, logging them (with `trace` verbosity, since this happens every second), and letting the rest through, in the hope that this may shed some light into cases where instances end up in unknown state.
=> Improve waiting for SSH

src/platform/backends/qemu/qemu_vm_process_spec.cpp, tests/qemu/test_qemu_vm_process_spec.cpp
Update the AppArmor profile for QEMU processes, to allow `/usr/local` based firmware directories as well as `qemu` "leave" directories. This caters to locally built QEMU needs.
=> [qemu] Allow more firmware directories in AppArmor

3rd-party/CMakeLists.txt
There is a regression seen on macOS in the latest gRPC branch we used for the 1.12 release.  The gRPC branch has been updated to revert the problematic commits.
Fixes #3142
---
Here are the relevant changes in our gRPC branch: https://github.com/CanonicalLtd/grpc/commit/e796379a445776c34d5146afcad0ba1902783ff1 and https://github.com/CanonicalLtd/grpc/commit/e3acf245a91630fe4d464091ba5446f6a638d82f.
=> [3rd-party] Update gRPC branch

src/client/cli/cmd/delete.cpp, src/client/cli/cmd/delete.h
Added a confirmation action that a user must answer if purging snapshots and instances together in the same command. If you think about it, specifying both instances and snapshots together in a deletion command is a little bit odd and not something that user who is unfamiliar with the command would do. So, if they do happen to specify both, we ask them to confirm the action.
=> [snapshots] Improve purge wording

src/daemon/daemon.cpp
Verify all snapshot arguments, even when the corresponding instance is also an argument. Do so while fetching each snapshot's info and before deleting any instance/snapshot.
=> [snapshots] Fix daemon being blind to missing snapshots in `info` and `delete`

src/platform/backends/qemu/CMakeLists.txt
Fixes a build failure on macOS.
=> [qemu] Link backend against `scope_guard`

src/iso/CMakeLists.txt, src/iso/cloud_init_iso.cpp
Add more information to the exception that is thrown when `QFile` fails to `open` to create a cloud-init ISO, in the hope that we can gain some insight into why this keeps failing in CI (e.g. https://github.com/canonical/multipass/actions/runs/5690481781/job/15423903919#step:13:101)
=> [iso] Complement error message on failure to open

tests/test_base_virtual_machine_factory.cpp
Fix call to `std::mismatch` which would imply a deference of the end iterator.
=> [tests] Fix UB in test

include/multipass/cli/prompters.h, src/client/cli/cmd/launch.cpp, src/client/common/prompters.cpp, tests/test_cli_prompters.cpp
When adding a bridged interface to an existing instance, the user must be prompted to allow adding a network bridge disrupting connectivity. This is already implemented, but the code lies in the implementation of the `launch` command. This PR moves this code to the part common to all clients.
=> Refactor bridge prompt

3rd-party/CMakeLists.txt, include/multipass/cli/client_common.h, include/multipass/dart_ffi.h, src/client/cli/client.cpp, src/client/cli/main.cpp, src/client/common/client_common.cpp, src/client/desktop_gui/CMakeLists.txt, src/client/desktop_gui/ffi/dart_ffi.cpp, src/client/gui/client_gui.cpp, src/client/gui/main.cpp, tests/mock_cert_provider.h, tests/test_cli_client.cpp, tests/test_client_common.cpp
This PR adds a new shared library called `dart_ffi` which contains C interfaces of some of our C++ functions which we'd like to call from Dart using FFI.
Some additional refactoring was needed in order decouple the generation of certificates from the creation of the gRPC channel, so that certificate data can be more easily retrieved using a C interface.
=> Create dynamic libraries with C interfaces for Dart FFI

src/daemon/daemon.cpp
This reverts commit f570fd99315a80a1a503ab07cd8cbde86c45e710, since one snapshot overview needs to be added per snapshot.
=> Revert "[daemon] Extract repeated argument derivation"

src/simplestreams/simple_streams_manifest.cpp
=> Show image with `devel` alias regardless of its `supported` status

src/daemon/daemon.cpp, src/daemon/instance_settings_handler.cpp, src/daemon/instance_settings_handler.h, tests/test_instance_settings_handler.cpp
This PR implements the `set` interface to add a bridged network to an existing instance.
=> Add `local.instance.bridged` setting.

completions/bash/multipass, include/multipass/async_periodic_task.h, include/multipass/simple_streams_manifest.h, include/multipass/url_downloader.h, include/multipass/utils.h, include/multipass/vm_image_host.h, src/client/cli/cmd/find.cpp, src/daemon/common_image_host.cpp, src/daemon/common_image_host.h, src/daemon/custom_image_host.cpp, src/daemon/custom_image_host.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/daemon_config.cpp, src/daemon/ubuntu_image_host.cpp, src/daemon/ubuntu_image_host.h, src/network/url_downloader.cpp, src/rpc/multipass.proto, src/simplestreams/simple_streams_manifest.cpp, tests/image_host_remote_count.cpp, tests/mischievous_url_downloader.cpp, tests/mischievous_url_downloader.h, tests/mock_image_host.h, tests/mock_url_downloader.h, tests/stub_image_host.h, tests/test_cli_client.cpp, tests/test_custom_image_host.cpp, tests/test_daemon_find.cpp, tests/test_ubuntu_image_host.cpp
This PR contains a few things. 
1. `update_manifests()` function will no longer be called internally in the `UbuntuImageHost` and `CustomImageHost` class, instead it becomes a public method and gets invoked by client code like `daemon.cpp`. 
2. The two `update_manifests()` calls are wrapped into one function and it is launched by the daemon constructor asynchronously and it will run periodically. 
3. Because of the first two, the `manifest_time_to_live` related codes are all removed since it is no longer relevant. 
4. Inside `UbuntuImageHost::update_manifests` and `CustomImageHost::update_manifests`, the parallelization of the manifests fetching is also applied in order to speed it up. 
---
[Epic link](https://warthogs.atlassian.net/browse/MULTI-254)
[issue …
=> Improve the performance of manifests fetching

.clang-format
suggestive clang-format improvement:
The function arguments and parameters are always bin-packed in the current clang-format style which can sometimes be hard to read. The improved clang-format formats arguments and parameters in a way that it either does not break the line because the line length is still within the column limit or it breaks each argument/parameter into a separate line. 
This PR contains the clang-format file code change and some sample files in the new format. If this PR is approved, then the sample files will be reverted and only the clang-format change will be merged.
=> clang-format improvement: remove bin pack arguments/parameters.

src/client/cli/argparser.cpp
=> [cli] fix regex to remove `command` argument from help messages

completions/bash/multipass
Bash completions will currently suggest repeated flags endlessly. This PR filters out previously seen options/flags with the assumption that no multipass currently accepts this pattern.
=> [bash] remove duplicates from completions

include/multipass/utils.h, src/utils/utils.cpp, tests/mock_platform.h, tests/mock_utils.h
This is a prerequisite of canonical/multipass-private#508, but the changes should appear in public as well
=> [tests] add mocks for a few util methods

src/daemon/daemon.cpp
Fix interpreting of snapshot arguments with empty name, i.e. ending in dot (like "\<instance\>."). Refuse such arguments, instead of interpreting them as instance arguments (i.e. equivalent to "\<instance\>").
This affects `info` and `delete`.
```
$ multipass info foo. # before
[info on instance foo]
$ multipass info foo. # after
info failed: The following errors occurred:
No such snapshot: a.
```
=> [snapshots] Fix interpreting empty snapshot name in snapshot args

src/daemon/daemon.cpp, src/platform/backends/qemu/linux/qemu_platform_detail.h, src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp, src/platform/backends/qemu/qemu_platform.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, tests/qemu/linux/test_qemu_platform_detail.cpp, tests/qemu/mock_qemu_platform.h
This branch implements the Linux platform code for adding bridged network interfaces on QEMU. Since it will be available first in macOS, here the implementation just throws.
=> Add bridged interfaces in macOS QEMU

include/multipass/ssh/ssh_session.h, include/multipass/utils.h, include/multipass/virtual_machine.h, src/daemon/daemon.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.h, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/lxd/lxd_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/ssh/ssh_session.cpp, src/utils/utils.cpp, tests/libvirt/test_libvirt_backend.cpp, tests/lxd/test_lxd_backend.cpp, tests/mock_virtual_machine.h, tests/qemu/test_qemu_backend.cpp, tests/stub_virtual_machine.h, tests/test_base_virtual_machine.cpp, tests/test_daemon.cpp, tests/test_daemon_start.cpp, tests/test_delayed_shutdown.cpp, tests/test_sftp_client.cpp, tests/test_sftpserver.cpp, tests/test_ssh_client.cpp, tests/test_ssh_process.cpp, tests/test_ssh_session.cpp, tests/test_sshfsmount.cpp
- Always pass the `key_provider` in when verifying that ssh is up and ready
- Remove unused `SSHSession` constructor
- Remove `SSHSession` constructor that is specifically for tests and modify tests to pass a stub key provider
- Simplify remaining `SSHSession` constructors
Fixes #3252
=> [ssh] wait for ssh user authentication before returning

src/cert/ssl_cert_provider.cpp
While implementing my own Go client for multipass, I noticed that the TLS certificates used by `multipassd`'s RPC server weren't using the SANs x509v3 extension. 
As such you would run into an annoying error when attempting to verify the TLS certificate that was being returned by the RPC server (`multipassd`). 
Go's standard library hasn't supported TLS/x509 certitficates without SANs present for a while now. See https://go.dev/doc/go1.16#minor_library_changes
This change is a modification to the `ssl_cert_provider.cpp`'s x509 certificate generation. Here there are two major changes: 
1. Version of x509 certificate has been bumped to x509v3
2. Added SANs x509v3 Extension to include `DNS:${server_name}`
I have managed to get this building and testing locally on my Ubuntu laptop, however I …
=> updated x509 certificates to x509v3 and SANs extension

include/multipass/utils.h, src/sshfs_mount/sshfs_mount_handler.cpp, src/utils/utils.cpp
=> [sshfs_mount] Better logic to determine if mount is active in instance

3rd-party/submodule_info.md, include/multipass/ip_address.h, src/cert/ssl_cert_provider.cpp, src/client/cli/cmd/transfer.cpp, src/ssh/sftp_client.cpp, src/ssh/sftp_utils.cpp
This fixes compilation with gcc-13 and clang-16.
=> Support Mantic compilers

src/blueprint_provider/default_vm_blueprint_provider.cpp, tests/test_blueprint_provider.cpp, tests/test_data/blueprints/v1/complex-cloud-init.yaml
This PR makes it so that cloud-init vendor data coming from a blueprint is merged with the vendor data that we normally provide. The merging follows these rules:
- If a key refers to a scalar value in both our vendor data and the blueprint vendor data, the blueprint is rejected
- If a key refers to values of different types in our vendor data and the blueprint vendor data, the blueprint is rejected
- If an entry from the blueprint vendor data does not exist in our own vendor data, simply add it
- If a key refers to a sequence in both our vendor data and the blueprint vendor data, append the items from the blueprint sequence to the sequence from our data
- If a key refers to a map in both our vendor data and the blueprint vendor data, recurse this algorithm on each key from the blueprint …
=> Merge blueprint vendor data

src/client/cli/cmd/delete.cpp, src/client/cli/cmd/delete.h, src/daemon/daemon.cpp, src/rpc/multipass.proto
Confirm snapshot deletion with a prompt to users when they try to delete a snapshot without the `--purge` flag, as long as multipass is running interactively.
=> Confirm snapshot deletion with prompt

src/daemon/daemon.cpp, tests/test_daemon_find.cpp
=> [daemon/find] Filter out snapcraft remote by default

include/multipass/file_ops.h, src/sshfs_mount/sftp_server.cpp, src/sshfs_mount/sftp_server.h, src/sshfs_mount/sshfs_mount.cpp, src/utils/file_ops.cpp, tests/mock_file_ops.h, tests/test_sftpserver.cpp, tests/test_sshfsmount.cpp
File operations in an instance in an sshfs mount are now restricted to only files that have a uid/gid mapping for them (host-to-guest).
Fixes #3179 
Public side of [#571](https://github.com/canonical/multipass-private/pull/571)
=> [sftp] Restrict sshfs perms to mapped ids

include/multipass/virtual_machine.h, include/multipass/virtual_machine_factory.h, src/client/cli/formatter/csv_formatter.cpp, src/client/cli/formatter/json_formatter.cpp, src/client/cli/formatter/table_formatter.cpp, src/client/cli/formatter/yaml_formatter.cpp, src/daemon/daemon.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine_factory.h, src/platform/backends/shared/base_virtual_machine.cpp, src/platform/backends/shared/base_virtual_machine.h, src/platform/backends/shared/base_virtual_machine_factory.h, src/rpc/multipass.proto, tests/mock_virtual_machine.h, tests/mock_virtual_machine_factory.h, tests/stub_virtual_machine.h
And omit the number of snapshots in `info`.
Fixes #3328
=> Complain on snapshot operations if unsupported

src/daemon/daemon.cpp, tests/test_daemon_start.cpp
Some executions can give a timeout for several reasons, but does not necessarily mean there was an error. However, the daemon used to fail on timeouts as it failed in severe cases like not being able to create a SSH connection. This PR makes the daemon catch the timeout exception, avoiding an error be shown to the user.
=> Catch timeout on commands at boot

src/platform/backends/shared/base_virtual_machine.cpp
Stop applying the last snapshot when rolling back a failed snapshot
restore. Instead, apply the intended snapshot only after every other
restore step has succeeded, thereby dispensing with rolling back the
apply step itself (as long as it is itself transactional). Fixes #3362.
=> [snapshots] Fix restore rollback

src/client/common/client_common.cpp
This will hopefully fix a race condition when running unit tests particularly the occasional TestClientCommon.usesExistingGuiCert failure.
=> [client/common] Increase deadline timeout

src/daemon/daemon.cpp
Avoid fixing the state of deleted instances from off to stopped, along with incoherent log "<instance> is deleted but has incompatible state 0, resetting state to 0 (stopped)".
=> [daemon] Avoid fixing state from off to stopped

include/multipass/virtual_machine_factory.h, src/daemon/daemon.cpp, src/daemon/instance_settings_handler.cpp, src/daemon/instance_settings_handler.h, src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.h, src/platform/backends/shared/base_virtual_machine_factory.h, src/platform/backends/shared/linux/backend_utils.cpp, src/platform/backends/shared/linux/backend_utils.h, tests/lxd/test_lxd_backend.cpp, tests/mock_virtual_machine_factory.h, tests/test_base_virtual_machine_factory.cpp, tests/test_instance_settings_handler.cpp
This PR fixes issue 3 of [this review](https://github.com/canonical/multipass/pull/3195#pullrequestreview-1765804396).
=> Fix `get local.<instance>.bridged` command

src/platform/backends/lxd/lxd_virtual_machine.cpp, tests/lxd/test_lxd_backend.cpp
Replace the existing runtime error with proper not-implemented exception.
=> [lxd] Throw not-impl exception from LXD suspend

src/client/cli/formatter/table_formatter.cpp, tests/test_alias_dict.cpp
When the alias dictionary contained an empty context, the table formatter segfaulted.
Fixes https://github.com/canonical/multipass/issues/3383.
=> Fix segfault in `aliases` command

src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/lxd/lxd_request.cpp, src/platform/backends/lxd/lxd_request.h, tests/lxd/test_lxd_backend.cpp, tests/test_daemon_start.cpp
Adding interfaces after the instance was created introduced the possibility of some kinds of clashes when the instance starts. To fix this, we check first if the backend is able to add each one of the network interfaces requested by the user. The daemon then filters out the failing interfaces, letting only the interfaces which work be added to the instance.
This PR fixes issue 4 of [this review](https://github.com/canonical/multipass/pull/3195#pullrequestreview-1765804396).
=> Filter new extra interfaces before instance start

src/daemon/daemon.cpp
This will add the pollinate package to the snapcraft buildd images. It is no-op on the regular cloud images since it already exists.
Fixes #3390
=> [daemon] Add pollinate package to internal cloud-init

src/client/cli/cmd/create_alias.cpp
The alias message was not shown when launching a Blueprint which defined aliases. The issue was that it was shown only when the size of the alias dictionary was one, and in fact it would be two when the new alias is in a context different to `default`.
This bug was reported [here](https://discourse.ubuntu.com/t/running-a-container-with-the-docker-blueprint-in-multipass/26806/12).
=> Fix showing alias message on Blueprint creation

src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/shared/qemu_img_utils/qemu_img_utils.cpp, src/platform/backends/shared/qemu_img_utils/qemu_img_utils.h, tests/qemu/test_qemu_backend.cpp
Addresses #3399.
I am not super happy about this approach, as it goes against *fail fast*, breaking preconditions for other operations (snapshots+resizing) and leaving a VM around in a bad state. A better approach would be to put any VMs whose constructor threw into a special quarantine state, where only a select few operations would be allowed. But we don't have time for that right now and the operation in question is transitory anyway, so I guess this will do.
=> Handle failure to convert to QCOW2 v3

snap/snapcraft.yaml
This will quiet the errors and linter.  The only warning now is for libvirt.so which is still needed since it is dlopen()'d.  This reduces the Snap size by ~45%!
=> [snap] Improve snap packaging

src/client/cli/cmd/common_callbacks.h, src/client/cli/cmd/remote_settings_handler.cpp, src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/instance_settings_handler.cpp, src/daemon/instance_settings_handler.h, src/rpc/multipass.proto, tests/test_common_callbacks.cpp, tests/test_daemon.cpp, tests/test_instance_settings_handler.cpp
The prompt asking the user for authorization to disrupt networking to create a bridge was not working. This PR fixes issue 1 of [this review](https://github.com/canonical/multipass/pull/3195#pullrequestreview-1765804396).
=> Fix bridging authorization

include/multipass/cloud_init_iso.h, include/multipass/virtual_machine.h, src/daemon/daemon.cpp, src/iso/cloud_init_iso.cpp, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/lxd/lxd_virtual_machine.h, src/platform/backends/shared/base_virtual_machine.cpp, src/platform/backends/shared/base_virtual_machine.h, tests/lxd/test_lxd_backend.cpp, tests/mock_virtual_machine.h, tests/stub_virtual_machine.h, tests/test_base_virtual_machine.cpp, tests/test_cloud_init_iso.cpp, tests/test_daemon.cpp, tests/test_instance_settings_handler.cpp
This PR is about applying the extra interface changes to cloud-init-config.iso file when the snapshot retore command is called.
=> Snapshot restore applies cloud init change

CMakeLists.txt
The `covreport` target is not working (this target is obtained by using the CMake flag `-DCMAKE_BUILD_TYPE=Coverage`) with Mantic. The reason is that the `lcov` package in Mantic is broken; this is fixed by installing the package from Noble. But this newer package produce some warnings which become fatal. This PR makes newer versions of `lcov` ignore those warnings, producing the desired output.
=> Fix coverage on Mantic

src/daemon/daemon.cpp, tests/test_daemon.cpp
The code in Daemon::set() did not take into account that Daemon::get_bridged_interface_name() could throw. Throwing is correct in all the other calls, so only the exception thrown in `set()` was catched this time.
=> Fix non-bridging settings

.github/workflows/linux.yml
This will help allow builds to continue while the issue of tokenless uploads to Codecov is worked out.
See https://github.com/codecov/codecov-action/issues/1359 for more details.
=> [actions] Continue on Coverage build errors

snap/snapcraft.yaml
This is needed for vcpkg support and the Launchpad builders don't have it installed by default.
Fixes #3480
=> [snap] Add curl build dependency

src/platform/backends/qemu/qemu_virtual_machine.cpp
Fix an assert condition when making a new snapshot of a QEMU VM.
=> Fix assert condition in QEMU VMs

include/multipass/json_utils.h, src/daemon/daemon.cpp, src/platform/backends/qemu/qemu_snapshot.cpp, src/platform/backends/shared/base_snapshot.cpp, src/platform/backends/shared/base_snapshot.h, src/utils/json_utils.cpp, tests/test_base_snapshot.cpp, tests/test_json_utils.cpp
Snapshots taken with old versions of Multipass did not store the `extra_interfaces` field. If an interface is added after instance creation, it will overwrite the extra interfaces added at creation. This PR fixes that behavior.
=> Handle legacy snapshots

src/daemon/instance_settings_handler.cpp, tests/test_instance_settings_handler.cpp
If `local.instance.bridged` is `true`, no more interfaces bridging the current network will be allowed.
=> Permit only one bridge

snap/snapcraft.yaml
Paths in the gui part were hardcoded to the multipass part, but this breaks on Launchpad due to how snapcraft is invoked (--destructive-mode).
=> [snap] Use a more general approach for paths in gui part

include/multipass/utils.h, src/daemon/CMakeLists.txt, src/daemon/daemon.cpp, src/daemon/runtime_instance_info_helper.cpp, src/daemon/runtime_instance_info_helper.h, src/utils/utils.cpp, tests/mock_utils.h
Introduce the parallelization of the SSH commands that are used for `info` within VMs with multiple cores.
With the exception of the command to fetch IPs (which follows a different scheme that is used also for `list`), all the necessary commands are combined into a single one and executed in one go on the instane over SSH. Two versions of this single combined command are derived: one sequential and one parallel. The parallel version is used when the VM has multiple cores. On single-core VMs, the sequential version is used.
For organization, and to avoid polluting the unnamed namespace in `daemon.cpp` any further, the code is now in a new helper class: `RuntimeInstanceInfoHelper`.
Credit goes to @andrei-toterman for the idea implemented here. Thanks!
=> Parallelize info intra vm

tests/daemon_test_fixture.cpp, tests/test_cli_client.cpp, tests/test_client_common.cpp, tests/unix/test_daemon_rpc.cpp
Remove the excessive gmock warnings from unit tests.
=> [unit test] use nicemock to remove the excessive gmock warnings. 

include/multipass/async_periodic_download_task.h, include/multipass/async_periodic_task.h, include/multipass/exceptions/aborted_download_exception.h, include/multipass/exceptions/base_qexception.h, include/multipass/exceptions/create_image_exception.h, include/multipass/exceptions/download_exception.h, src/daemon/custom_image_host.cpp, src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/ubuntu_image_host.cpp, tests/test_custom_image_host.cpp, tests/test_daemon_find.cpp, tests/test_ubuntu_image_host.cpp
fix #3464 
This PR adds [binary exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) based retry mechanism to async periodic download tasks, the checking exception (download failure an exception) in the main thread is done in a non-blocking fashion via `QFutureWatcher`. 
1. Changed `std::async` + `std::future` pair to `QtConcurrent::run` + `QFuture` in order to use some QFuture specific features.
2. Added  `QFutureWatcher` to watch `QFuture` and react correspondingly in the successful and failed cases when QFuture is finished. 
3. Changed `DownloadException` to a QException-based class so it can cross the qt thread boundary. 
4. Made the CRTP `BaseQException` class to reuse the boilerplate code for all the QException derived classes. 
To test the behavior, you can …
=> Retry on download failure

src/daemon/daemon.cpp, src/daemon/runtime_instance_info_helper.cpp
- Add back runtime info items that got lost in a rebase.
- Fix logic to decide whether to execute cmds in parallel
- Fix command quoting to avoid collapsing a double space on cpu_times
=> Fix issues with runtime info

src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, src/platform/backends/qemu/linux/dnsmasq_process_spec.cpp, src/platform/backends/qemu/qemu_base_process_spec.cpp, src/platform/backends/qemu/qemu_vm_process_spec.cpp, src/platform/backends/shared/sshfs_server_process_spec.cpp, src/platform/platform_linux.cpp, src/process/qemuimg_process_spec.cpp, src/utils/snap_utils.cpp, tests/linux/test_snap_utils.cpp
Normalize uses of `mu` to `mpu`, which was already in use and is more in line with the three-letter norm for multipass namespace aliases.
=> [utils] Use a consistent namespace alias for utils

include/multipass/id_mappings.h, include/multipass/mount_handler.h, include/multipass/snapshot.h, include/multipass/virtual_machine.h, include/multipass/vm_mount.h, src/client/cli/cmd/mount.cpp, src/daemon/daemon.cpp, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/qemu/qemu_mount_handler.cpp, src/sshfs_mount/sshfs_mount_handler.cpp, src/utils/vm_mount.cpp, tests/daemon_test_fixture.cpp, tests/json_test_utils.cpp, tests/qemu/test_qemu_mount_handler.cpp, tests/qemu/test_qemu_snapshot.cpp, tests/test_base_snapshot.cpp, tests/test_base_virtual_machine.cpp, tests/test_daemon.cpp, tests/test_id_mappings.cpp, tests/test_vm_mount.cpp
Fixes #3332
Public side of [#641](https://github.com/canonical/multipass-private/pull/641)
=> [mounts] only allow one to one id mappings

include/multipass/file_ops.h, src/utils/file_ops.cpp, src/utils/utils.cpp, tests/file_operations.cpp, tests/file_operations.h, tests/linux/test_platform_linux.cpp, tests/mock_file_ops.h, tests/test_sftpserver.cpp, tests/test_utils.cpp
This PR improves error handling around writing files via `make_file_with_content()`.
There are actually two versions of `make_file_with_content()` before this PR: one in utils, one in tests. One started as a copy-paste of the other, then they drifter apart. Entropy always increases... That is fixed here (not entropy increasing unfortunately).
But what prompted this was [this failure](https://github.com/canonical/multipass/actions/runs/9587796659/job/26438549050#step:15:262). That might arise if the test file is not properly flushed when closed, as that error would [go undetected](https://doc.qt.io/qt-6/qfiledevice.html#close). This refines the implementation of `make_file_with_content` by calling `QFile::flush()` directly and checking the return. It also adds more details when `QFile` …
=> Refine utilities to `make_file_with_content`

include/multipass/platform.h, include/multipass/utils.h, include/multipass/virtual_machine_factory.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/instance_settings_handler.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.cpp, src/platform/backends/lxd/lxd_virtual_machine_factory.h, src/platform/backends/qemu/linux/qemu_platform_detail.h, src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp, src/platform/backends/qemu/qemu_platform.h, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.h, src/platform/backends/shared/base_virtual_machine_factory.cpp, src/platform/backends/shared/base_virtual_machine_factory.h, src/platform/backends/shared/linux/backend_utils.cpp, src/platform/backends/shared/linux/backend_utils.h, src/platform/platform_linux.cpp, src/utils/utils.cpp, tests/lxd/test_lxd_backend.cpp, tests/mock_daemon.h, tests/mock_platform.h, tests/mock_virtual_machine_factory.h, tests/qemu/mock_qemu_platform.h, tests/test_base_virtual_machine_factory.cpp, tests/test_daemon.cpp, tests/test_instance_settings_handler.cpp
An instance is considered bridged, at any point in time, *iff* the configured preferred network at that time is:
- part of the corresponding `VMSpecs::extra_networks`, or
- linked to a bridge/switch (depending on the platform) which is part of the instance's `extra_networks`.
This PR implements that predicate in `mp::Daemon::is_bridged` (and `is_bridged_impl`), removing any previous logic relying on bridge names to relate bridges with other interfaces, and instead using readily available `NetworkInterfaceInfo::links`. To achieve this, the predicate calls `find_bridge_with`, which was refactored into a backend-agnostic utility.
Because Windows uses "switches" instead of "bridges", a platform function is added to obtain the correct nomenclature, replacing hard-coded uses in backend …
=> Fix detection of whether an instance is bridged, take2

include/multipass/ssh/ssh_session.h, include/multipass/utils.h, include/multipass/virtual_machine.h, src/daemon/runtime_instance_info_helper.cpp, src/platform/backends/shared/base_virtual_machine.cpp, src/platform/backends/shared/base_virtual_machine.h, src/ssh/ssh_session.cpp, src/utils/utils.cpp, tests/mock_utils.h, tests/mock_virtual_machine.h, tests/stub_virtual_machine.h, tests/test_base_virtual_machine.cpp, tests/test_delayed_shutdown.cpp
Reduce logging of ssh executions inside instances for `list` and `info` to trace level, while keeping the rest at debug.
=> [ssh] Reduce log level to avoid log spam with GUI

src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp
On backends that do not implement networks, `prepare_networking()` should be a NOOP, rather than throw. We throw NotImplemented elsewhere.
=> Fix broken launch on QEMU

include/multipass/exceptions/virtual_machine_state_exceptions.h, include/multipass/virtual_machine.h, src/client/cli/cmd/stop.cpp, src/daemon/daemon.cpp, src/daemon/daemon.h, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.h, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/lxd/lxd_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/platform/backends/shared/base_virtual_machine.cpp, src/platform/backends/shared/base_virtual_machine.h, src/platform/backends/shared/qemu_img_utils/qemu_img_utils.cpp, src/platform/backends/shared/qemu_img_utils/qemu_img_utils.h, src/rpc/multipass.proto, tests/libvirt/test_libvirt_backend.cpp, tests/lxd/test_lxd_backend.cpp, tests/mock_virtual_machine.h, tests/qemu/test_qemu_backend.cpp, tests/stub_virtual_machine.h, tests/test_base_virtual_machine.cpp, tests/test_cli_client.cpp
Add a new parameter to force the shutdown instances (i.e., power down them).
Fixes #1909, Fixes #2492
=> Add `--force` argument to the `stop` command

README.md
close https://github.com/canonical/multipass/issues/3476
@ricab 
I did not add `MULTIPASS_UPSTREAM` approach because I can not get it to work. 
I also attempted to make a dummy version number in the `determine_version` function. But it turns out there are more things to change than just one if statement. So I did not go down that route. 
So eventually I went with just suggesting the user run `git fetch --tags https://github.com/canonical/multipass.git`. If that is fine with you. Then @giuliazanchi can start the linguistics review.
=> [readme] added the special build instruction for forked repo developer.

.github/workflows/linux.yml
Multipass is currently using a lot of storage in GitHub workflows. This can easily be addressed by reducing the number of days that artifacts are retained.
Additionally, built packages are also uploaded to the snapcraft store which persist for a period of 30 days from the point of the last update to the channel.
https://snapcraft.io/docs/channels
=> [workflows] reduce retention time of snap packages

CMakeLists.txt, src/platform/backends/qemu/linux/CMakeLists.txt, src/platform/backends/qemu/linux/bridge_helper.c, src/platform/backends/qemu/linux/qemu_platform_detail.h, src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp, src/platform/backends/qemu/qemu_platform.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.cpp, src/platform/backends/qemu/qemu_virtual_machine_factory.h, src/platform/backends/qemu/qemu_vm_process_spec.cpp, tests/qemu/linux/test_qemu_platform_detail.cpp, tests/qemu/mock_qemu_platform.h, tests/qemu/test_qemu_backend.cpp, tests/qemu/test_qemu_vm_process_spec.cpp
Public side of [#647](https://github.com/canonical/multipass-private/pull/647)
The spec for this feature can be found [here](https://docs.google.com/document/d/1UAZgCHHjdY_RmYCIir-p9sDpa2M7uRP7P81Tx2qM0c8/edit).
This second version of QEMU network bridging was required because of the change in implementation of `find_bridge_with()`. Since most of bridged networks was already available on macOS/QEMU and implemented, this PR is mostly just for enabling and wiring up the function calls needed to create a network interface on Linux.
The key difference on Linux is the presence of `bridge_helper.c`. Below is an excerpt from the spec on the purpose of the bridge helper:
> Finally, to use bridges on QEMU, on Linux, we will use a bridge helper. The QEMU bridge helper,  shipped with QEMU, is a …
=> [linux/qemu] Qemu bridging v2

src/client/cli/cmd/start.cpp
Add a missing opening parenthesis in help text for `start`.
=> [cli] Fix typo in help text

src/client/cli/cmd/shell.cpp
=> clarify behavior of `multipass shell` in short_help and description

src/platform/backends/qemu/qemu_virtual_machine.cpp, tests/qemu/test_qemu_backend.cpp
Condense code to log mismatches between suspension snapshot and VM state. Just trying to reduce the space that is taken by logging code, which dilutes actual logic for the reader.
This could be further improved by adding a formatter for the State enum to `multipass/format.h`. That would be useful in other places too, but we should then probably also move the corresponding logic from the CLI formatters, so leaving that for now.
=> [qemu] Make logging code terser

src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, tests/qemu/test_qemu_backend.cpp
Downgrades log levels when forcing a shutdown. This way we still get logs from the vm process, but they are not shown to the user through the CLI.
Fixes #3591
=> [qemu] silence force stop logs

src/platform/backends/qemu/qemu_virtual_machine.cpp, tests/qemu/test_qemu_backend.cpp
=> correct the condition check of suspended vm on force stop

3rd-party/libssh/CMakeLists.txt, tests/libvirt/test_libvirt_backend.cpp
close #3558
A minimalistic example to reproduce this is to have an executable in Multipass CMake environment links to `Qt6::Network` and `ssh` where `ssh` target is built by the git submodule library libssh of multipass. 
The problem here is that the executable links to `libQt6Network.so.6.4.2->libcurl-gnutls.so.4->libssh.so.4` and 3rd-party libssh. So there are two libssh shared libraries linked to the same executable. Symbol versioning is a mechanism used in shared libraries to manage changes in the library API over time. In this case, the system libssh has the symbol version that linker is looking for but 3rd-party one does not have. Besides, the linker apparently is looking into the 3rd-party libssh for the functions he needs as opposed to the system libssh. 
So one possible fix for …
=> fix the linker error on ubuntu 24.04

src/daemon/daemon_init_settings.cpp, tests/test_global_settings_handlers.cpp
=> intercept `val` in driver_interpreter and remove capitals

src/client/gui/lib/vm_table/vm_table_headers.dart
=> [gui] when clicking the select all checkbox, respect instance filters

src/client/cli/cmd/info.cpp, src/client/gui/lib/grpc_client.dart, src/client/gui/lib/main.dart, src/client/gui/lib/notifications/notification_entries.dart, src/client/gui/lib/providers.dart, src/client/gui/lib/settings/general_settings.dart, src/client/gui/lib/update_available.dart, src/daemon/daemon.cpp, src/rpc/multipass.proto
This PR adds a notification if there is a Multipass update available.
There is also a refactoring for the update entry in the settings page.
=> Show in-app notification if an update is available

src/client/gui/lib/main.dart, src/client/gui/linux/flutter/generated_plugin_registrant.cc, src/client/gui/linux/flutter/generated_plugins.cmake, src/client/gui/macos/Flutter/GeneratedPluginRegistrant.swift, src/client/gui/pubspec.lock, src/client/gui/pubspec.yaml, src/client/gui/windows/flutter/generated_plugin_registrant.cc, src/client/gui/windows/flutter/generated_plugins.cmake
close #3590 
We can use the window_size flutter plugin from google's flutter desktop embeddings repository https://github.com/google/flutter-desktop-embedding/tree/main/plugins/window_size
to check the size of the screen, and 
- if the size of the screen is below 1600x900, open a small 750x450 window
- if the size of the screen is larger then open the 1400x822 window that multipass is currently set to by default. We can also think of more reactive functionality than this but I don't think it's necessary. 
We'll need to add this plugin to pubspec.yaml, but it's ~an official plugin from Google~ the closest-to-official Flutter plugin that handles screen size and it seems that the only reason that this plugin needs to be added at all is because Google has not yet added this functionality to …
=> change window minimumSize to 750x450, and default size based on screen resolution 

debian/control
`curl` is required by `vcpkg` to function correctly, and without it installed on the Linux system, vcpkg fails at the `cmake ../` step. curl is not installed by default on e.g. a fresh Ubuntu 22.04 minimal installation.
=> add `curl` to build dependencies in debian/control

src/client/gui/lib/main.dart, src/client/gui/lib/tray_menu.dart
resolve #3667 
`windowManager.restore()` calls gtk_window_deiconify as well as gtk_window_present https://docs.gtk.org/gtk3/method.Window.deiconify.html
In my testing, this has made it so "Open in Multipass" for an instance either
- opens the Multipass window (if keyboard focus is not stolen), or 
- shows the " is ready" dialog if typing focus is on another app 
100% of the time, and fixes the issues seen from #3667 without needing to fork the flutter window_manager plugin
=> call windowManager.show() and windowManager.restore() together as an extension

include/multipass/virtual_machine.h, src/client/cli/cmd/delete.cpp, src/client/cli/cmd/stop.cpp, src/daemon/daemon.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.cpp, src/platform/backends/libvirt/libvirt_virtual_machine.h, src/platform/backends/lxd/lxd_virtual_machine.cpp, src/platform/backends/lxd/lxd_virtual_machine.h, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, src/platform/backends/shared/base_virtual_machine.cpp, src/platform/backends/shared/base_virtual_machine.h, tests/libvirt/test_libvirt_backend.cpp, tests/lxd/test_lxd_backend.cpp, tests/mock_virtual_machine.h, tests/qemu/test_qemu_backend.cpp, tests/stub_virtual_machine.h, tests/test_base_virtual_machine.cpp, tests/test_cli_client.cpp
close #3624
close #3606
A few things were done based on our team discussion
1. skip_states check in `daemon.cpp` was removed because it is the responsibility of `VirtualMachine::shutdown` function to check the state. 
2. delegate the cmd suggestion part of the error message to CLI client. The daemon maps `VMStateInvalidException` exception to `grpc::StatusCode::FAILED_PRECONDITION`, and the CLI side interprets this code respectively. 
3. The force boolean input parameter of function `VirtualMachine::shutdown` is replaced by a 3 values enum `ShutdownPolicy`, corresponding refactor was performed as well.
Functional testing:
Please at least cover the following scenarios:
1. `multipass stop` on a deleted or non-existing VM does not trigger the `--force` suggestion
2. `multipass stop` on a VM …
=> Fix the bug where VirtualMachine::shutdown function throw affects multipass delete

src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h, tests/qemu/test_qemu_backend.cpp
Small cleanup:
- Moved common stub monitor to `test_qemu_backend` constructor
- Some tests were using a mock object but were not mocking function calls, so replaced with stub object
- Removed a couple instance variables from the qemu virtual machine class as they are simply copies of members from the already saved `VirtualMachineDescription`
=> small qemu improvements

src/client/cli/cmd/restart.cpp, src/daemon/daemon.cpp, tests/test_daemon_start.cpp
Partial fix for #3672, unable to reproduce `start` behavior. 
When running `restart` with a new version of Multipass available, no notification would be shown but the field is present in the gRPC reply.
This PR makes it so the daemon properly populates that field for `restart` and has the CLI respond to it.
=> Fix `restart` not showing new version

src/platform/backends/qemu/qemu_virtual_machine.cpp, tests/qemu/test_qemu_backend.cpp
resolves #2907 
When running `stop` on an instance that could not be stopped no error would be reported. This was because `QemuVirtualMachine::shutdown(force=false)` ignored the result of `vm_process->wait_for_finished(shutdown_timeout)` which indicates if a timeout occurred or not. This issue does not seem to be present in other VM backends.
This PR makes it so the timeout is not ignored and the timeout is properly reported.
=> Fix `stop` succeeding when instance isn't stopped

tests/linux/test_platform_linux.cpp
Previously the following tests could fail when a user did not have permissions for ip related processes
- `PlatformLinux.test_default_driver_produces_correct_factory`
- `PlatformLinux.test_explicit_qemu_driver_produces_correct_factory`
- `PlatformLinux.test_libvirt_in_env_var_is_ignored`
Since these tests are not meant to fail for this case, these failures are unwanted. To resolve the issue, mocking the DNSMasqServerFactory allows the tests to focus more on testing the driver factories.
=> Increase robustness of driver factory tests

src/daemon/daemon.cpp, src/platform/backends/qemu/qemu_virtual_machine.cpp, src/platform/backends/qemu/qemu_virtual_machine.h
resolves #3279 
There are several sources of crashes when running `delete -p` and `start` at the same time.
One source stems from a race condition in the daemon involving multiple reads and writes to `operative_instances` concurrently. The crash source is from a callback created in `on_restart` which can unsafely write into `operative_instances` if the instance has been deleted. A workaround is to ensure this is always a read operation and catching the resulting error, but this still causes UB and puts the thread in a corrupt state. Preventing the callback or having safe access into the `operative_instances` map would be better.
Another is from callbacks in the `QemuVirtualMachine` which are called during or after the destruction of the VM instance. This is addressed by disconnecting the …
=> Fix crash when purge deleting while starting

3rd-party/libssh/CMakeLists.txt, 3rd-party/submodule_info.md
In response to various [issues](https://github.com/canonical/multipass/issues/3727), reverts to the previously used version of libssh.
=> Revert libssh update

include/multipass/utils.h, src/daemon/daemon.cpp, src/utils/utils.cpp, tests/mock_utils.h
This PR adds the functionality for the daemon to choose a mount target path if it is not given. Right now the logic is to take the last directory name in the source path and append it to `/home/ubuntu` e.g. given the source path `/home/andrei/projects/multipass`, the default target path would be `/home/ubuntu/multipass`
=> [daemon] let daemon choose mount target if not specified

include/multipass/dart_ffi.h, src/client/cli/cmd/mount.cpp, src/client/gui/ffi/dart_ffi.cpp, src/client/gui/lib/ffi.dart
This PR makes the logic of computing a mount target path from a source path available in the FFI library that we use from Dart. This is so that the GUI can show a preview of what a target path will be before actually sending the request to the daemon.
=> [gui] add ffi for getting mount target from source

src/client/cli/cmd/mount.cpp
This PR simply removes the responsibility of the CLI to choose a mount target path if it is not given, since that will now be the responsibility of the daemon. Thus, the CLI can now pass an empty target path to the daemon.
=> [cli/mount] remove default target if not specified

src/client/gui/lib/providers.dart
Providers only update on new data. Built collections provide deep equality comparison. But in our case, we want vm info providers to update even if the data is the same. For example, a stopped vm will emit the same info, so CPU sparkline does not update because of that. So this PR makes providers emit regular collections, which do not provide deep equality, so this makes the GUI update even if the data that comes from a vm is the same. This could also be optimized with more granular updates in the needed providers, if we notice the need for more performance.
=> [gui] make info providers update even if data is equal

src/client/gui/pubspec.lock, src/client/gui/pubspec.yaml
Via a fork of the flutter xterm.dart plugin, editing ui/render.dart
=> Ensure terminal doesn't render partial lines & Snap terminal scrolling to line height

src/client/gui/lib/notifications/notification_entries.dart
Fixes launch success notification typo. Previously it said `You can start using using it now`. Now it says `You can start using it now`.
=> Fix typo in launch success notification

renovate.json5
This PR makes the renovate bot run only every two weeks on Monday, and it also moves the config file to JSON5 so that it can support trailing commas.
=> [ci] make the renovate bot run only every 2 weeks

.github/workflows/sync-gh-jira.yaml
It goes with a github secret, a Jira action and a webhook.
MULTI-1561
=> Add automation to sync Github issues to Jira

src/daemon/daemon.cpp, src/platform/backends/shared/base_snapshot.cpp, tests/json_test_utils.cpp, tests/json_test_utils.h, tests/test_base_snapshot.cpp, tests/test_daemon.cpp, tests/test_daemon_launch.cpp
Previously CI could fail while writing to JSON files, especially in snapshot tests. Now, snapshot tests and many daemon tests minimally rely on the filesystem so the chance of spurious filesystem failures should be reduced.
MULTI-1230
=> Reduce spurious CI test failures

src/network/CMakeLists.txt, src/network/url_downloader.cpp, tests/test_url_downloader.cpp
The enum for timeouts in Qt's networking library is `QNetworkReply::TimeoutError`. Different logs are printed at debug, warning, and error levels.
MULTI-1529
=> log all QNetworkReply error messages at debug level

src/client/cli/cmd/launch.cpp, src/client/cli/cmd/mount.cpp
Now we use a different way of deriving the target path of a mount based on the source path, if the target path is not explicitly specified. We take the directory name of the source and use it under `/home/ubuntu` in the instance.
For example, for a source path `/abc/def/ghi` the corresponding default target is `/home/ubuntu/ghi`
=> [cli] update messages to clarify default mount target

src/client/gui/pubspec.yaml
GUI version must be updated manually, unfortunately...
=> [gui] set version to 1.15.0

CMakeLists.txt
Now that CI runners are on MacOS 12, bump the CMake project minimum MacOS version up to 12.
=> [cmake] bump macos project version

src/client/gui/lib/main.dart
Some Macbooks and other small laptops have resolutions such as 1440x900 or 1366x768 that are below the threshold for the "large" GUI resolution of 1400x822's minimum screen size of 1600x900, but the default (minimum) of 750x450 is too small. 
This PR updates the startup application window size logic in main.dart to add an intermediate 1024x576 resolution for smaller screens,
It now sets the window size to 1400x822 for screens 1600x900 or larger, 1024x576 for screens 1280x720 or larger, and defaults to 750x450 otherwise.
=> add 1024x576 as an intermediate GUI resolution for smaller screens

CMakeLists.txt
Fix the pattern for excluding build dir files from the coverage report. Without this, nothing matches the build dir pattern given to `lcov` (at least with my version).
I suppose Codecov knows to exclude anything that is not part of the repo, which would explain why its results are not impacted.
Local test recipe, from build directory:
1. `cmake -DCMAKE_BUILD_TYPE=Coverage ...`
2. `cmake --build . --target covreport`
3. `xdg-open coverage/index.html`
=> [cmake] Fix exclusion of build files from coverage

renovate.json5
Unfortunately, this means that @jibel will get the occasional review request. 
But, I think this is a better approach than manually listing all Multipass developers and having to maintain it when developers join/leave.
P.S. and @giuliazanchi!
=> [renovatebot] Auto assign random reviewer from Multipass GitHub team

src/client/cli/cmd/launch.cpp
Minor update to add a missing "." at the end of the help text for the --mount option.
=> Update launch.cpp help text

src/client/gui/lib/platform/linux.dart, src/client/gui/lib/platform/macos.dart, src/client/gui/lib/platform/windows.dart, src/client/gui/lib/vm_details/terminal.dart, src/client/gui/lib/vm_details/terminal_tabs.dart
This PR adds the ability to change the font size in the GUI terminals, using common shortcuts like `Ctrl`+`+` to increase, `Ctrl`+`-` to decrease and `Ctrl`+`0` to reset. `Command` is used instead of `Ctrl` on macOS.
It also include two small, drive-by fixes, which change the deprecated `MaterialStateColor` with the newer `WidgetStateColor`. Those were done because they were in the same files as the other, relevant changes.
MULTI-1678
=> Terminal zoom

tests/mock_process.cpp, tests/test_basic_process.cpp
fixes #3787 
Some `EXPECT`s should've been `ASSERT`s because of getting value of `std::nullopt`
Windows compiled with debug has different behavior from release builds, this has been fixed for the tests.
MULTI-1652
=> Fix basic process tests on Windows

include/multipass/utils.h, src/platform/platform_linux.cpp, src/sshfs_mount/sftp_server.cpp, src/utils/utils.cpp, tests/test_utils.cpp
Fixes #3759 
Previously, mount targets and sources were not escaped. This caused strange targets and mounts like `" & mkdir hello & "` to be able to execute commands in the instance. Now they are properly escaped so strangely named directories like `" & mkdir hello & "` will work as source or target. 
MULTI-1675
=> Escape mount sources and targets

include/multipass/console.h, include/multipass/terminal.h, src/client/cli/cmd/exec.cpp, src/client/cli/cmd/shell.cpp, src/platform/console/console.cpp, src/platform/console/unix_terminal.cpp, src/platform/console/unix_terminal.h, tests/mock_terminal.h, tests/stub_terminal.h, tests/test_cli_client.cpp, tests/unix/test_unix_terminal.cpp
Fixes #3788 
Previously the test output would disappear since `StubTerminal*` was being cast to `WindowsTerminal*` and then `cin`/`cout`/`cerr` would get deleted. Now `StubTerminal*` is not cast at all and `Console` creation is handled by their respective Terminals.
MULTI-1676
=> Fix console creation

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/workflows/linux.yml, README.md, src/client/gui/lib/help.dart, src/client/gui/lib/update_available.dart, src/daemon/daemon.cpp, src/platform/update/new_release_monitor.h
The multipass.run "microsite" is being replaced canonical.com/multipass. We need to update our URLs accordingly.
Fixes #3839
MULTI-1707
=> Replace multipass.run with canonical.com/multipass

src/client/gui/lib/grpc_client.dart, src/client/gui/lib/providers.dart
we have bidirectional streaming rpcs, but we usually send only one response back on that stream for most operations. therefore, the gui would only read data from the stream until it got the first reply. but this introduced errors in which the stream was disposed too early. now we read everything from the stream, so that issue shouldn't happen.
=> Fix `Connection is being forcefully terminated` error in GUI

src/client/gui/lib/providers.dart, src/client/gui/lib/vm_details/terminal.dart
Now, if the VM is in a state from which it can be started (`Stopped` or `Suspended`), the `Open shell` button will be enabled and it will start the VM before shelling into it.
MULTI-1681
=> `Open shell` button starts the VM if needed

.github/actions/lint/action.yml
Lint action is broken because it can't find clang-format-12.
Fix stolen from [here](https://github.com/canonical/multipass/pull/3845/files#diff-b75b025d551d3387aae641b07b3d675985802e588607716e79373d0c3adceae8). Thanks, @georgeliao!
=> [ci] update clang-format to 16

vcpkg.json
Updated the vcpkg from 2023.10.19~628 to 2024.02.14. This small update does not leap vcpkg to the latest version which is 2024.12.16, but it can fix the windows build without breaking the old grpc build.
=> updated vcpkg to 2024.02.14

src/client/gui/lib/platform/linux.dart, src/client/gui/lib/platform/windows.dart, src/client/gui/lib/vm_details/terminal.dart
This PR adds Ctrl+Insert and Shift+Insert as copy/paste shortcuts for the terminal on Windows, as well as adding a right-click context menu in the terminal that provides copy/paste functionality.
It also refactors some of the terminal code by extracting some nested widgets into separate variables, since the nesting level was getting too big.
MULTI-1679
=> Copy paste improvements

src/platform/backends/qemu/qemu_vm_process_spec.cpp
Fix #3834
Possible explanation on the behavior we saw. 
1. The original code just added  `%4/bin/bridge_helper` without any permissions. The behavior for this case is the bridging feature can run with the permissions it needs and the mount folder lost its write permission somehow. The reason behind this is that `bridge_helper` operates in the unrestricted mode when no permissions are specified, meaning that it inherits all permissions and capabilities from the parent process. That is why the bridging feature is able to run. When AppArmor is in unrestricted mode (`%4/bin/bridge_helper` without explicit permissions), the mode may interfere with the rule order in the profile. More specifically, it can result in mounted folder permissions which is defined later in this profile being …
=>  Fix the snap qemu native mount regression

.gitignore
This PR updates the .gitignore file to include the `.vs` and `.vscode` folders. These folders contain IDE-specific configuration files created by Visual Studio and Visual Studio Code, similar to the `.idea` folder for JetBrains IDEs that is already currently in the gitignore.
=> add Visual Studio and VSCode project configuration directories to gitignore

.github/actions/lint/action.yml
Work done by @rico33631 in #3873
=> [ci] add flutter linting to lint/action.yml

3rd-party/libssh/CMakeLists.txt, 3rd-party/submodule_info.md, include/multipass/platform.h, include/multipass/platform_unix.h, include/multipass/ssh/ssh_session.h, src/platform/console/unix_console.cpp, src/platform/platform_unix.cpp, src/ssh/ssh_session.cpp, src/sshfs_mount/sshfs_mount.cpp, src/sshfs_mount/sshfs_mount.h, src/sshfs_mount/sshfs_server.cpp, tests/unix/mock_signal_wrapper.h, tests/unix/test_platform_unix.cpp
Sets the timeout to infinite since no messages for extended periods of time is expected behavior. Libssh updated to fix timeout being ignored.
Sets the pty mode explicitly to default since Libssh updated to inherit settings from `stdin`.
Fixes #3745
MULTI-1528
=> Update libssh to 0.11.1

src/client/gui/linux/flutter/generated_plugin_registrant.cc, src/client/gui/linux/flutter/generated_plugins.cmake, src/client/gui/macos/Flutter/GeneratedPluginRegistrant.swift, src/client/gui/pubspec.lock, src/client/gui/pubspec.yaml, src/client/gui/windows/flutter/generated_plugin_registrant.cc, src/client/gui/windows/flutter/generated_plugins.cmake
=> Upgrade Flutter to 3.27 and upgrade its dependencies as well

include/multipass/file_ops.h, include/multipass/vm_image_vault.h, include/multipass/vm_image_vault_utils.h, src/daemon/default_vm_image_vault.cpp, src/platform/backends/lxd/lxd_vm_image_vault.cpp, src/platform/backends/shared/base_vm_image_vault.h, src/utils/file_ops.cpp, src/utils/utils.cpp, src/utils/vm_image_vault_utils.cpp, src/xz_decoder/xz_image_decoder.cpp, tests/CMakeLists.txt, tests/mock_file_ops.h, tests/mock_image_decoder.h, tests/mock_image_vault_utils.h, tests/test_file_ops.cpp, tests/test_image_vault_utils.cpp, tests/test_utils.cpp
This PR refactors several functions related to image vault utilities. All util functions now have unit test coverage and can be mocked to ease testing for components that use the utilities. Some functions have been removed or moved to file_ops since they already exist or fit better there.
MULTI-1653
=> Refactor image vault utils

.github/ISSUE_TEMPLATE/bug_report.md
I find that it would often be useful to have this information from the beginning.
=> Add a CPU architecture/model field to the bug-report template

include/multipass/file_ops.h, include/multipass/path.h, include/multipass/platform.h, include/multipass/utils.h, src/daemon/daemon_config.cpp, src/platform/platform_linux.cpp, src/platform/platform_unix.cpp, src/ssh/sftp_client.cpp, src/sshfs_mount/sftp_server.cpp, src/utils/file_ops.cpp, src/utils/utils.cpp, tests/linux/test_platform_linux.cpp, tests/mock_file_ops.h, tests/mock_platform.h, tests/mock_utils.h, tests/test_client_cert_store.cpp, tests/test_daemon.cpp, tests/test_file_ops.cpp, tests/test_sftp_client.cpp, tests/test_sftpserver.cpp, tests/unix/test_platform_unix.cpp
This PR removes `chmod` from `Platform.h` as well as functions that are similar in `file_ops.h`. They have all been changed to use `MP_PLATFORM.set_permissions`. This should not change behavior on Unix systems. On Windows this changes the behavior to modify ACLs as well as DOS permissions instead of just DOS permissions.
MULTI-1420
=> Remove chmod and duplicated permissions functions

src/cert/CMakeLists.txt
```
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-gnu’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-nested-anon-types’ may have been intended to silence earlier diagnostics
```
The original implementation uses `check_cxx_compiler_flag`, and the cmake function does not seem to return the expected `SUPPORTED` value. As a result, `-Wno-nested-anon-types -Wno-gnu` two warnings flags that are clang-only can pass gcc check and get appended to gcc. To verify this, `make clean && make cert` in the linux + gcc environment will show the message above. The fix is simple as well, append the flags explicitly to respective compilers. 
https://warthogs.atlassian.net/browse/MULTI-1766
=> [compiler] fix the wrongly appended warning flags on gcc compiler.

src/client/gui/pubspec.lock, src/client/gui/pubspec.yaml
Before, this dependency had no license at all. Now it has a LGPL3 license, so we should include that as well.
=> [gui] update tray menu dep so that it has a license

src/client/gui/windows/runner/flutter_window.cpp
Previously the GUI would always crash when the GUI is closed. This PR makes it so the GUI does not crash when it is closed. The issue was due to destructor call ordering for the GUI Window. FlutterWindow (subclass of Win32Window) would begin destruction which destructs the FlutterViewController and then the Win32Window base class. The FlutterViewController is registered to a Windows callback that is removed when Win32Window is destructed, but since the FlutterViewController gets destructed before the Win32Window there is some time where the callback is still active but the FlutterViewController is in an invalid state.
MULTI-1711
=> Fix Windows GUI crash on close

3rd-party/xz-decoder/CMakeLists.txt
Fix #3898 by enabling `-fPIC` for the 3rd-party dep  `xz-embedded`. @ricab
=> fix #3898 by adding -fPIC to xz-embedded

src/client/gui/lib/copyable_text.dart, src/client/gui/lib/tooltip.dart, src/client/gui/lib/vm_details/ip_addresses.dart, src/client/gui/lib/vm_details/vm_details_general.dart, src/client/gui/lib/vm_table/vm_table_headers.dart
closes https://github.com/canonical/multipass/issues/3821
This pull request introduces a new `CopyableText` widget and updates several components to use this widget for improved text copy functionality. Additionally, it modifies the `Tooltip` widget to be stateful to handle dynamic changes in the tooltip message.
New `CopyableText` widget:
* [`src/client/gui/lib/copyable_text.dart`](diffhunk://#diff-807730c5b270aaec0c016a8cd65a89c673ffaf2001e8925b07d3561e27ea48f0R1-R48): Created a new `CopyableText` widget that allows text to be copied to the clipboard with a click and displays a tooltip indicating the copy status.
Updates to `Tooltip` widget:
* [`src/client/gui/lib/tooltip.dart`](diffhunk://#diff-5665636198f18253cea1d1c8687fe9ee297ee52a18c32c76855bb3bf8c840d96L3-R3): Changed `Tooltip` …
=> use CopyableText (click-to-copy) in GUI for instance info

include/multipass/platform_unix.h, src/platform/platform_unix.cpp, tests/unix/test_platform_unix.cpp
Small drive by fixes that I noticed while reviewing #3735 (which this is based on).
=> Unix drive-by tweaks

src/ssh/sftp_client.cpp, tests/test_sftp_client.cpp
Fixes the issue of `multipass transfer` only transferring some chunks of the file. This uses `sftp_limits` instead of the constant `65536u` to determine the correct buffer size for SFTP reads and writes.
Fixes #3892 
MULTI-1768
=> Fix transfer only partially transferring

src/client/gui/lib/platform/linux.dart, src/client/gui/lib/platform/windows.dart
fixes #3887 
This pull request resolves an issue on keyboards that have the + key as lowercase, such as German layout keyboards. Previously, we were always checking for shift to be pressed as well as control for <Ctrl><+> since + can only be made by holding shift on US layout keyboards. There is a dedicated LogicalKeyboardKey in Flutter for this lowercase "add" key.
Keyboard shortcut additions:
* [`src/client/gui/lib/platform/linux.dart`](diffhunk://#diff-8d945490628ab65a2dee4475abb3c1a7fe4302438c68de63890dafe66502179cR44-R45): Added a new keyboard shortcut `SingleActivator(LogicalKeyboardKey.add, control: true)` to increase terminal font size.
* [`src/client/gui/lib/platform/windows.dart`](diffhunk://#diff-4ea20cca689dd319ac27577691743b87a135a8c44c07d617d58dc0ec6d33d8c0R46-R47): Added a …
=> add shortcut for + key without shift needed

snap/snapcraft.yaml
Scrape license files that either:
- Have a name starting with LICENSE, or
- Have a full path that contains /LICENSE/
MULTI-1763
=> [snapcraft] Scrape files with LICENSE or full path contains LICENSE

docs/conf.py, docs/explanation/authentication.md, docs/explanation/mount.md, docs/how-to-guides/customise-multipass/configure-multipass-default-logging-level.md, docs/how-to-guides/customise-multipass/configure-multipasss-default-logging-level.md, docs/how-to-guides/customise-multipass/configure-where-multipass-stores-external-data.md, docs/how-to-guides/customise-multipass/index.md, docs/how-to-guides/customise-multipass/set-up-a-graphical-interface.md, docs/how-to-guides/customise-multipass/set-up-the-driver.md, docs/how-to-guides/index.md, docs/how-to-guides/install-multipass.md, docs/how-to-guides/manage-instances/index.md, docs/how-to-guides/manage-instances/use-instance-command-aliases.md, docs/how-to-guides/troubleshoot/access-logs.md, docs/how-to-guides/troubleshoot/index.md, docs/reference/command-line-interface/index.md, docs/reference/gui-client.md, docs/reference/index.md, docs/reference/logging-levels.md, docs/tutorial/index.md
- Changed MyST syntax to render tabs
- Improved labels in the navigation tree
- Fixed two broken image links (asset manager)
- Fixed order of pages in the navigation tree (now it's the same as in https://canonical.com/multipass/docs)
- Updated `conf.py` to display the "Give feedback" button on all pages
NOTE: To build the docs locally, go in the `/docs/` folder and run the command `make run`.
=> Small fixes to docs structure

docs/how-to-guides/customise-multipass/build-multipass-images-with-packer.md, docs/tutorial/index.md, tests/CMakeLists.txt, tests/test_log.cpp
This MP adds log level to string unit test case to ensure all cases are covered.
The MP also includes the commits from https://github.com/canonical/multipass/pull/3944 to resolve cyclic dependency between the two branches causing a CI failure
[giuliazanchi] Fixed link to Multipass Discourse landing page
MULTI-1831
=> [tests] add log level to string unit tests

.clang-format
Tiny PR to ensure that we end files with a newline. See the [POSIX definition of a line](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap03.html#tag_03_185).
=> [format] Ensure proper ending of the last line

.github/.jira_sync_config.yaml
Tweak mappings in the Jira bot config to:
- closed as not planned on GH ➡ rejected in Jira
- enhancements on GH ➡ stories in Jira
=> Tweak Jira bot

.clang-format, .github/actions/lint/action.yml
The CI lint action does not detect invalid syntax in the .clang-format file if the pull request does not contain any code changes.
This patch corrects the `Standard` value and adds a `clang-format --dump-config` run to ensure that the .clang-format is syntatically valid.
=> [ci/clang-format] fix the language standard string

src/client/gui/lib/catalogue/launch_form.dart, src/client/gui/lib/grpc_client.dart, src/client/gui/lib/settings/virtualization_settings.dart, src/client/gui/lib/switch.dart, src/client/gui/lib/vm_details/vm_details_bridge.dart
This PR introduces the following changes:
- when launching an instance with some mounts specified, if the reply stream of the launch RPC yielded an error, the launch operation would not end early, and it would proceed to attempt the mounts. now, instead of yielding directly from the launch reply stream, we use `await for` to iterate over the stream and manually yield the replies. this turns errors from the stream into exceptions that are thrown, interrupting the launch process early, so mounts are no longer attempted
- we now allow our custom `Switch` to be conditionally disabled. there were also some minor changes to it, related to using newer styling properties in place of deprecated ones, with no effect to visuals
- in the launch form, we check if a bridged network was set correctly, …
=> Fix gui launch bridged error

docs/how-to-guides/troubleshoot/troubleshoot-networking.md
This PR removes a duplicated block of content that was previously moved to `troubleshoot-launch-start-issues.md`, and adds a link to this new troubleshooting page.
=> Minor fixes to troubleshoot-networking.md

include/multipass/logging/log.h, tests/test_log.cpp
the most usual case for a log() call is to produce a log message using `fmt::format()`. the new log() variadic template function streamlines that by providing the formatting by default with minimal intrusion. The old log() API is preserved as-is -- the new code can opt in using the new log() API by passing a format string and format arguments directly:
before
```c++
mpl::log(lvl::debug, "cat", fmt::format("{} {}", 1, 2)); // uses the existing log() overload
```
after
```c++
mpl::log(lvl::debug, "cat", "{} {}", 1 ,2); // uses the new variadic overload
```
The new log() function also uses fmt::format_string<...> to capture the format string argument which means the code will get compile time format string checks for free when the codebase switches to C++20.
MULTI-1844
=> [log] introduce log function w/ formatting

.github/workflows/linux.yml
The BuıldAndTest(Debug) step crashes intermittently without any significant clue for us to pursue. The crash does not happen in the local environment so the best next thing is to grab the core dump & crashed executable and upload them to artifacts so we can investigate them.
MULTI-1845
=> [ci/BuildAndTest]: upload test coredump to artifacts on crash

docs/conf.py
... to fix the warning:
WARNING: conf.py setting 'github_folder' is deprecated. Use 'repo_folder' instead.
MULTI-1856
=> [docs/conf.py] replace "github_folder" key with "repo_folder"

include/multipass/exceptions/formatted_exception_base.h, tests/CMakeLists.txt, tests/test_exception.cpp
FormattedExceptionBase is a generic base class type that produces a formatted string and passes it to the base class. This is a common occurrence in the codebase, so this class is designed to address that.
FormattedExceptionBase can be used with any type that derives from std::exception and has a std::string constructor.
The class gracefully handles format errors to not incur a `std::terminate()`.
MULTI-1854
=> [exceptions] add FormattedExceptionBase type

tests/test_sshfsmount.cpp
make_exec_to_check_commands is not checking whether the optional object contains an optional or not. the patch fixes that.
=> [test_sshfsmount] fix invalid optional access in helper function

include/multipass/logging/log.h, tests/test_log.cpp
Added the following templated log functions: error, warn, info, debug, trace.
Added a templated log overload, which takes the log level as a template parameter. This function acts as a dispatcher for calls with/without a format.
Moved non-templated function declarations to the top.
Unit tests were added for the new log-level functions.
Prefixed all log() calls with logging:: namespace so log() from math library does not get pulled into overload resolution candidates.
MULTI-1853
=> [log] introduce mpl::<level-name>(...) log functions

src/ssh/ssh_session.cpp
Sometimes, ssh_connect blocks while a VM is booting up, where it won't return to the caller at all. Since the timeout is set to ~infinity the ssh_connect would block forever.
This patch fixes that by using two different timeout values for the different session connection states.
MULTI-1863
=> [ssh/ssh_session] different timeouts for connect & established

.github/workflows/linux.yml
one-by-one file pulling was breaking when the file included whitespace characters. this patch switches to pulling the whole coredumps folder to simplify the code. 
also added a fix for pull coredump step not triggering when the segfault happens in the coverage step.
MULTI-1875
=> [ci/BuildAndTest] pull the coredump folder as a whole

src/client/cli/cmd/common_callbacks.h
The make_confirmation_callback function takes the key argument as const ref, meaning that it'll be bound to an existing QString when the arg is QString, but a temporary QString would be constructed and bound to it when the "key" is not a QString. This is fine during the make_confirmation_callback's scope since const& extend the lifetime of the temporary, but passing that "const&" to a capture list of a lambda that'll be executed later does not extend the lifetime, hence leading to undefined behavior.
I believe this was not causing any issues in release builds because of the optimization level. The compiler is probably inlining the whole thing, so the QString is directly constructed into the lambda's body. I could only trigger this while running the unit tests in Windows, built with the …
=> [common_callbacks] fix make_confirmation_callback lifetime issue

src/client/cli/cmd/exec.cpp, tests/test_cli_client.cpp
<details>
<summary>fixes #3933 </summary>
I had to run the `sudo concierge prepare -p dev --extra-snaps terraform` command twice whether I was shelled in with `multipass shell` or using `multipass exec`. Running `multipass exec juju-dev -- sudo env | grep SUDO_` gives the correct SUDO environment variables
```text
~/CLionProjects/multipass/build$ ./bin/multipass launch noble --disk 50G --memory 4G --cpus 2 --mount .  --name juju-dev
Launched: juju-dev
Mounted '.' into 'juju-dev:'
~/CLionProjects/multipass/build$ ./bin/multipass exec juju-dev -- sudo snap install concierge --classic
concierge 0.11.1 from Jon Seager (jnsgruk✪) installed
frame@frame-laptop:~/CLionProjects/multipass/build$ ./bin/multipass exec juju-dev -- sudo concierge prepare -p dev --extra-snaps terraform …
```
=> `exec` runs sudo commands with `-u` to preserve user

include/multipass/network_interface_info.h, src/platform/CMakeLists.txt
Author: @rshrj
This MP contains two external MPs:
https://github.com/canonical/multipass/pull/4008:
> This PR fixes an issue in `src/platform/CMakeLists.txt` where `add_compile_definitions()` is used with a `-D` prefix:
> 
> ```cmake
> add_compile_definitions(-DMULTIPASS_JOURNALD_ENABLED)
> ```
> 
> This results in a malformed macro definition `-D-DMULTIPASS_JOURNALD_ENABLED`, which causes a compiler error:
> 
> ```shell
> <command-line>: error: macro names must be identifiers
> ```
> 
> The fix is to pass only the macro name, as `add_compile_definitions()` automatically adds the `-D` prefix:
> 
> ```cmake
> add_compile_definitions(MULTIPASS_JOURNALD_ENABLED)
> ```
>
> Tested in a clean Debian 12 environment using Make, where this issue was originally triggered. …
=> Fix invalid macro definition and add <tuple> include

src/platform/CMakeLists.txt
This PR fixes an issue in `src/platform/CMakeLists.txt` where `add_compile_definitions()` is used with a `-D` prefix:
```cmake
add_compile_definitions(-DMULTIPASS_JOURNALD_ENABLED)
```
This results in a malformed macro definition `-D-DMULTIPASS_JOURNALD_ENABLED`, which causes a compiler error:
```shell
<command-line>: error: macro names must be identifiers
```
The fix is to pass only the macro name, as `add_compile_definitions()` automatically adds the `-D` prefix:
```cmake
add_compile_definitions(MULTIPASS_JOURNALD_ENABLED)
```
Tested in a clean Debian 12 environment using Make, where this issue was originally triggered.
=> Fix invalid macro definition in CMakeLists.txt

include/multipass/network_interface_info.h
This PR adds a missing `#include <tuple>` to `network_interface_info.h`, which is required for the use of `std::tie`.
Without this include, builds fail on compilers/environments that do not implicitly include `<tuple>` via transitive headers. For example, GCC on Debian 12 produces:
```shell
error: ‘tie’ is not a member of ‘std’
note: ‘std::tie’ is defined in header ‘’; did you forget to ‘#include ’?
```
Tested by successfully building the project in a clean Debian 12 dev container with GCC. No other changes.
=> Fix missing <tuple> include for std::tie in network_interface_info.h

3rd-party/CMakeLists.txt
With CMake 4.0, support for compatibility with versions older than 3.5 has been removed. One of our dependencies (yaml-cpp) defines its policy version as 3.4, so the build with CMake 4 fails for that reason.
There's an option to override that behavior, called CMAKE_POLICY_VERSION_MINIMUM. This flag suppresses the error and allows CMake to try building the project anyway. yaml-cpp builds without any issues when the option is in place. The upstream also updated the cmake_minimum_required() to `3.4...3.14` without making any code changes, so it's safe to assume that the project is compatible with the CMake 3.5 policies.
https://github.com/jbeder/yaml-cpp/commit/c2680200486572baf8221ba052ef50b58ecd816e
MULTI-1919
=> [3rd-party/CMakeLists] Define CMAKE_POLICY_VERSION_MINIMUM=3.5

include/multipass/ssl_cert_provider.h, include/multipass/utils.h, snap/hooks/install, src/cert/client_cert_store.cpp, src/cert/ssl_cert_provider.cpp, src/client/common/client_common.cpp, src/daemon/daemon.cpp, src/daemon/daemon_config.cpp, src/daemon/default_vm_image_vault.cpp, src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp, src/platform/platform_linux.cpp, src/platform/platform_unix.cpp, src/ssh/openssh_key_provider.cpp, tests/linux/test_platform_linux.cpp, tests/test_cli_client.cpp, tests/test_client_common.cpp, tests/test_daemon.cpp, tests/test_daemon_find.cpp, tests/test_ssl_cert_provider.cpp
[MULTI-1765](https://warthogs.atlassian.net/browse/MULTI-1765)
Public side of https://github.com/canonical/multipass-private/pull/719
**A few things to note**
The `make_cert_key_pair` function originally handles the generation of both server and client key-certificate pairs . The `server_name` parameter determines the use case, when `server_name` is an empty string, it indicated the client key-certificate case. In the standard gRPC TLS scheme, the root key-certificate pair is added. 
Now, the role of the `make_cert_key_pair` function is still generating and holding server and client key-certificate pairs. However, the server certificate has evolved into a signed server certificate. As the result, the server side branch must first generate root key-certificate pair and use it to sign the …
=> Standard grpc mTLS 

src/client/gui/lib/platform/linux.dart, src/client/gui/lib/providers.dart, src/client/gui/lib/settings/virtualization_settings.dart
This PR removes libvirt from the list of drivers in the GUI. If a user has libvirt they will still be on libvirt, however, once they switch to a different driver libvirt will no-longer be selectable.
MULTI-1889
=> Remove libvirt driver from GUI

src/client/gui/lib/platform/linux.dart
This PR removes lxd from the list of drivers in the GUI. If a user has lxd they will still be on lxd, however, once they switch to a different driver lxd will no-longer be selectable.
MULTI-1894
=> Remove lxd driver from GUI

3rd-party/vcpkg-ports/poco/vcpkg.json
- Enforced pcre2 >= 10.43 for [cmake minimum version](https://github.com/PCRE2Project/pcre2/blob/3864abdb713f78831dd12d898ab31bbb0fa630b6/CMakeLists.txt#L108) compatibility with cmake 4.0
=> [vcpkg] Update deps for compatibility with cmake 4.0

src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/daemon_rpc.cpp, src/daemon/daemon_rpc.h, src/rpc/multipass.proto, tests/mock_client_rpc.h, tests/mock_daemon.h
This PR adds AZ information to RPC messages that need it, as well as methods for listing AZs and changing their state.
=> add daemon gRPC boilerplate for AZs

src/client/gui/pubspec.lock, src/client/gui/pubspec.yaml
I transferred my libs and forks from my ownership to Canonical's.
=> [gui] move git deps under canonical ownership

.github/actions/checkout/action.yml
The action claimed it checked out Multipass code, but that is actually
done elsewhere via the standard GitHub "checkout" action.
=> [ci] Fix description of custom checkout action

include/multipass/availability_zone.h, include/multipass/availability_zone_manager.h, include/multipass/exceptions/availability_zone_exceptions.h
This PR adds interfaces for AZs and for an AZ manager, as well as some AZ specific exceptions.
=> Az definitions

.github/workflows/linux.yml, CMakeLists.txt, README.md, src/cmake/configure-linker.cmake, src/cmake/environment-utils.cmake
`mold` and `lld` are usually several magnitudes faster compared to the default linker of the toolchains. This PR adds the configure_linker CMake function to automatically configure which linker to use based on availability of the "mold" and "lld" in the environment. The function is no-op below CMake 3.29 since the current implementation depends on a rather recent CMake variable, CMAKE_LINKER_TYPE.
The user can disable the auto linker selection by explicitly specifying the CMAKE_LINKER_TYPE at configure step, i.e.,:
cmake -DCMAKE_LINKER_TYPE=DEFAULT -S . -B build
The `configure_linker` is intended to be only run in non-CI environments. The `is_running_in_ci` determines whether the project is being built in a CI environment.
MULTI-1912
=> [project/cmake] add auto linker selection based on availability

include/multipass/qt_delete_later_unique_ptr.h, include/multipass/sshfs_mount/sshfs_mount_handler.h, src/platform/update/new_release_monitor.cpp, src/sshfs_mount/sshfs_mount_handler.cpp, tests/test_sshfs_mount_handler.cpp
Currently, the signal handlers outlast the process and the mount handler, which leads to undefined behavior.  
This resulted in a crash when I attempted to unmount an sshfs mount in Windows.  
This patch resolves the issue by ensuring that all connected signals are disconnected in the destructor.
Also modernized the mpl::log calls while at it.
MULTI-1873
=> [sshfs-mount-handler] ensure signals are disconnected upon destruction

.github/workflows/linux.yml
Addresses https://github.com/canonical/multipass/issues/3991. Not exhaustive, but at least filter out some paths.
MULTI-1899
=> [ci] Skip Linux CI on unrelated changes

docs/explanation/driver.md, docs/explanation/mount.md, docs/how-to-guides/customise-multipass/set-up-the-driver.md, docs/how-to-guides/manage-instances/create-an-instance.md, docs/reference/command-line-interface/networks.md, docs/reference/settings/local-driver.md
[MULTI-1888](https://warthogs.atlassian.net/browse/MULTI-1888)
[MULTI-1893](https://warthogs.atlassian.net/browse/MULTI-1893)
[MULTI-1888]: https://warthogs.atlassian.net/browse/MULTI-1888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MULTI-1893]: https://warthogs.atlassian.net/browse/MULTI-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR is about adding the driver warning messages to all the lxd and libvirt related documentation pages.
=> lxd libvirt deprecation warning docs

.github/workflows/automatic-doc-checks.yml
If there are incompatibilities between separate changes to docs, we want to detect that before merging.
=> [ci] Trigger docs checks on merge_group too

.github/workflows/linux.yml
Allow in-progress workflows to be canceled when an external event requests them (e.g., the workflow run has been superseded with a new commit).
MULTI-1939
=> [gh/wf/linux.yml] allow workflow cancellation

.gitmodules, 3rd-party/submodule_info.md
This pull request updates the URL for the `xz-embedded` submodule to point to the GitHub repository for xz-embedded, which is more stable than the git.tukaani.org link that points to the GitHub repo anyways.
* [`.gitmodules`](diffhunk://#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584L10-R10): Updated the URL for the `xz-embedded` submodule from `https://git.tukaani.org/xz-embedded.git` to `https://github.com/tukaani-project/xz-embedded.git`.
=> update xz-embedded submodule url in gitmodules

docs/how-to-guides/install-multipass.md
=> Update macOS requirement

src/client/gui/lib/vm_action.dart
This pull request simplifies the `VmActionButton` widget in the `src/client/gui/lib/vm_action.dart` file by removing special styling related to the `delete` action. The Delete button previously was styled with a red background color, which was too strong of a call-to-action compared to the other Vm action buttons.
=> [gui] vm_delete button uses normal buildButton styling

src/client/cli/cmd/launch.cpp, src/daemon/daemon.cpp, src/rpc/multipass.proto
```
$     multipass list
No instances found.
$     multipass launch
Launched: frisky-sturgeon in zone zone1
$     multipass launch --zone zone1,zone3
launch failed: Invalid arguments supplied
$     multipass launch --zone zone1,
launch failed: Invalid arguments supplied
$     multipass launch --zone zone
launch failed: Invalid arguments supplied
$     multipass launch --zone zone3
Launched: quiet-lapwing in zone zone3
$     multipass list
Name                    State             IPv4             Image               Zone
frisky-sturgeon         Running           10.127.101.158   Ubuntu 24.04 LTS    zone1(a)
quiet-lapwing           Running           10.127.101.19    Ubuntu 24.04 LTS    zone3(a)
```
This pull request includes several changes to improve the `launch` command functionality in …
=> Add --zone argument to launch command

src/daemon/daemon.cpp, tests/daemon_test_fixture.cpp, tests/daemon_test_fixture.h, tests/test_daemon.cpp
on_restart re-initializes some daemon-side resources needed for the VM functionality, such as non-backend mounts like sshfs. this patch ensures that on_restart is executed for the VM's that are already running, or starting.
Closes: #4005
MULTI-1908
=> [daemon] trigger on_restart for a running VM after daemon boot

include/multipass/signal.h, include/multipass/top_catch_all.h, src/daemon/daemon_main.cpp, tests/test_daemon.cpp, tests/test_delayed_shutdown.cpp, tests/test_sshfsmount.cpp
The signal handler should be the first thing to register since the controller (e.g. user, snapd) can send signals immediately. Right now, the daemon either freezes or crashes when it's being launched and then immediately killed via Ctrl-C, which can also observed via running `snap restart multipass` in quick succession.
The signal handler uses `QCoreApplication::quit()` to wrap everything up, but use of `QCoreApplication::quit()` requires proper initialization of the QT resources first, so the signal handler should wait until that's done.
In order to ensure that this patch does the following:
- signal.h is moved from test/ to multipass/
- Added a top-level mp::Signal object to facilitate communication between the signal handler thread and the main thread
- mp::top_catch_all can now …
=> [daemon] register the signal handler immediately on start

src/client/gui/lib/catalogue/launch_form.dart
resolves #4028 
This pull request introduces a new feature to the `LaunchForm` in the `src/client/gui/lib/catalogue/launch_form.dart` file, allowing users to launch and configure the next item without closing the form. The most important changes include adding a new button, modifying the launch method to support the new functionality, and adjusting the form reset behavior.
New feature for launching and configuring the next item:
* Added a `launchAndConfigureNextButton` to the form, which allows users to launch the current item and immediately configure the next one. [[1]](diffhunk://#diff-1859f216fc901caa87909945aef29585a3d98e3b5e265a7e804870ae8a3a652fR253-R257) [[2]](diffhunk://#diff-1859f216fc901caa87909945aef29585a3d98e3b5e265a7e804870ae8a3a652fR293-R294)
Modifications to the launch …
=> [gui] add 'Launch & Configure next' button to launch form

.github/workflows/tics.yml, tests/lxd/test_lxd_backend.cpp
Adds Tiobe's TICS github action to the Multipass project
- Runs on a weekly basis (the Desktop team [SSDLC guide](https://docs.google.com/document/d/11BLKA6XC_HmrHVJO5qDhurnkq3xYTQBODTL5oEVmoVE/edit?tab=t.gewyardc36dz) suggests nightly)
- Each analysis takes about 4+hrs to run (may vary depending on the number of changed files between runs)
- The TICS custom action has some specific requirements which are not always clear
- The coverage report must be at `${{ github.workspace }}/coverage/coverage.xml`
- The project must be built beforehand with standard build tools and build directories
- Build files should be in `${{ github.workspace }}/build`
- `make` must be used for compilation (using `ninja` generator will fail the action)
- TICS analysis now includes and analyzes the `tests/` …
=> [CI] run tics on weekly schedule

tests/test_sftpserver.cpp
The test was expecting returned lastRead to be the same as the expected lastModified, which has a really small chance of not being true. Changed it to check the returned lastModified to be the same as the expected lastModified.
Resolves #4086
=> Fix flakey SFTP server test

tests/mock_logger.cpp
Right now, it's hard to tell which expect_log call is failed to be satisfied because the output is ambiguous:
```
error: Actual function call count doesn't match EXPECT_CALL(*this, log(lvl, _, HasSubstr(substr)))...
Expected: to be called once
Actual: never called - unsatisfied and active
```
The patch fixes that by utilizing the matcher description:
````
error: Actual function "my expected log string" call count doesn't match EXPECT_CALL(*this, log(lvl, _, HasSubstr(substr)))...
Expected: to be called once
Actual: never called - unsatisfied and active
```
=> [tests/mock_logger] Add substr as Description() for distinction

tests/test_data/no_image_downloads_in_datatype.json, tests/test_simple_streams_index.cpp
It is causing spurious coverage-related CI failures, such as: https://app.codecov.io/gh/canonical/multipass/pull/4090/indirect-changes
MULTI-2005
=> [tests/simple_streams] add test case for no image-downloads

.github/workflows/linux.patch, .github/workflows/linux.yml, snap/snapcraft.yaml
... for reliability. GitHub runners use a mirror-based failover scheme. Multipass's build step happens inside an LXC container, which does not benefit from this. This PR adds a new part named "inject-apt-mirrors" to [replicate the runner behavior](https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/configure-apt-sources.sh).
=> [snapcraft.yaml] mimic github runner's sources.list

src/client/gui/lib/main.dart, src/client/gui/lib/tray_menu.dart
Closes: #3919
Previously, the tray menu action **'Quit'** caused a function to immediately destroy the window. Now the usual process of closing window is taking place. This allows to consider the settings and perform the necessary tasks before closing.
Additionally, the restoration functionality of a hidden/minimized window has been added if there is a setting of the need to show a dialog before closing (**'Ask about running instances'**).
**To reproduce:**
Set setting _'Stop running instances'_ or _'Ask about running instances'_
Launch instance:
**Don't close the app Window, but Quit from the tray.**
Before:
After:
=> Honour the close settings when quitting from the tray

packaging/macos/postinstall-multipassd.sh.in
With our recent changes to permissions, it doesn't make sense for the daemon binary to not have similar restrictions applied to it. This PR applies those restrictions by making the daemon owned by root similar to how the storage directory is now owned by root.
MULTI-1998
=> Update daemon permissions

completions/bash/multipass
Improve the security of our bash completion in some respects, most notably by avoiding evaluating function input. See commit messages for further details.
MULTI-2010
=> Harden bash completion security a little

BUILD.linux.md, CMakeLists.txt, src/platform/backends/qemu/linux/qemu_platform_detail_linux.cpp, src/platform/backends/qemu/qemu_vmstate_process_spec.cpp, src/platform/platform_linux.cpp, tests/linux/test_platform_linux.cpp, tests/qemu/linux/test_qemu_platform_detail.cpp, tests/qemu/test_qemu_vmstate_process_spec.cpp
https://warthogs.atlassian.net/browse/MULTI-1933
In the development environment, `qemu-system-arm` and `qemu-efi-aarch64` need to be installed and `sudo cp /usr/share/qemu-efi-aarch64/QEMU_EFI.fd /usr/share/qemu/QEMU_EFI.fd` need to be run in order to make `qemu-system-arm -bios QEMU_EFI.fd ...` find the `QEMU_EFI.fd` file and access it with the right permission. On the other side, the snapcraft [copies](https://github.com/canonical/multipass/blob/3d329cb5a94056953785580149c5536baeadc1b0/snap/snapcraft.yaml#L338) the file into a snap confined folder, so there above-mentioned issues do not exist in deployment. 
The snap file can be downloaded [here](https://www.dropbox.com/scl/fi/z6rgdmnqi0ksu4odormao/multipass_1.16.0-dev.3744-gaad30415_arm64.snap?rlkey=w0d88ywq1ujbv7c3xri69szss&st=vio2wmpw …
=> Enabling qemu driver on linux arm cpu 

docs/explanation/driver.md, docs/reference/settings/local-driver.md
https://warthogs.atlassian.net/browse/MULTI-2012
Sync the default driver part of the documentation on linux os and arm cpu based on this [PR](https://github.com/canonical/multipass/pull/4050).
=> Update the qemu linux arm doc

completions/bash/multipass
Closes: #3682
Previously, when the TAB pressed, only ‘Running’ instances were completed.
Now, if the `--force` flag is provided, additionally taken into account 'Starting', 'Restarting', 'Suspending' and 'Suspended' ones.
**To reproduce:**
Run service:
`sudo /usr/local/bin/multipassd`
Run GUI:
`/usr/local/bin/multipass.gui`
start and then **suspend the instance**
**OR** start/stop/suspend tasks can be done from the CLI:
`multipass start --all`
`multipass suspend --all`
**Before:**
Open Bash and add the script:
`source <multipass>/completions/bash/multipass`
Check the instance is suspended:
`multipass ls`
Try the bash-completion (**'n'** is the first letter of the instance’s name):
`multipass stop --force n[TAB]`
_Nothing happens._
**After:**
Reopen Bash and add the script:
`source …
=> Added more Bash-complete instances in multipass stop --force

completions/bash/multipass
Clone of https://github.com/canonical/multipass/pull/4072. Fixes #3682. See original for details.
Authored by [Artem-OSSRevival](https://github.com/Artem-OSSRevival).
=> Added more Bash-complete instances in multipass stop --force (clone of  #4072)

.github/workflows/linux.patch, snap/snapcraft.yaml
Inject apt mirrors that are relevant for CI only on GH. These mirrors are typically not necessary in local environments and they [break builds on launchpad](https://launchpadlibrarian.net/798872671/buildlog_snap_ubuntu_jammy_arm64_multipass-beta_BUILDING.txt.gz).
MULTI-2025
=> [ci] Restrict custom archive mirrors to GH

.github/workflows/tics.yml
These packages were always required and TICS would just log a warning, but TIOBE made an update a few days ago that turns these warnings into errors.
=> [tics] add new deps

include/multipass/cloud_init_iso.h, src/iso/CMakeLists.txt, src/iso/cloud_init_iso.cpp, src/platform/backends/shared/base_virtual_machine_factory.cpp, tests/test_cloud_init_iso.cpp
- Removes some unnecessary conversions between `QString` and `std::string`
- Reduces the binary size by a few percentages of a `KB`
=> [cloud-init] replace Qt with C++ stl

tests/CMakeLists.txt
Referenced gtest code has been merged in for quite some time.
https://github.com/google/googletest/blob/7e2c425db2c2e024b2807bfe6d386f4ff068d0d6/googlemock/include/gmock/internal/gmock-pp.h#L31
=> [cmake] remove obsolete gtest workaround

src/client/cli/cmd/launch.cpp, tests/test_cli_client.cpp
Time to remove one of my first pieces of work in Multipass 🫡
=> [cli] remove deprecated `mem` option

src/platform/backends/shared/base_virtual_machine.cpp, tests/test_base_virtual_machine.cpp
Remove safety-net catch for generic runtime errors when waiting for SSH.
=> [vm] Drop transition safety net for runtime errors

snap/snapcraft.yaml
Qemu build fails with the following output in an arm64 environment:
[4/12] Generating po/bg/LC_MESSAGES/qemu-bg.mo with a custom command FAILED: po/bg/LC_MESSAGES/qemu.mo
/snap/gnome-42-2204-sdk/current/usr/bin/msgfmt -o po/bg/LC_MESSAGES/qemu.mo ../po/bg.po /snap/gnome-42-2204-sdk/current/usr/bin/msgfmt: error while loading shared libraries: libgettextsrc-0.21.so: cannot open shared object file: No such file or directory ninja: build stopped: subcommand failed.
The gettext package provides libgettextsrc-0.21.so.
MULTI-2036
=> [snap/snapcraft.yaml] add `gettext` to the build-packages

.github/workflows/linux.yml, .github/workflows/windows-macos.yml
This PR introduces [binary caching](https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-packages?pivots=linux-runner) for vcpkg. Since going open source, we can take advantage of [GitHub Packages](https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages) to host binary caches.
Binary caching is enabled by setting the `VCPKG_BINARY_SOURCES` environment variable. A tutorial for how to do this can be found [here](https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-packages) and was generally followed for changes in this PR.
For MacOS and ARM, there is seemingly no official support or guide, and with the differences in bundled packages in GitHub hosted runners, a little bit of tailoring is required. On non-Windows machines, …
=> [ci] add vcpkg binary caching

src/cert/ssl_cert_provider.cpp, src/platform/platform_win.cpp
There was a change in logic in when permissions are set for ssl certificates which caused newly created client certificates to have overly restrictive permissions. This fixes that.
Also there was a bug where unix permissions weren't converted to Windows permissions correctly. This fixes that.
Setting the permissions of the file to read by everyone does not change security since the parent folder maintains the user only access. However, in the future it would be nice to give read permissions directly to the user instead of everyone.
closes #4193
=> Fix client key permissions

src/client/gui/lib/daemon_unavailable.dart, src/client/gui/lib/ffi.dart, src/client/gui/lib/providers.dart
resolves #4175 
This pull request introduces changes to improve error handling and user experience when the FFI library fails to load. The updates include a new mechanism to detect FFI availability, enhancements to the `DaemonUnavailable` widget, and modifications to providers for better integration.
* [`src/client/gui/lib/ffi.dart`](diffhunk://#diff-0a91f284d9074caf859890b9d92d83e3eaeb2963f74491605435b5124bf5107bL20-R53): Introduced the `FFILibrary` class to encapsulate FFI library loading logic, handle errors gracefully, and provide utility methods (`isFFIAvailable` and `ffiLoadError`) for checking availability and accessing load errors.
* [`src/client/gui/lib/daemon_unavailable.dart`](diffhunk://#diff-45e88b27cc58ea15345a9f1736ad4d77b8f8ccf5eaa3fa0c85572876cad76a81R15-R74): Updated the …
=> [gui] Enhance FFI library loading

.github/workflows/linux.yml, .github/workflows/windows-macos.yml
When running outside of a PR, `Linux` and `Windows/macOS` have the same concurrency group leading to them cancelling each other.
=> [ci] distinguish reusable workflows concurrency groups

.github/workflows/windows-macos.yml
Fixes vcpkg caching on macOS 14.
Without this, the incantation to overwrite nuget fails: https://github.com/canonical/multipass/actions/runs/16224912911/job/45814502234#step:16:28
We could instead tweak the recipe to find nuget parts from the baked install, but this is a quicker fix that costs 12s per CI run and keeps our CI setup a little simpler (no need to branch based on macOS version).
=> [ci] Install nuget on macOS 14 with brew too

.github/workflows/tics.yml
Using single label to prevent confusion with multiple labels.
https://canonical-self-hosted-github-runner-docs.readthedocs-hosted.com/en/latest/usage/available_runners/
MULTI-2105
=> [ci] use dedicated self-hosted tiobe runner

tests/test_cloud_init_iso.cpp
read_returns_five_bytes_string mock was using std::strcpy to copy five characters from the string "NonJo". In reality, strcpy always terminates the destination with a '\0', which leads to an overflow since the destination is a 5-byte stack-allocated buffer.
This patch fixes that by replacing std::strcpy with std::memcpy.
MULTI-2156
=> [tests/cloud_init_iso] fix `read` mock stack overrun

src/platform/backends/shared/base_virtual_machine_factory.cpp, tests/qemu/test_qemu_backend.cpp
Debian and Fedora ship their cloud images with the `.qcow2` file extension which does not get picked up by `multipass clone`.
Fixes #4271 
---
MULTI-2150
=> [3rd-party images] include qcow2 files when cloning

src/platform/platform_win.cpp, src/sshfs_mount/sftp_server.cpp
chown is a platform-specific function which depends uid and gid. these values are not available in Windows, and the chown impl is by default returns -1. This causes filesystem operation failures in Windows hosts when sshfs mounts are used in guests. One example is as follows:
ubuntu@foo:~/Downloads$ echo "test" > foo.txt
-bash: foo.txt: Operation not permitted
This operation fails because it first lands in handle_open, which eventually calls chown to change the file's owner, which is a failure by default in Windows.
The patch fixes that by introducing a shim function, chown_shim which returns success when either uid or gid is set to no_id_info_available.
MULTI-2155
=> [sshfs-mount] make chown return 0 on Windows

.gitignore, src/client/cli/client.cpp, src/client/cli/cmd/CMakeLists.txt, src/client/cli/cmd/common_cli.cpp, src/client/cli/cmd/common_cli.h, src/client/cli/cmd/launch.cpp, src/client/cli/cmd/restart.cpp, src/client/cli/cmd/shell.cpp, src/client/cli/cmd/start.cpp, src/client/cli/cmd/wait_ready.cpp, src/client/cli/cmd/wait_ready.h, src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/daemon_main.cpp, src/daemon/daemon_rpc.cpp, src/daemon/daemon_rpc.h, src/rpc/multipass.proto, tests/CMakeLists.txt, tests/mock_client_rpc.h, tests/mock_daemon.h, tests/test_cli_client.cpp, tests/test_daemon.cpp, tests/test_daemon_wait_ready.cpp
**Feature: Add `multipass wait-ready` command**
**Description:**
This PR introduces a new CLI command, `multipass wait-ready`. This command allows users and scripts to pause execution until the Multipass daemon is fully initialized and ready to accept requests. This is particularly beneficial for automation workflows that need to ensure the daemon is operational before proceeding with other Multipass operations.
The `wait-ready` command works by:
1.  Initially polling the daemon's gRPC socket until it becomes available.
2.  Once the socket is available, it sends a `WaitReady` request to the daemon.
3.  The daemon, upon receiving this request, verifies its readiness by attempting to update image manifests (which implicitly checks connectivity to image servers).
4.  The command supports a …
=> [feat] Add wait-ready command to check Multipass daemon readiness

packaging/macos/com.canonical.multipassd.plist.in
resolves #4287 
Old versions of Multipass on MacOS had launchd listen to a hardcoded tcp socket opened at port 50051. This was updated in https://github.com/canonical/multipass/commit/0f77459b9aa3ebba13100bd63898b8b25aede952 but the definition in the plist file was never updated.  This PR removes the unused TCP socket from being created on port 50051
=> [macos] remove unused gRPC socket definition

packaging/macos/com.canonical.multipassd.plist.in
Increase the timeout after which launchd tires to wait for the daemon to
quit on SIGTERM and sends it a SIGKILL. The daemon can take a while to
quit before suspending VMs finish writing to disk. Fixes #4319.
=> [macos] Increase the timeout for launchd

git-hooks/commit-msg.py
The commit message linter enforces the rules for Git comments in the COMMIT_MSG, which causes trouble when a long path appears in the change summary.
The patch addresses this issue by removing all comments from the input before processing.
MULTI-2221
=> [commit-msg-hook] Strip comments before processing

include/multipass/cli/format_utils.h
The TimestampToNanoseconds function is only defined for valid timestamp values. The multipass::format::sorted function is converting the ts values without checking if they're valid first, leading to UB.
The patch fixes that by ensuring timestamp validity first.
=> [format-utils] Validate timestamps before compare

include/multipass/dart_ffi.h, src/client/gui/ffi/dart_ffi.cpp, src/client/gui/lib/ffi.dart, src/client/gui/lib/grpc_client.dart, src/client/gui/lib/providers.dart
This pull request introduces support for loading and using a root certificate for secure gRPC connections in the client GUI. The changes add a new FFI binding and retrieval method for the root certificate, update the credentials handling to include the root certificate, and propagate this through the provider setup.
**Certificate Management Improvements:**
* Added a new FFI function `get_root_cert` in both C++ (`dart_ffi.cpp`) and Dart (`ffi.dart`) to retrieve the root certificate from the platform. [[1]](diffhunk://#diff-ed42989e5f6878e79523cbc2b507752aae44f3c4ca80ba052c743a48cd218d7fR21-R22) [[2]](diffhunk://#diff-cbb1d58f70f76ec2eaf0b1aca1a176bb82bcbf480341ccb19d4d033f4be1f11cR98-R118) [[3]](diffhunk://#diff-0a91f284d9074caf859890b9d92d83e3eaeb2963f74491605435b5124bf5107bR140-R144) …
=> [gui] Add certificate check to grpc client

.github/workflows/prune-packages.yml
Binaries from vcpkg caching will slowly accumulate as versions of dependencies change. This workflow will periodically go through GitHub packages and delete old versions.
For example, [fmt](https://github.com/canonical/multipass/pkgs/nuget/fmt_x64-linux-release) has an old version that isn't used anymore.
---
MULTI-2084
=> [ci] delete old vcpkg cached binaries

src/platform/backends/hyperv/hyperv_virtual_machine.cpp, src/platform/backends/hyperv/hyperv_virtual_machine.h
The cached management IP address becomes stale on some operations when it happens out-of-band, like "multipass restart", where it's a SSH-induced guest reboot.
This patch fixes that by invalidating the cached IP address on every update_state() invocation.
Fixes: #3354
MULTI-2068
=> [hyper-v] Invalidate cached mgmt IP address on update_state()

docs/conf.py, docs/how-to-guides/customise-multipass/build-multipass-images-with-packer.md, docs/how-to-guides/customise-multipass/set-up-the-driver.md, docs/how-to-guides/troubleshoot/troubleshoot-launch-start-issues.md
This PR fixes the failing CI caused by rate-limited Hashicorp links for Packer.
It also corrects the hardcoded path for `sitemap.xml` to remove the `/en/` string from url.
=> [docs] Fix 404 and sitemap url

src/platform/backends/shared/linux/backend_utils.cpp, src/platform/backends/shared/linux/backend_utils.h, src/platform/backends/shared/macos/backend_utils.cpp, tests/macos/test_backend_utils.cpp
This PR adds some validation to the process that resolves IP addresses from MAC addresses on macOS. Due to past changes made by Apple, we now use ARP to resolve IP addresses. The ARP table is, however, a cache that can potentially contain old and stale IP addresses before they are purged.
For launching Ubuntu Core images, this creates several problems. The initialization of an Ubuntu Core image is completed in two phases which is separated by the guest rebooting itself. Networking is partially initialized during the first phase, and macOS assigns it an IP address. During the second phase after the guest reboots, guest networking finishes initializing causing macOS to assign it another IP address. Now, ARP contains two IP addresses for the same MAC address.
To solve this, I have added a …
=> [macos] IP address validation

.github/workflows/prune-packages.yml
Couple fixes and improvements here
- Only query NuGet package types
- Packages are fetched at the `org` level, so filter out non-Multipass packges
- Create Mattermost alert on workflow failure
- Entire workflow won't fail if one package fails to be deleted
Example workflow can be found [here](https://github.com/canonical/multipass/actions/runs/17925720184). Old packages were pruned in a previous test run [here](https://github.com/canonical/multipass/actions/runs/17924005630/job/50965570706).
=> [ci] Prune vcpkg binaries kaizen

src/daemon/default_vm_image_vault.cpp, src/platform/backends/lxd/lxd_vm_image_vault.cpp, tests/disabling_macros.h, tests/lxd/test_lxd_image_vault.cpp, tests/test_image_vault.cpp
Local file URLs should have three slashes after "file:".
This just adds an error message alerting the user to the fact that non-local file URLs aren't supported (at least, not yet), and suggesting a fix. The wording feels a little clumsy to me, but I'm not sure of a better way to phrase it without becoming confusing.
(Recreated this from #4341 in the original repo so CI passes.)
=> [daemon] Improve file URL error message (#4198)

docs/how-to-guides/customise-multipass/authenticate-clients-with-the-multipass-service.md, docs/how-to-guides/customise-multipass/configure-multipass-default-logging-level.md, docs/how-to-guides/customise-multipass/index.md, docs/how-to-guides/customise-multipass/integrate-with-windows-terminal.md, docs/how-to-guides/customise-multipass/migrate-from-hyperkit-to-qemu-on-macos.md, docs/how-to-guides/customise-multipass/use-a-different-terminal-from-the-system-icon.md
This PR solves the issue of standardizing the internal linking to use the recommended Myst cross-linking [standard ](https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html)instead of relative linking to internal documents. 
This provides the docs with capability of always linking to the correct document even in situations where a file has been moved or renamed.
MULTI-2157
=> [fix] Cross-references for `customise-multipass/`

docs/index.md
This PR updates the landing page (specifically the "In this documentation" section) to align with the standardized format used across other canonical products , improving consistency and user experience.
- Replaced markdown table with a responsive grid layout (and cards) for and aligning to design patterns of other canonical products.
The new format follows the same structure as other canonical product documentation:
• [Chisel docs](https://documentation.ubuntu.com/chisel/en/latest/)
• [Ubuntu server docs](https://documentation.ubuntu.com/server/)
MULTI-2031
=> docs: Standardize landing page format

.editorconfig
This is just a first pass at copying some of our style rules into a [`.editorconfig`](https://editorconfig.org/) file so that (hopefully) everyone's favorite editors will see these rules and set the various options appropriately. There are probably more rules we could set, but this should cover the basics.
If you're an Emacser like me, then you can add this to your `.dir-locals.el` to enable editorconfig support in the Multipass repo, if it's not already enabled globally in your config: `((nil . ((mode . editorconfig))))`
=> [format] Add formatting rules to `.editorconfig`

docs/reference/command-line-interface/find.md, docs/tutorial/index.md, src/client/gui/lib/catalogue/catalogue.dart, src/daemon/daemon_config.cpp, src/daemon/ubuntu_image_host.h, tests/mock_process_factory.cpp, tests/test_base_virtual_machine_factory.cpp, tests/test_cli_prompters.cpp, tests/test_daemon.cpp, tests/test_global_settings_handlers.cpp, tests/windows/powershell_test_helper.cpp, tests/windows/test_powershell.cpp
=> [daemon] Remove support for appliances

src/network/url_downloader.cpp
Resolves #1098 
This PR modifies the URLDownloader constructor to check if the `cache_dir` parameter is empty before appending "network-cache". Previously, URLDownloader constructor was unconditionally appending "network-cache" to the cache directory path, even when initialized with an empty path. This caused QDir("") to resolve to the current directory, resulting in ./network-cache being created wherever tests were executed.
Now when tests instantiate URLDownloader with just a timeout parameter (which calls the no-argument constructor that passes an empty Path()), the cache_dir_path will now remain empty instead of being set to "./network-cache". This prevents Qt's QNetworkDiskCache from creating the network-cache directory in the current working directory when running the …
=> [network] Handle empty cache dir path in url_downloader constructor
